Refactor category select
fullstack-development/react-redux-starter-kit pull request #13
Opened 2017-11-06 05:33 UTC by Gulyaev52

2017-11-06 14:10 UTC, Znack requested changes

2017-11-06 14:10 UTC, Znack commented on src/features/categorySelect/redux/reducers/data.ts
> +    case 'CATEGORY_SELECT:LOAD_CATEGORIES_SUCCESS': {
А там же выше нормально типизирован ICategoriesResponse, тут пейлоад не выводит тип?

2017-11-06 14:10 UTC, Znack commented on src/features/categorySelect/redux/reducers/data.ts
> +    case 'CATEGORY_SELECT:LOAD_CATEGORIES_SUCCESS': {
В редьюсерах просто надо по-минимуму использовать any, это критически важная часть приложения

2017-11-06 14:12 UTC, Gulyaev52 commented on src/features/categorySelect/redux/reducers/data.ts
> +    case 'CATEGORY_SELECT:LOAD_CATEGORIES_SUCCESS': {
Я не доглядел просто)

2017-11-06 14:15 UTC, Znack commented on src/features/categorySelect/redux/reducers/data.ts
> +    case 'CATEGORY_SELECT:LOAD_CATEGORIES_SUCCESS': {
Ага, ну тут добавь просто, и в принципе все, с меня апрув :)

2017-11-06 14:47 UTC, Znack approved these changes

2017-11-06 14:48 UTC, Znack commented
@NikitaRzm Никита, ждем тебя :)

2017-11-08 12:38 UTC, Znack approved these changes

2017-11-23 05:31 UTC, NikitaRzm approved these changes

2017-11-23 05:31 UTC, merged