WIP: 130. Migrating to eslint
fullstack-development/react-redux-starter-kit pull request #151
Opened 2019-10-16 13:13 UTC by prodderman

Перевел правила tslint в eslint по возможности.
Заюзал [Димину основу для конфига](https://github.com/fullstack-development/react-redux-starter-kit/issues/130#issuecomment-542126521) и появилось куча ошибок по типу: модуль такой-то должен быть в dependencies, а не в devDependencies, или метод такой-то дожен быть объявлен перед методом таким-то (потому что используются стрелочные методы в некоторых местах), или использование глобальных require и прочие ошибки форматирования. Мне их в этой задаче править?

2019-10-16 15:52 UTC, in19farkt commented on webpack/common.ts
> +      eslint: true,
предлагаю выпилить отсюда еслинт, чтобы сборку разгрузить и линтить отдельной командой. Кто что думает? @kinda-neat @chmnkh @NikitaRzm

2019-10-16 15:52 UTC, in19farkt commented on .eslintrc.js
> +    // ban-keywords is missing in eslint
а мы можем по максимуму этот список почистить?

Возможно некоторые правила уже по умолчанию (или в airbnb-typescript) выставлены так как здесь, а некоторые может и не стоит переопределять.

2019-10-16 15:52 UTC, in19farkt commented on .eslintrc.js
> +    // ban-keywords is missing in eslint
Как минимум всё что связано со спейсингами, семиколонами и в целом форматированием нужно повыпиливать. Этим будет заниматься притир

2019-10-16 15:52 UTC, in19farkt commented on package.json
> +    "fork-ts-checker-webpack-plugin": "^1.5.1",
tslint'овские зависимости забыл выпилить

2019-10-16 15:53 UTC, in19farkt commented
@prodderman да, в этом ПР исправляй все ошибки линтинга.

2019-10-16 15:58 UTC, in19farkt commented
По поводу разделения депсов и девДепсов. Ящитаю нужно делать так:

- в депсы попадают те пакеты которые в конечном итоге попадают в бандл, т.е. используются в рантайме
- в девДепсы попадает всё остальное, пакеты для сборки/линтинга/прогона тестов/@types
- в файлах с вебпак-конфигами и файлах SSR мы игнорим правило еслинта на импорт пакетов из девДепсов

Такое разбиение мне кажется позволит держать package.json в чистоте, видеть что у нас в рантайме вообще используется.

2019-10-16 16:02 UTC, in19farkt commented
но я не уверен, что сейчас стоит реструктурировать депсы, т.к. у нас еще в параллельных ветках идут работы с зависимостями, будут жесткие конфликты в package-lock. Предлагаю сейчас заигнорить это правило в конфиге, но оставить TODO, чтобы не забыли потом навести порядок там.

2019-10-16 16:20 UTC, in19farkt commented
Еще проверь что нет правила на обязательность префикса `I` для типов объявленных с помощью `interface`. Тут https://github.com/fullstack-development/react-redux-starter-kit/issues/150 вроде пришли к тому что это не нужно.

2019-10-16 16:21 UTC, Znack commented
Я думаю, что после каждлого мержа в мастер код должен оставаться в мастере чистым — eslint не ругаться, тс компилиться и тд. Поэтому тут либо вырубить правила пока, которые мы не поддерживаем (возможно с TODO и с обяхательным созданием ишью на восстановления этих правил, причем этим ишью надо будет повышенный приорттет), либо прямо тут с исправлениями, если это не очень сложно

2019-10-16 16:24 UTC, in19farkt commented
я думаю тема с депсами не критичная, поэтому можно заигнорить пока с тудухой. Как более менее зависимости устаканятся, тогда и вернем это правило

2019-10-18 03:17 UTC, chmnkh commented on .eslintrc.js
> +    "react/jsx-boolean-value": "off",
https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-boolean-value.md

а нафиг это? по дефолту же там "never", то есть мы не напишем `flag={true}`, я считаю это крутое правило и я бы "never" и оставил, плюс еще недавно заумался над тем, чтобы флаги писать как `flag?: true`, в связке с этим правилом вообще огонь, ящитаю

2019-10-18 03:32 UTC, chmnkh commented on .eslintrc.js
> +    // ban-keywords is missing in eslint
тоже ощущение сложилось, что половина из этого в аирбнб есть

2019-10-18 03:46 UTC, chmnkh commented on webpack/common.ts
> +      eslint: true,
я вообще не понимаю нафига нам на этапе сборки линтинг и тайпчекинг

мне кажется достаточно вполне иметь чип конфиг для работы, а линтить и тайпчекать на препуш/прекоммит какой-нибудь, не?

2019-10-18 05:39 UTC, in19farkt commented on webpack/common.ts
> +      eslint: true,
тайпчекинг ящитаю нужен, ты когда рефакторишь и где-то что-то изменяешь, хочешь видеть в каких местах что отвалилось и не сошлось по типам. А вот линтинг, это реально второстепенная штука без которой можно писать код.

2019-10-18 07:54 UTC, kinda-neat commented on webpack/common.ts
> +      eslint: true,
Да, согласен, на момент работы хватает тайпчекинга, я бы на прекоммит повесил проверку линтером и если есть косяки, то пусть правятся сразу, а не потом отдельным коммитом который проставляет запятые, пробелы, отступы, было бы круто поставить это по дефолту, а еще добавить какой-нибудь --force чтобы без линтинга закоммитить и запушить (в редких кейсах возможно это нужно)

2019-10-18 09:49 UTC, chmnkh commented on .eslintrc.js
> +    "react/jsx-boolean-value": "off",
Степан тут справедливо заметил, что `flag?: true` плохо вкатит, если во флаг будет переменная передаваться, поэтому идея дичь(

2019-10-18 15:43 UTC, in19farkt commented on webpack/common.ts
> +      eslint: true,
не нужно ничего вешать на прекоммит, мне кажется это дич и этими проверками должны заниматься CI. CI на проверку ПРов настраивается за полчаса (с учетом изучения доки).

2019-10-18 15:52 UTC, in19farkt commented
@prodderman проблем с правилом import/no-unresolved ?

Я сейчас столкнулся с ней, еслинт не подхватывает почему-то paths из tsconfig. Решил установкой eslint-import-resolver-typescript и правками в eslintrc:
```
  settings: {
    'import/resolver': {
      typescript: {
        alwaysTryTypes: true,
      },
    },
  },
```

2019-10-21 04:40 UTC, kinda-neat commented on webpack/common.ts
> +      eslint: true,
> не нужно ничего вешать на прекоммит, мне кажется это дич и этими проверками должны заниматься CI. CI на проверку ПРов настраивается за полчаса (с учетом изучения доки).

Мне больше всего здесь не нравятся коммиты чисто для того чтобы поправить запятую, форматирование как таковое

2019-10-21 05:48 UTC, in19farkt commented on webpack/common.ts
> +      eslint: true,
> Мне больше всего здесь не нравятся коммиты чисто для того чтобы поправить запятую, форматирование как таковое

Это лучше чем на каждый коммит вламываться в творческий процесс этими линтингами. Может мне удобнее нахерачить всё по быстрому в 10 коммитов, а потом с чувством выполненного долга коммитнуть все правки по линтингу. В своей ветке я должен иметь право коммитить всё что угодно, мне даже не обязательно следить за тем что мой код вообще собирается, не говоря уже о каких-то там ошибках форматирования...

2019-10-29 13:00 UTC, kinda-neat commented on .eslintrc.js
> +    'react/jsx-filename-extension': ['error', { 'extensions': ['.js', '.jsx', '.ts', '.tsx'] }],
убираем

2019-10-29 14:14 UTC, kinda-neat requested changes

2019-10-29 14:14 UTC, kinda-neat commented on .eslintrc.js
> +    'react/state-in-constructor': 'off',
never

2019-10-29 14:14 UTC, kinda-neat commented on .eslintrc.js
> +    'react/no-danger': 'off',
врубаем

2019-10-29 14:14 UTC, kinda-neat commented on .eslintrc.js
> +    'import/no-default-export': 'error',
в будущем надо будет обсудить что делаем с компонентами в HOC'ах

2019-10-29 14:14 UTC, kinda-neat commented on .eslintrc.js
> +    '@typescript-eslint/indent': ['error', 2],
убираем, преттиер разберется в будущем

2019-10-29 14:14 UTC, kinda-neat commented on .eslintrc.js
> +    '@typescript-eslint/no-unused-vars': 'error',
убираем, оставляем дефолтное

2019-10-29 14:14 UTC, kinda-neat commented on .eslintrc.js
> +    '@typescript-eslint/type-annotation-spacing': ['error', {
затрется притиром, так что кттс выпилить

2019-10-29 14:24 UTC, kinda-neat requested changes

2019-10-29 14:24 UTC, kinda-neat commented on .eslintrc.js
> +    'import/no-extraneous-dependencies': "off", // TODO: uncomment ['error', { devDependencies: ['**/test.tsx', '**/test.ts'] }],
надо поправить package.json (там ща беспорядок), далее раскомментим 
\+ еще вынести в ишью: рефакторнуть package.json:scripts

2019-10-30 08:29 UTC, in19farkt commented
@prodderman Пачка конфликтов подъехала :)

2019-10-30 14:03 UTC, in19farkt commented on package.json
> +    "husky": "^3.0.9",
Нужно выпилить

2019-10-30 14:03 UTC, in19farkt commented on jest.config.js
> +    'ContainersProvider.tsx$': '<rootDir>/src/core/__mocks__/fileMock.ts',
верни экранирование для `.` но с двумя слешами, как в регулярке выше

2019-10-30 14:03 UTC, in19farkt commented on server/starters.ts
>    const render = require('../static').default;
тут походу сломано, т.к. в `src/server.tsx ` больше нет дефолтного экспорта. Попробуй сделать так и проверь SSR:

```diff
- const render = require('../static').default;
+ const render = require('../static').render;
```

2019-10-30 14:03 UTC, in19farkt commented on src/client.tsx
> +/* eslint-disable-next-line */
Тут же вроде всё норм должно быть? зачем тут disable?

2019-10-30 14:03 UTC, in19farkt commented on src/core/App.tsx
> +import 'normalize.css';
а это почему сюда спустилось? это же модуль из dependencies

2019-10-30 14:03 UTC, in19farkt commented on src/core/configureApp.ts
>    // tslint:disable:max-line-length
удоли

2019-10-30 14:03 UTC, in19farkt commented on src/shared/helpers/bootstrap.tsx
> +    return undefined;
этот return можно убрать

2019-10-31 11:30 UTC, in19farkt submitted a review, later dismissed

2019-10-31 11:45 UTC, kinda-neat commented on package.json
> +    "eslint-autofix": "./node_modules/.bin/eslint . --ext .ts --ext .tsx --fix"
тяжело добавить lint:autofix чтобы сразу и стилевые и жс поправил?

2019-10-31 12:07 UTC, kinda-neat requested changes

2019-10-31 12:07 UTC, kinda-neat commented on package.json
> +    "concurrently": "^5.0.0",
на нашел где этот пакет используется

2019-10-31 12:07 UTC, kinda-neat commented on package.json
> +    "eslint-import-resolver-typescript": "^2.0.0",
используется?

2019-10-31 12:07 UTC, kinda-neat commented on package.json
> +    "lint": "eslint . --ext .js,.jsx,.ts,.tsx && tsc --noEmit --pretty",
ты чо ничего не запушил? ты же на моих глазах менял eslint -> ./node_modules/.bin/eslint

2019-10-31 12:08 UTC, in19farkt commented on package.json
> +    "lint": "eslint . --ext .js,.jsx,.ts,.tsx && tsc --noEmit --pretty",
а это еще зачем?

2019-10-31 12:12 UTC, in19farkt commented on package.json
> +    "eslint-autofix": "./node_modules/.bin/eslint . --ext .ts --ext .tsx --fix"
Еще нужно будет какое-то соглашение принять по неймингу npm скриптов, а то сейчас каша какая-то, где-то через дефис, где-то через двоеточие, где-то начинаем с глагола, где-то с существительного

2019-10-31 12:18 UTC, kinda-neat commented on package.json
> +    "lint": "eslint . --ext .js,.jsx,.ts,.tsx && tsc --noEmit --pretty",
у Степана тогда не запустился линтинг, видимо из-за того что npm i не сделал, ну ща ок, просто мне интересно запушил он или нет последние изменения)

2019-10-31 12:18 UTC, kinda-neat commented on package.json
> +    "eslint-autofix": "./node_modules/.bin/eslint . --ext .ts --ext .tsx --fix"
рил ток

2019-10-31 12:19 UTC, in19farkt commented on package.json
> +    "lint": "eslint . --ext .js,.jsx,.ts,.tsx && tsc --noEmit --pretty",
Вроде всё запушил и даже некоторые мои замечания уже поправил

2019-10-31 12:40 UTC, prodderman commented on package.json
> +    "eslint-import-resolver-typescript": "^2.0.0",
да ничего не вышло, надо выпилить

2019-10-31 12:41 UTC, prodderman commented on package.json
> +    "concurrently": "^5.0.0",
пригодится, что бы параллельно запусить несколько npm скриптов

2019-10-31 13:30 UTC, prodderman commented on package.json
> +    "concurrently": "^5.0.0",
хотя не, выпилил

2019-10-31 13:30 UTC, prodderman commented on package.json
> +    "eslint-autofix": "./node_modules/.bin/eslint . --ext .ts --ext .tsx --fix"
добавил

2019-10-31 13:39 UTC, in19farkt submitted a review, later dismissed

2019-11-01 04:54 UTC, kinda-neat requested changes

2019-11-01 04:54 UTC, kinda-neat commented on src/client.tsx
> +/* eslint global-require: 0 */
давай положим ближе к месту использования, я не сразу допер где этот require, положи так:
![image](https://user-images.githubusercontent.com/27883524/68002333-fb224100-fc9a-11e9-9ad6-8a3fd86408ed.png)

2019-11-01 04:54 UTC, kinda-neat commented on package.json
> +    "eslint-autofix": "./node_modules/.bin/eslint . --ext .ts --ext .tsx --fix"
Блен, мне кажется если делаем, то сразу надо на все случаи жизни команды добавить:
- eslint
- stylelint (ща этого нету)
- lint-all
- eslint-autofix
- stylelint-autofix
- autofix-all

2019-11-01 05:41 UTC, sk1e commented on package.json
> +    "eslint-autofix": "./node_modules/.bin/eslint . --ext .ts --ext .tsx --fix"
зачем отдельные команды для линта?  В сборке же удобнее.

зачем отдельные команды для фикса варнингов, когда оставить одну которая будет править всё?

2019-11-01 05:45 UTC, kinda-neat requested changes

2019-11-01 05:45 UTC, kinda-neat commented on src/features/repositoriesSearch/view/components/RepositoryAttribute/RepositoryAttribute.tsx
> +  const onValueKeyPress = (e: React.KeyboardEvent<HTMLSpanElement>) => {
facepalm

а как же handle?

2019-11-01 05:45 UTC, kinda-neat commented on src/features/usersSearch/view/components/UsersAvatarsWall/UsersAvatarsWall.scss
> +    background: none;
зачем?

2019-11-01 05:45 UTC, kinda-neat commented on src/features/usersSearch/view/components/UsersAvatarsWall/UsersAvatarsWall.tsx
> +    return Object.values(this.avatarsLoadingStatus).every(x => x === true);
x => x === true -> R.identity

2019-11-01 05:45 UTC, kinda-neat commented on src/features/usersSearch/view/components/UsersAvatarsWall/__tests__/index.test.ts
> +    const avatars = component
что за avatars в котором лежит button?

2019-11-01 05:45 UTC, sk1e requested changes

2019-11-01 05:45 UTC, sk1e commented on package.json
> +    "lint": "eslint . --ext .js,.jsx,.ts,.tsx && tsc --noEmit --pretty",
зачем отдельные команды для линта? В сборке же удобнее.

2019-11-01 05:45 UTC, sk1e commented on package.json
> +    "stylelint-autofix": "./node_modules/.bin/stylelint \"./src/**/*.scss\" --fix",
зачем отдельные команды для фикса варнингов, когда оставить одну которая будет править всё?

2019-11-01 05:47 UTC, kinda-neat commented on package.json
> +    "stylelint-autofix": "./node_modules/.bin/stylelint \"./src/**/*.scss\" --fix",
ну можно и так, мне показалось что может быть необходимость по частям все фиксить и смотреть что фиксится отдельно

2019-11-01 06:16 UTC, in19farkt commented on package.json
> +    "eslint-autofix": "./node_modules/.bin/eslint . --ext .ts --ext .tsx --fix"
а мне кажется нехер засирать скрипты всякой шалупонью, там итак трешак в этих скриптах, нужно половину выпиливать)) И прикинь у нас еще пару инструментов для линтинга добавится)

ящитаю нужно оставить 2 команды `lint` и `lint:autofix`, которые запустят все возможные линтинги и все возможные автофиксы. А если нужно запустить что-то отдельно, просто копипастишь нужную часть скрипта и запускаешь с помощью `npx {script}`

2019-11-01 06:24 UTC, in19farkt commented on src/features/usersSearch/view/components/UsersAvatarsWall/UsersAvatarsWall.tsx
> +    return Object.values(this.avatarsLoadingStatus).every(x => x === true);
похоже ты херню написал)) насколько я помню
```typescript
R.identity = <T>(value: T) => () => value;
```
на `R.equals(true)` еще можно заменить, или вообще на `.every(Boolean)`.

2019-11-01 06:27 UTC, in19farkt commented on package.json
> +    "eslint-autofix": "./node_modules/.bin/eslint . --ext .ts --ext .tsx --fix"
@prodderman  и убери плиз эти штуки из скриптов `./node_modules/.bin/`, они там не нужны

2019-11-01 07:35 UTC, kinda-neat commented on src/features/usersSearch/view/components/UsersAvatarsWall/UsersAvatarsWall.tsx
> +    return Object.values(this.avatarsLoadingStatus).every(x => x === true);
![image](https://user-images.githubusercontent.com/27883524/68009553-cd49f600-fcb4-11e9-931a-663d75eae109.png)
Функция identity возвращает то, что ей передали)

2019-11-01 08:22 UTC, in19farkt commented on src/features/usersSearch/view/components/UsersAvatarsWall/UsersAvatarsWall.tsx
> +    return Object.values(this.avatarsLoadingStatus).every(x => x === true);
Я к тому, что `R.identity` не равно `x => x === true`, результат будет одинаковый пока мы на вход даем true/false, а если залетит что-то другое, то результат будет разный.

2019-11-01 08:24 UTC, in19farkt commented on src/features/usersSearch/view/components/UsersAvatarsWall/UsersAvatarsWall.tsx
> +    return Object.values(this.avatarsLoadingStatus).every(x => x === true);
Хотя если this.avatarsLoadingStatus имеет тип Record<string, boolean>, или нам не нужна проверка на строгое равенство `true`, то можно и `R.identity` заюзать.

2019-11-01 08:26 UTC, kinda-neat commented on src/features/usersSearch/view/components/UsersAvatarsWall/UsersAvatarsWall.tsx
> +    return Object.values(this.avatarsLoadingStatus).every(x => x === true);
я не понимаю зачем писать === true, когда у тебя там и так булины, достаточно просто их вернуть

2019-11-01 08:28 UTC, in19farkt commented on src/features/usersSearch/view/components/UsersAvatarsWall/UsersAvatarsWall.tsx
> +    return Object.values(this.avatarsLoadingStatus).every(x => x === true);
> я не понимаю зачем писать === true, когда у тебя там и так булины, достаточно просто их вернуть. типа из-за type-safe, не type-safe, ну хз

Да, согласен, тут это уместно))

2019-11-01 15:28 UTC, chmnkh commented on src/features/usersSearch/view/components/UsersAvatarsWall/UsersAvatarsWall.tsx
> +    return Object.values(this.avatarsLoadingStatus).every(x => x === true);
я не согласен, потому что `x === true` это очевиднее, чем писать айдентити

написать здесь айдентити - какая-то неявная бадяга-понт, ящитаю, и чтобы это понять нужно больше усилий приложить, чем явное `x === true`

при этом минусов в том как написано сейчас перед айдентити я не вижу вообще, буков мало, воспринимается легче, чем айдентити

2019-11-01 15:31 UTC, chmnkh commented on src/features/usersSearch/view/components/UsersAvatarsWall/UsersAvatarsWall.tsx
> +    return Object.values(this.avatarsLoadingStatus).every(x => x === true);
Я в `every` жду функцию, которая будет отвечать да/нет, а айдентити вообще не про это

2019-11-01 15:36 UTC, kinda-neat commented on src/features/usersSearch/view/components/UsersAvatarsWall/UsersAvatarsWall.tsx
> +    return Object.values(this.avatarsLoadingStatus).every(x => x === true);
а что если да/нет у тебя уже описано, осталось только взять и посмотреть что оно всё да? и тут вместо того чтобы еще раз чекать что да === да, ты просто результат возвращаешь, причем здесь какая-то искусственная задача ваще

2019-11-01 15:36 UTC, kinda-neat commented on src/features/usersSearch/view/components/UsersAvatarsWall/UsersAvatarsWall.tsx
> +    return Object.values(this.avatarsLoadingStatus).every(x => x === true);
> при этом минусов в том как написано сейчас перед айдентити я не вижу вообще, буков мало, воспринимается легче, чем айдентити

для меня выглядит как масло масляное

2019-11-01 15:50 UTC, chmnkh commented on src/features/usersSearch/view/components/UsersAvatarsWall/UsersAvatarsWall.tsx
> +    return Object.values(this.avatarsLoadingStatus).every(x => x === true);
> а что если да/нет у тебя уже описано, осталось только взять и посмотреть что оно всё да? и тут вместо того чтобы еще раз чекать что да === да, ты просто результат возвращаешь, причем здесь какая-то искусственная задача ваще

> для меня выглядит как масло масляное

да нет, просто у меня есть определенное восприятие `every` методов, например, в коде, и когда я их вижу, я их читаю, типа "каждый элемент === true" (как в текущем коде). пофиг - булины там или не булины

если же я вижу в `every` `identity`, то для меня это сразу ломает привычный способ восприятия `every`, потому что я уже не могу вопрос задать, у меня мозги спотыкаются и я начинаю думать "так так падажжи че тут у нас булины ага"

если это я просто поломанный и у меня у одного такая проблема - базара 0, но для меня так

2019-11-02 01:19 UTC, Znack commented on src/features/usersSearch/view/components/UsersAvatarsWall/UsersAvatarsWall.tsx
> +    return Object.values(this.avatarsLoadingStatus).every(x => x === true);
> на R.equals(true) еще можно заменить, или вообще на .every(Boolean).
 
`equals(true)` тоже хотел предложить как вариант, мне и `identity` норм, к этому быстро привыкаешь и только поначалу кажется что "так падажжи, че тут у нас :)

а вот `.every(Boolean)` я б не рекомендовал, типы теряются, в итоге если ты случайно массив перед этим мапнул и у тебя стал не массив булинов, а массив объектов, то просто все элементы всегда будут `true` обозначать (потому что даже `Boolean({})` — это `true`)

2019-11-02 08:33 UTC, sk1e commented on src/features/usersSearch/view/components/UsersAvatarsWall/UsersAvatarsWall.tsx
> +    return Object.values(this.avatarsLoadingStatus).every(x => x === true);
Согласен с Алексеем. В аргументе every ожидается увидеть предикат, коим R.identity не является.

2019-11-03 16:44 UTC, kinda-neat commented on src/features/usersSearch/view/components/UsersAvatarsWall/UsersAvatarsWall.tsx
> +    return Object.values(this.avatarsLoadingStatus).every(x => x === true);
> Согласен с Алексеем. В аргументе every ожидается увидеть предикат, коим R.identity не является.

Справедливое замечание, но проверять на true === true я не стал бы и воткнул бы R.identity

2019-11-03 16:47 UTC, kinda-neat commented on src/features/usersSearch/view/components/UsersAvatarsWall/UsersAvatarsWall.tsx
> +    return Object.values(this.avatarsLoadingStatus).every(x => x === true);
еще вот так можно
Object.values(this.avatarsLoadingStatus).reduce(R.and);

2019-11-03 16:50 UTC, kinda-neat commented on src/features/usersSearch/view/components/UsersAvatarsWall/UsersAvatarsWall.tsx
> +    return Object.values(this.avatarsLoadingStatus).every(x => x === true);
ёмае, так тут еще и Statuses, а не просто Status

2019-11-03 17:52 UTC, kinda-neat commented on src/features/usersSearch/view/components/UsersAvatarsWall/UsersAvatarsWall.tsx
> +    return Object.values(this.avatarsLoadingStatus).every(x => x === true);
![image](https://user-images.githubusercontent.com/27883524/68089613-486e0080-fe9d-11e9-8098-39e2a046c01d.png)

2019-11-04 04:21 UTC, chmnkh commented on src/features/usersSearch/view/components/UsersAvatarsWall/UsersAvatarsWall.tsx
> +    return Object.values(this.avatarsLoadingStatus).every(x => x === true);
> еще вот так можно, здесь семантично и кратко
> Object.values(this.avatarsLoadingStatus).reduce(R.and);

чо там, как борьба со сложностью?

я, блин, не понимаю

есть ПРОСТЕЙШЕЕ выражение `arr.some(x => x === true)` которое просто МАКСИМАЛЬНО легко читается и воспринимается, ты же какие-то извраты предлагаешь, то засовывая `identity` на место предиката, то предлагая какие-то редьюсы с эндом, и это все из-за того, что `x === true` это булин и `x` - это тоже булин? это какая-то на ровном месте выдуманная проблема, вот честно

я понимаю, если бы решения, которые ты предлагал, как-то бы элегантнее были, но это не так, `identity` на месте предиката и `reduce` с эндом не делают код красивее, они его делают тупо сложнее, и все

2019-11-04 04:23 UTC, kinda-neat commented on src/features/usersSearch/view/components/UsersAvatarsWall/UsersAvatarsWall.tsx
> +    return Object.values(this.avatarsLoadingStatus).every(x => x === true);
reduce(R.and) - элегантно, красиво, семантично

2019-11-04 04:24 UTC, chmnkh commented on src/features/usersSearch/view/components/UsersAvatarsWall/UsersAvatarsWall.tsx
> +    return Object.values(this.avatarsLoadingStatus).every(x => x === true);
я бы понял, если бы ты топил за `arr.some(equals(true))`, потому что это уже явно декларативнее, но то что ты предлагаешь - это просто какая-то неочевидная фигня, которая только менее читаемым код делает, на мой взгляд

2019-11-04 04:27 UTC, chmnkh commented on src/features/usersSearch/view/components/UsersAvatarsWall/UsersAvatarsWall.tsx
> +    return Object.values(this.avatarsLoadingStatus).every(x => x === true);
> reduce(R.and) - элегантно, красиво, семантично

reduce(R.and) - по сравнению с some(R.equals(true)) - сложно, не понятно, не очевидно

2019-11-04 04:28 UTC, kinda-neat commented on src/features/usersSearch/view/components/UsersAvatarsWall/UsersAvatarsWall.tsx
> +    return Object.values(this.avatarsLoadingStatus).every(x => x === true);
> > reduce(R.and) - элегантно, красиво, семантично
> 
> reduce(R.and) - по сравнению с some(R.equals(true)) - сложно, не понятно, не очевидно

согласен что менее, но буков меньше и все короче, давай every(R.equals(true))

2019-11-04 04:30 UTC, chmnkh commented on src/features/usersSearch/view/components/UsersAvatarsWall/UsersAvatarsWall.tsx
> +    return Object.values(this.avatarsLoadingStatus).every(x => x === true);
у меня есть задача: посмотреть, все ли флаги в массиве `true`

вот скажи, какой код очевиднее `arr.every(equals(true))` или `arr.reduce(and)`

ты предлагаешь на задачу посмотреть в разрезе "свернуть в один булин через И", что в принципе сложнее и в контексте того, что флаги в принципе здесь означают, менее очевидно

постановка вопроса "все ли флаги выставлены" и "свертка всех флагов через И в булин будет тру" это прямо вообще разных уровней сложности и очевидности вещи

2019-11-04 04:32 UTC, Znack commented on src/features/usersSearch/view/components/UsersAvatarsWall/UsersAvatarsWall.tsx
> +    return Object.values(this.avatarsLoadingStatus).every(x => x === true);
я бы тоже предпочёл `arr.some(equals(true))`, но `reduce(R.and)` я бы не стал категорично относить в "сложно, не понятно, не очевидно" по той причине, что после небольшого порога входа это становится довольно (но не на все 100%) легко, понятно и очевидно, потому что ты быстро в голове можешь заменить `reduce(R.and)` на `arr[0] && arr[1] && arr[2] && arr[3] && arr[4] && ...`. Другое дело, что `arr.some(equals(true))` буквально читается как обычный английский и без всяких преобразований в голове :)

2019-11-04 04:33 UTC, kinda-neat commented on src/features/usersSearch/view/components/UsersAvatarsWall/UsersAvatarsWall.tsx
> +    return Object.values(this.avatarsLoadingStatus).every(x => x === true);
у тебя есть задача - узнать, все ли аватары загружены areAllAvatarsLoaded, а вот как ты будешь ее решать уже другой вопрос, я бы в качестве эксперимента сделал бы это через reduce(R.and)

2019-11-04 04:34 UTC, Znack commented on src/features/usersSearch/view/components/UsersAvatarsWall/UsersAvatarsWall.tsx
> +    return Object.values(this.avatarsLoadingStatus).every(x => x === true);
> в качестве эксперимента сделал бы

Хорошее уточнение 😆

2019-11-04 04:36 UTC, chmnkh commented on src/features/usersSearch/view/components/UsersAvatarsWall/UsersAvatarsWall.tsx
> +    return Object.values(this.avatarsLoadingStatus).every(x => x === true);
> я бы тоже предпочёл `arr.some(equals(true))`, но `reduce(R.and)` я бы не стал категорично относить в "сложно, не понятно, не очевидно" по той причине, что после небольшого порога входа это становится довольно (но не на все 100%) легко, понятно и очевидно, потому что ты быстро в голове можешь заменить `reduce(R.and)` на `arr[0] && arr[1] && arr[2] && arr[3] && arr[4] && ...`. Другое дело, что `arr.some(equals(true))` буквально читается как обычный английский и без всяких преобразований в голове :)

сложно, не понятно, не очевидно - только в контексте сравнения с `every(equals(true))`

понятное дело, что сам по себе это простой редьюс, но в сравнении с кодом с `every` (который, как ты сам заметил, читается просто как английский язык) - там просто конская сложность, которая ничем не оправдана, ящитаю

2019-11-04 04:36 UTC, kinda-neat commented on src/features/usersSearch/view/components/UsersAvatarsWall/UsersAvatarsWall.tsx
> +    return Object.values(this.avatarsLoadingStatus).every(x => x === true);
> Другое дело, что arr.some(equals(true)) буквально читается как обычный английский и без всяких преобразований в голове :)

это, по моему мнению ключевой аргумент, но все равно, здесь это не так критично, мне кажется нужно заморачиваться больше над кусками где по 10 функций а не две

2019-11-04 04:37 UTC, chmnkh commented on src/features/usersSearch/view/components/UsersAvatarsWall/UsersAvatarsWall.tsx
> +    return Object.values(this.avatarsLoadingStatus).every(x => x === true);
> у тебя есть задача - узнать, все ли аватары загружены areAllAvatarsLoaded, а вот как ты будешь ее решать уже другой вопрос, я бы в качестве эксперимента сделал бы это через reduce(R.and)

эксперимента? в чем именно эксперимент и для чего он проводится?

2019-11-04 04:38 UTC, Znack commented on src/features/usersSearch/view/components/UsersAvatarsWall/UsersAvatarsWall.tsx
> +    return Object.values(this.avatarsLoadingStatus).every(x => x === true);
> нужно заморачиваться больше над кусками где по 10 функций а не две

ну мы же обсуждаем общие правила, применимые в других местах. в итоге обсуждаемая здесь тема затронет сотни или тысячи мелких функций, которые будет пистаь кто-то из тех, кто в данном ПР принимает участие :)

2019-11-04 04:38 UTC, kinda-neat commented on src/features/usersSearch/view/components/UsersAvatarsWall/UsersAvatarsWall.tsx
> +    return Object.values(this.avatarsLoadingStatus).every(x => x === true);
Всё, я уже признал что го оставим с equals, у себя на проекте я заюзаю reduce(R.and) как только представится возможность, базарить в след раз будем за другим МРом

2019-11-04 04:40 UTC, chmnkh commented on src/features/usersSearch/view/components/UsersAvatarsWall/UsersAvatarsWall.tsx
> +    return Object.values(this.avatarsLoadingStatus).every(x => x === true);
> это, по моему мнению ключевой аргумент, но все равно, здесь это не так критично, мне кажется нужно заморачиваться больше над кусками где по 10 функций а не две

больше - это не значит, что не надо заморачиваться над такими кусками, это раз

два: давай вспомним, кто же тут начал заморачиваться и оставил дискашен)

три: если бы я в коде встретил место, где можно было бы написать как предлагаю я, а оно было бы написано через `reduce(and)`, я бы сначала чуток бомбанул, а потом бы переписал, потому что это переусложнение и переклиночка так писать, имхо

2019-11-04 04:42 UTC, kinda-neat commented on src/features/usersSearch/view/components/UsersAvatarsWall/UsersAvatarsWall.tsx
> +    return Object.values(this.avatarsLoadingStatus).every(x => x === true);
>_<, ща бомбит у меня, я уже выше написал что согласен оставить а ты дальше накидываешь
![image](https://user-images.githubusercontent.com/27883524/68100004-32d9f480-fef8-11e9-8da2-85df4ec3f452.png)

2019-11-04 04:45 UTC, chmnkh commented on src/features/usersSearch/view/components/UsersAvatarsWall/UsersAvatarsWall.tsx
> +    return Object.values(this.avatarsLoadingStatus).every(x => x === true);
да потому что там рассинхрон вышел: я написал одно, потом подумал, дописал еще, обновил страницу, и в итоге твой коммент между моими двумя оказался, и там понеслось))

2019-11-04 04:46 UTC, chmnkh commented on src/features/usersSearch/view/components/UsersAvatarsWall/UsersAvatarsWall.tsx
> +    return Object.values(this.avatarsLoadingStatus).every(x => x === true);
Резюме для @prodderman 

пишем `every(equals(true))`

2019-11-04 04:48 UTC, prodderman commented on src/features/usersSearch/view/components/UsersAvatarsWall/UsersAvatarsWall.tsx
> +    return Object.values(this.avatarsLoadingStatus).every(x => x === true);
мы тут eslint прикручиваем, или рефакторим?

2019-11-04 04:48 UTC, kinda-neat commented on src/features/usersSearch/view/components/UsersAvatarsWall/UsersAvatarsWall.tsx
> +    return Object.values(this.avatarsLoadingStatus).every(x => x === true);
> да потому что там рассинхрон вышел: я написал одно, потом подумал, дописал еще, обновил страницу, и в итоге твой коммент между моими двумя оказался, и там понеслось))
![image](https://user-images.githubusercontent.com/27883524/68100143-f78bf580-fef8-11e9-935a-a9a9578d7ec2.png)

2019-11-04 04:50 UTC, kinda-neat commented on src/features/usersSearch/view/components/UsersAvatarsWall/UsersAvatarsWall.tsx
> +    return Object.values(this.avatarsLoadingStatus).every(x => x === true);
> мы тут eslint прикручиваем, или рефакторим?

уже поздно, уже все решили

2019-11-04 04:59 UTC, chmnkh commented on src/features/usersSearch/view/components/UsersAvatarsWall/UsersAvatarsWall.tsx
> +    return Object.values(this.avatarsLoadingStatus).every(x => x === true);
> мы тут eslint прикручиваем, или рефакторим?

донный подход, имхо, в чем проблема какие-то маленькие вещи вот так походу по-другому написать? трудозатрат вот для тебя лично практически нету - уже за тебя все подумали и посмотрели, а проект мы лучше сделали

2019-11-05 05:15 UTC, kinda-neat commented on src/features/usersSearch/view/components/UsersAvatarsWall/UsersAvatarsWall.tsx
> +    return Object.values(this.avatarsLoadingStatus).every(x => x === true);
> мы тут eslint прикручиваем, или рефакторим?

ты чисто зашёл поворчать что ли? давай сделай эти несколько несчастных коммитов и вмерджим

2019-11-06 05:19 UTC, in19farkt commented
@prodderman какой статус по ПРу? когда сможешь доделать?

2019-11-10 16:30 UTC, prodderman commented on src/features/usersSearch/view/components/UsersAvatarsWall/UsersAvatarsWall.scss
> +    background: none;
что зачем?

2019-11-10 16:32 UTC, kinda-neat commented on src/features/usersSearch/view/components/UsersAvatarsWall/UsersAvatarsWall.scss
> +    background: none;
сбрасывать стили эти дефолтные >_<. так у каждой кнопки делаем? может в одном месте сбросить?

2019-11-10 16:32 UTC, kinda-neat commented on src/features/usersSearch/view/components/UsersAvatarsWall/UsersAvatarsWall.scss
> +    background: none;
тоже самое с ul, li, вот мне никогда не уперлись эти дефолтные отступы, list-style: none каждый раз писать такое себе

2019-11-10 16:36 UTC, kinda-neat commented
![image](https://user-images.githubusercontent.com/27883524/68547332-bf157b80-0412-11ea-98a5-5994829ed6ba.png)
ну, названия уже лучше, это респект

2019-11-10 16:38 UTC, kinda-neat commented on src/features/usersSearch/view/components/UsersAvatarsWall/__tests__/index.test.ts
> +    const avatars = component
нет, смысл был в том, что в const avatars лежит button, тогда почему переменная называется avatars?

2019-11-12 07:55 UTC, kinda-neat commented
> @prodderman какой статус по ПРу? когда сможешь доделать?

@prodderman вопросы в воздух что ли летят? ты можешь нас ориентировать как-то? чтобы если что мы эту задачу кому-то другому отдали, вот Лехе Ч например, вообще нифига непонятно что у тебя в голове, так что описывай словами, надоело тебе из раза в раз напоминать

2019-11-12 08:22 UTC, prodderman commented
> > @prodderman какой статус по ПРу? когда сможешь доделать?
> 
> @prodderman вопросы в воздух что ли летят? ты можешь нас ориентировать как-то? чтобы если что мы эту задачу кому-то другому отдали, вот Лехе Ч например, вообще нифига непонятно что у тебя в голове, так что описывай словами, надоело тебе из раза в раз напоминать

Передал задачу Лехе @chmnkh

2019-11-12 08:23 UTC, kinda-neat commented
> > > @prodderman какой статус по ПРу? когда сможешь доделать?
> > 
> > 
> > @prodderman вопросы в воздух что ли летят? ты можешь нас ориентировать как-то? чтобы если что мы эту задачу кому-то другому отдали, вот Лехе Ч например, вообще нифига непонятно что у тебя в голове, так что описывай словами, надоело тебе из раза в раз напоминать
> 
> Передал задачу Лехе @chmnkh

спасибо за ответ спустя неделю и два меншена -_-

2019-11-12 08:49 UTC, chmnkh commented
@kinda-neat @in19farkt готово

@prodderman капец ты блин, неделю переменную переименовывал))

2019-11-12 08:49 UTC, chmnkh approved these changes

2019-11-12 10:04 UTC, in19farkt approved these changes

2019-11-12 10:05 UTC, in19farkt commented
@sk1e твой аппрув еще нужен, без него ничего не получится :(

2019-11-12 10:12 UTC, sk1e approved these changes

2019-11-12 10:16 UTC, merged

2019-11-12 10:17 UTC, in19farkt commented
еее!!!