Ife 157 get rid of some helpers
fullstack-development/react-redux-starter-kit pull request #160
Opened 2019-11-12 09:08 UTC by chmnkh

#157

2019-11-15 06:55 UTC, Znack commented
Конфликтики :)

2019-11-15 06:56 UTC, in19farkt commented
дык оно же wip

2019-11-19 11:12 UTC, chmnkh commented
@in19farkt @sk1e @kinda-neat готово

2019-11-19 11:17 UTC, sk1e requested changes

2019-11-19 11:17 UTC, sk1e commented on src/features/usersSearch/view/containers/UsersSearchForm/UsersSearchForm.tsx
> +  private getFilters = createSelector(
`getFilters` -> `selectFilters`?

2019-11-19 11:21 UTC, sk1e requested changes

2019-11-19 11:21 UTC, sk1e commented on src/features/usersSearch/view/containers/UsersSearchForm/UsersSearchForm.tsx
> +        (value: any, key: keyof typeof filters) => {
мне кажется value можно затипизировать тут через`value: typeof filters[keyof filters]`

2019-11-19 12:14 UTC, chmnkh commented on src/features/usersSearch/view/containers/UsersSearchForm/UsersSearchForm.tsx
> +        (value: any, key: keyof typeof filters) => {
![image](https://user-images.githubusercontent.com/18498637/69145647-b69efe00-0b00-11ea-9491-f9365cb06fdd.png)

там вообще по типам обосрань получается полная, я не вижу смысла именно `value` типизировать в условиях, когда дальше с `filtersValuesFormattersMap` и с `key` проблемы, хз как там разрулить адекватно

2019-11-19 12:19 UTC, sk1e commented on src/features/usersSearch/view/containers/UsersSearchForm/UsersSearchForm.tsx
> +        (value: any, key: keyof typeof filters) => {
ну и хрен с ним тогда

2019-11-19 12:19 UTC, sk1e submitted a review, later dismissed

2019-11-20 08:06 UTC, Znack commented on src/services/i18n/locales/en.ts
> +      max: 'Max',
🤣

2019-11-20 08:07 UTC, Znack commented
Ждём @in19farkt 

Тут получается сразу пачка ишьюсов будет закрыта?

2019-11-20 08:19 UTC, chmnkh commented on src/services/i18n/locales/en.ts
> +      max: 'Max',
ваще подстава да

2019-11-20 08:20 UTC, chmnkh commented
> Тут получается сразу пачка ишьюсов будет закрыта?

Да

2019-11-20 08:25 UTC, kinda-neat commented on src/features/usersSearch/view/containers/UsersSearchForm/UsersSearchForm.tsx
> +import * as RA from 'ramda-adjunct';
во, теперь ту пачку булинов можно заменить на RA.allEqualTo(true, avatarsLoadingStatuses])

2019-11-20 09:57 UTC, chmnkh commented
после коммита отвалился аппрув сереги, но он двумя руками за был!

2019-11-20 10:57 UTC, sk1e submitted a review, later dismissed

2019-11-21 03:55 UTC, chmnkh commented
@in19farkt @kinda-neat аппрувы аппрувы даем не стесняемся

2019-12-05 03:24 UTC, kinda-neat commented
не знаю куда написать, но ща заметил что shared/redux/makeSelectFeatureState называется, а должно makeFeatureStateSelector, надо переименовать когда-нибудь

2019-12-14 09:36 UTC, in19farkt requested changes

2019-12-14 09:36 UTC, in19farkt commented on src/features/repositoriesSearch/view/containers/RepositoriesSearchForm/RepositoriesSearchForm.tsx
> +    (formValues: IRepositoriesSearchFormFields) => formValues,
тут не совсем тоже самое получилось, прошлая версия мемоизировалась по `formValues` и по `props.t`. Изменение языка приводило к пересчету лейблов. Сейчас при изменении языка лейблы не подхватят новые переводы до тех пор пока не изменится `formValues`.

2019-12-14 09:36 UTC, in19farkt commented on src/features/usersSearch/view/containers/UsersSearchForm/UsersSearchForm.tsx
> +  private selectFilters = createSelector(
тут такой же косяк с переводами

2019-12-14 09:36 UTC, in19farkt commented on src/features/usersSearch/view/containers/UsersSearchForm/UsersSearchForm.tsx
> +        (value: any, key: keyof typeof filters) => {
можно попробовать такое:
```ts
type Filters = typeof filters;

<K extends keyof Filters>(value: Filters[K], key: K) => {
  // ...
}
```

2019-12-14 09:36 UTC, in19farkt commented on src/features/usersSearch/view/containers/UsersSearchForm/UsersSearchForm.tsx
> +            ? (filtersValuesFormattersMap as any)[key]
тут без `as any` никак?

2019-12-14 09:36 UTC, in19farkt commented on src/features/usersSearch/view/containers/UsersSearchForm/UsersSearchForm.tsx
> +        (value: any, key: keyof typeof filters) => {
тут просто небольшая ошибка, ты написал `keyof filters`, а надо было `keyof typeof filters`

2019-12-25 12:00 UTC, sk1e commented
@chmnkh каков статус?

2019-12-26 02:03 UTC, chmnkh commented
займусь после нг

2020-01-23 06:04 UTC, chmnkh commented on src/features/repositoriesSearch/view/containers/RepositoriesSearchForm/RepositoriesSearchForm.tsx
> +    (formValues: IRepositoriesSearchFormFields) => formValues,
я вообще не понял нафига там мемоизировать сам коллбэк передаваемый, а вот функцию, его создающую, я замемоизировал

https://github.com/fullstack-development/react-redux-starter-kit/pull/160/commits/c204f313d660635b576b04a45c81975d80c888b9

2020-01-23 06:38 UTC, chmnkh commented on src/features/usersSearch/view/containers/UsersSearchForm/UsersSearchForm.tsx
> +            ? (filtersValuesFormattersMap as any)[key]
тут с верхним дискашеном:
```
можно попробовать такое:

type Filters = typeof filters;

<K extends keyof Filters>(value: Filters[K], key: K) => {
  // ...
}
```
связано, поэтому верхний дискашн зарезолвлю сразу

там такая тема, что `key` - юнион из кучи строк (все филды формы т.е.), а в `filtersValuesFormattersMap` всего 2 форматтера определено (для двух филдов формы)

нам по логике надо брать либо из этой мапы форматтер, либо вообще ниче не форматить, т.е. `identity`
здесь `in` нифига не сужает тип, и тс не дает взять `filtersValuesFormattersMap` по `key`

https://github.com/fullstack-development/react-redux-starter-kit/pull/160/commits/e49b68a763acd5f3cc7bb4f48d986d49d078db05

2020-01-28 03:02 UTC, chmnkh commented on src/features/repositoriesSearch/view/containers/RepositoriesSearchForm/RepositoriesSearchForm.tsx
> +    (formValues: IRepositoriesSearchFormFields) => formValues,
@in19farkt

2020-03-25 09:59 UTC, chmnkh commented
@in19farkt глянь, пожалуйста, уже неприлично много времени прошло)) тут 5 сек, я щас заново вспоминал че делал, довольно быстро вышло

2020-06-22 13:00 UTC, in19farkt approved these changes

2020-06-22 13:01 UTC, merged