132 ts toolbelt
fullstack-development/react-redux-starter-kit pull request #162
Opened 2019-11-21 06:27 UTC by chmnkh

#132

2019-11-21 14:02 UTC, sk1e submitted a review, later dismissed

2019-11-22 07:30 UTC, Znack commented on src/shared/view/elements/Input/NumberInput.tsx
> +          inputComponent: makeNumberInput({ prefix, thousandSeparator, decimalScale }) as any,
что ж так?

2019-12-14 12:23 UTC, in19farkt commented on src/core/ContainersProvider.tsx
> +type IEntryWithContainer<K extends string, T extends React.ComponentType<any>> = IWithContainers<{ [D in K]: T }> & Pick<IFeatureEntry, 'reduxEntry'>;
чето тут херня какая-то получилась... Смысл сабсета был в том, чтобы можно было уточнить какой-то тип. И в случае изменения типа IFeatureEntry, и дальнейшей несовместимости с уточненным типом, тайпскрипт выдал бы ошибку.

2019-12-14 12:23 UTC, in19farkt commented on src/shared/types/app.ts
> +export interface IFeatureEntry extends Partial<IWithContainers<Record<string, React.ComponentType<any>>>> {
тут тоже трешак какой-то получился, почти как в лиспе `>>>>`

2019-12-14 12:23 UTC, in19farkt commented on src/shared/view/elements/CheckboxInput/CheckboxInput.tsx
> +  const checkboxProps: A.Equals<CheckboxProps, typeof rest> extends 1 ? CheckboxProps : unknown = rest;
тут наверное лучше вместо `1` написать `B.True`.

2019-12-25 12:00 UTC, sk1e commented
@chmnkh каков статус?

2019-12-26 02:03 UTC, chmnkh commented
займусь после нг

2020-01-23 08:16 UTC, chmnkh commented on src/shared/view/elements/Input/NumberInput.tsx
> +          inputComponent: makeNumberInput({ prefix, thousandSeparator, decimalScale }) as any,
в старом коде по типам все поломано было потому что, и только за счет этого тс не ругался

там переусложненная бадяга какая-то написана на мой взгляд, я вообще не хотел бы эти инпуты где-то еще использовать, для таких элементарных компонент такая сложность как там вообще неуместна я считаю

просто жалко даже усилия в эту строну направлять, если честно, не вижу в этом особой важности, потому что там и так на соплях все работает не понять как

2020-01-23 08:24 UTC, chmnkh commented on src/core/ContainersProvider.tsx
> +type IEntryWithContainer<K extends string, T extends React.ComponentType<any>> = IWithContainers<{ [D in K]: T }> & Pick<IFeatureEntry, 'reduxEntry'>;
так IFeatureEntry зависит от IWithContainers, это тип зависит от того и от того, в чем проблема-то в итоге?  мб пример есть?

2020-01-23 08:24 UTC, chmnkh commented on src/shared/types/app.ts
> +export interface IFeatureEntry extends Partial<IWithContainers<Record<string, React.ComponentType<any>>>> {
не понял претензии, выглядит не очень красиво, но тут довольно простые вещи типа Partial, Record, React.ComponentType, все легко читается как по мне

2020-01-28 03:02 UTC, chmnkh commented on src/shared/view/elements/Input/NumberInput.tsx
> +          inputComponent: makeNumberInput({ prefix, thousandSeparator, decimalScale }) as any,
@Znack

2020-01-28 03:02 UTC, chmnkh commented on src/core/ContainersProvider.tsx
> +type IEntryWithContainer<K extends string, T extends React.ComponentType<any>> = IWithContainers<{ [D in K]: T }> & Pick<IFeatureEntry, 'reduxEntry'>;
@in19farkt

2020-01-28 05:15 UTC, Znack submitted a review, later dismissed

2020-06-22 09:46 UTC, in19farkt submitted a review, later dismissed

2020-06-22 09:46 UTC, in19farkt commented
@Znack мержим?

2020-06-22 09:56 UTC, Znack commented
Ого, я забыл уже :) Ну вроде норм, а @sk1e будешь смотреть?

2020-06-22 10:03 UTC, sk1e requested changes

2020-06-22 10:03 UTC, sk1e commented on src/shared/view/elements/RadioGroupInput/RadioGroupInput.tsx
> +  const radioGroupProps: A.Equals<RadioGroupProps, typeof rest> extends 1 ? RadioGroupProps : unknown = rest;
1 -> Boolean.True

2020-06-22 10:33 UTC, in19farkt commented on src/shared/view/elements/RadioGroupInput/RadioGroupInput.tsx
> +  const radioGroupProps: A.Equals<RadioGroupProps, typeof rest> extends 1 ? RadioGroupProps : unknown = rest;
Пушнул правку, обнови ревью плиз

2020-06-22 10:33 UTC, sk1e approved these changes

2020-06-22 10:34 UTC, merged