translatе readme into Russian
fullstack-development/react-redux-starter-kit pull request #170
Opened 2019-12-30 08:53 UTC by EvgeniyChuprov

Не знаю стоит ли переводить `create-feature` и как лучше перевести `production environment`, по моему, `производственная среда` немного странно звучит.

2020-01-06 08:31 UTC, kinda-neat commented on README.md
> +Модульный стартовый комплект для проектов React + Redux + React Router.
а зачем нужен pull request?

2020-01-07 06:06 UTC, Znack requested changes

2020-01-07 06:06 UTC, Znack commented on README.md
> +Модульный стартовый комплект для проектов React + Redux + React Router.
А как без него сделать предлагаешь?

2020-01-07 06:06 UTC, Znack commented on README.md
> +- ```npm run prod``` производственная среда в режиме просмотра
можно "продакшн режим"

2020-01-07 06:28 UTC, in19farkt commented on README.md
> +Модульный стартовый комплект для проектов React + Redux + React Router.
Видимо вопрос Макса про то, что ПР непонятно откуда вообще.

Где иша/задача? Зачем ридми на русский переводим, а не на английский? Кто решил что нужно перевести на русский?

2020-01-09 08:35 UTC, chmnkh commented on README.md
> +Модульный стартовый комплект для проектов React + Redux + React Router.
выяснилось, что у нас была половина ридми на одном языке, половина на другом, и решили на русский перевести)

2020-01-09 13:17 UTC, Znack commented on README.md
> +Модульный стартовый комплект для проектов React + Redux + React Router.
ага, мы это как то в обсуждениях вынесли, что у нас рунглиш в описании :)

2020-01-09 13:18 UTC, Znack approved these changes

2020-01-09 13:18 UTC, Znack commented
@in19farkt @chmnkh @kinda-neat давайте ещё один аппрув или коммент :)

2020-01-09 15:57 UTC, in19farkt commented on README.md
>  ## NPM scripts
заголовок не переведен. в линке выше хеш нужно будет тоже поменять

2020-01-09 15:57 UTC, in19farkt commented on README.md
> +- ```npm run prod``` продакшн режим в режиме просмотра
мне одному кажется что "режим в режиме" - это "масло масляное"?

2020-01-09 15:57 UTC, in19farkt commented on README.md
> +- ```npm run prod``` продакшн режим в режиме просмотра
и "режим просмотра" как-то звучит странно

2020-01-09 16:25 UTC, kinda-neat commented on README.md
> +Модульный стартовый комплект для проектов React + Redux + React Router.
все как Диман описал

2020-01-09 16:26 UTC, kinda-neat commented on README.md
> +Модульный стартовый комплект для проектов React + Redux + React Router.
а зачем на русский? где это обсуждение? смысл переводить на русский? на мой взгляд, вкладывать ресурсы в то чтобы перевести на русский язык - это "медвежья услуга" и неразумно

2020-01-09 16:26 UTC, kinda-neat commented on README.md
> +Модульный стартовый комплект для проектов React + Redux + React Router.
@Znack @in19farkt @chmnkh

2020-01-10 03:06 UTC, krashaen commented on README.md
> +Модульный стартовый комплект для проектов React + Redux + React Router.
> Видимо вопрос Макса про то, что ПР непонятно откуда вообще.
> 
> Где иша/задача? Зачем ридми на русский переводим, а не на английский? Кто решил что нужно перевести на русский?

Вот иша) Но идея была в том, что привести к одному языку, видимо выбрали русский)

2020-01-10 03:57 UTC, kinda-neat commented on README.md
> +Модульный стартовый комплект для проектов React + Redux + React Router.
вот иша - это где?)

2020-01-10 05:09 UTC, krashaen commented on README.md
> +Модульный стартовый комплект для проектов React + Redux + React Router.
> вот иша - это где?)

Сенк, чет ссылка не подцепилась, поправил)

2020-01-10 05:29 UTC, chmnkh commented on README.md
> +Модульный стартовый комплект для проектов React + Redux + React Router.
"стартер кит" не переводится, я считаю, "стартовый комплект"  - это какое-то несуществующее словосочетание в данном контексте

2020-01-10 05:38 UTC, chmnkh commented on README.md
> +Модульный стартовый комплект для проектов React + Redux + React Router.
мне вообще кажется что текущее ридми это дно, дело не в том что там рунглишь только, а в том, что там вообще не понять что написано

я бы вообще подумал над тем как его полностью перепилить сначала, а потом бы уже язык выбирал

еще отдельный мой поинт в том, что куча вещей, которые были переведены на русский, в принципе не переводятся, типа "стартер кит" или "вотч режим", но это другой вопрос

2020-01-10 09:18 UTC, in19farkt commented on README.md
> +Модульный стартовый комплект для проектов React + Redux + React Router.
@chmnkh плюсую

2020-01-10 09:22 UTC, kinda-neat commented on README.md
> +Модульный стартовый комплект для проектов React + Redux + React Router.
> Зачем ридми на русский переводим, а не на английский? Кто решил что нужно перевести на русский?

на это я ответов не получил, ну ок, все равно откатываемся на этап ранее

2020-01-10 09:26 UTC, kinda-neat commented on README.md
> +Модульный стартовый комплект для проектов React + Redux + React Router.
нет такого понятия "русский оперсорс", опенсорс он и в Африке на английском. Захочет какой-нибудь чувак не понимающий русский заюзать наш стартеркит, так он посчитает ридми на русском рофлом и обойдет стороной. если мы пишем здесь на русском, не понимаю смысла это в "оперсорс" выкладывать, потому что он не в опенсорсе, он не доступный людям

2020-01-10 09:32 UTC, chmnkh commented on README.md
> +Модульный стартовый комплект для проектов React + Redux + React Router.
ну я тоже в целом не против, чтобы дока на английском была написана, тем более что там не будет каких-то сложных текстов (не должно быть, по крайней мере)

2020-01-13 03:39 UTC, EvgeniyChuprov commented on README.md
> +Модульный стартовый комплект для проектов React + Redux + React Router.
Как в таких случаях лучше писать?
Starter-kit для проектов React + Redux + React Router.
или
Стартер-кит для проектов React + Redux + React Router.
Модульный тоже странно звучит, но вроде и нужен тут.
Возможно, луче так?)
Модульный starter-kit для проектов использующих React + Redux + React Router.

2020-03-25 09:56 UTC, chmnkh commented
Че тут по итогу решили? Я предлагаю закрыть пр, тем более, что Евгений не доделал и ушел, и оставить ишу "перевести ридми на английский".

@Znack @in19farkt @kinda-neat @krashaen

2020-03-25 10:55 UTC, Znack commented
Ну и в свете последних событий, мы скорее всего будем остатки на английский переводить, а не наоборот :)

2020-03-25 10:55 UTC, closed without merging