Add yeoman generator
fullstack-development/react-redux-starter-kit pull request #18
Opened 2017-11-14 05:48 UTC by DYAPIK

2017-11-17 02:49 UTC, Znack approved these changes
@in19farkt @NikitaRzm Я все глянул, вроде все норм, Дима даже поддержку  flow  зафигачил, но там Влад потом подпилит нормально. Вроде код в фичах тоже норм, как по мне

2017-11-17 04:13 UTC, in19farkt requested changes

2017-11-17 04:13 UTC, in19farkt commented on README.md
> +1) sudo npm install -g yo
А можно сделать его локальным для проекта?
Чтобы не делать лишних телодвижений, и чтобы сразу после `npm install` можно было выполнить `npm run create-feature`, который проверит был ли проинициализирован локальный yeoman, и если нет то запустит скрипт инициализации (2, 3, 4 шаги), после чего запустит `./node_modules/.bin/yo create-feature`.

2017-11-17 04:16 UTC, in19farkt commented
Есть много замечаний по структуре темплейта фичи и наполнению файлов.
Также было бы неплохо добавить гибкости в генератор фичи (нужен ли редакс, нужна ли сага, ...) и в зависимости от выбора юзера формировать наполнение файлов.

2018-01-11 12:14 UTC, in19farkt approved these changes

2018-01-11 12:27 UTC, Znack requested changes

2018-01-11 12:27 UTC, Znack commented on generators/__tests__/app.js
> +'use strict';
файлик лишний? :)

2018-01-11 12:34 UTC, NikitaRzm approved these changes

2018-01-11 12:34 UTC, merged

2018-01-11 12:35 UTC, in19farkt commented on generators/__tests__/app.js
> +'use strict';
Да, это от Димаса осталось, надо будет выпилить)