Updated typescript verdion to 2.7
fullstack-development/react-redux-starter-kit pull request #29
Opened 2018-02-03 09:52 UTC by in19farkt

2018-02-08 04:45 UTC, Znack approved these changes

2018-02-09 11:05 UTC, NikitaRzm requested changes

2018-02-09 11:05 UTC, NikitaRzm commented on src/core/FeatureConnector.tsx
> +      private connectFeatureToStore!: (entry: IFeatureEntry<any, any, any>) => void;
Давай сюда моковый дефолтный коннектор закинем, чтоб если инжектор поломан было ясно, че поломано где:
```
private connectFeatureToStore!: (entry: IFeatureEntry<any, any, any>) => void = (_: TEntry) => throw new Error('connectFeatureToStore function did not injected or associated. Verify that injector works.')
```

2018-02-09 11:05 UTC, NikitaRzm commented on src/shared/helpers/redux/multiConnect/multiConnect.tsx
> +      private ConnectedComponent!: React.ComponentClass<
Он ведь может быть нулл. Давай будем честными :)

2018-02-09 11:05 UTC, NikitaRzm commented on src/shared/helpers/redux/multiConnect/multiConnect.tsx
> +      private instanceKey!: string;
Ну и тут также, по крайней мере в первый рендер ключ может быть пустым, явно прописать надобно бы.

2018-02-10 06:55 UTC, merged