Webpack updatingб
fullstack-development/react-redux-starter-kit pull request #35
Opened 2018-11-13 06:35 UTC by clicktronix

2018-11-13 09:08 UTC, Znack commented on webpack/common.ts
> +    test: /\.(ts|tsx)$/,
`/\.tsx?$/` — x с вопросом делает его необязательным :)

2018-11-13 09:08 UTC, Znack commented on webpack/common.ts
> +    use: ([] as any[])
зачем к пустому списку конкатим? :)

2018-11-13 09:35 UTC, clicktronix commented on webpack/common.ts
> +    test: /\.(ts|tsx)$/,
поправил

2018-11-13 09:35 UTC, clicktronix commented on webpack/common.ts
> +    use: ([] as any[])
убрал) не знаю как я это закодил :D

2018-11-13 10:08 UTC, NikitaRzm approved these changes

2018-11-13 10:08 UTC, NikitaRzm commented on webpack/common.ts
> +        loader: 'thread-loader',
Проверял? Нормально работает?

P.s. можно прогрев сделать еще  warmup :)

2018-11-13 10:08 UTC, NikitaRzm commented on webpack/common.ts
> +      'cache-loader',
А это кстати довольно дичевый лоадер, он между сборками умеет покэшить и срет жесткий диск - можно послать его нахрен -мало профита с него

2018-11-13 10:34 UTC, in19farkt requested changes

2018-11-13 10:34 UTC, in19farkt commented on webpack/dev.config.ts
> +    } : []),
Чета хурма какая-то. Ты в common создал лоадер, и тут тоже его оставил. Получается у тебя тут два рула для /\.tsx?$/

2018-11-13 10:34 UTC, in19farkt commented on webpack/prod.config.ts
> -  typescriptRule,
зачем выпилил typescriptRule? ты продакшен сборку будешь запускать с кэш-лоадером?

2018-11-13 10:34 UTC, in19farkt commented on webpack/common.ts
> +  },
Очень спорные изменения с тред и кэш лоадерами. На манитокене как-то прикручивал всю эту хурму, вообще быстрее не стало собираться)) это надо как-то тестировать и принимать решение надо ли оно вообще.

2018-11-13 10:35 UTC, in19farkt commented on webpack/prod.config.ts
> -  typescriptRule,
и в es6)

2018-11-13 10:35 UTC, clicktronix commented on webpack/common.ts
> +        loader: 'thread-loader',
сборка ускорилась, все работает, ошибки выплевывает. Не знаю как можно отловить сам поток. Почитаю про warmup

2018-11-13 10:36 UTC, clicktronix commented on webpack/common.ts
> +      'cache-loader',
Жесткий диск гавнякает, да. Посмотрю время сборки без него

2018-11-13 10:38 UTC, clicktronix commented on webpack/dev.config.ts
> +    } : []),
А тут, кстати, для чего бабель юзается? не понял

2018-11-13 10:39 UTC, in19farkt commented on webpack/dev.config.ts
> +    } : []),
для хот релоада реакта

2018-11-13 10:39 UTC, clicktronix commented on webpack/common.ts
> +  },
ну сборка ускорилась секунд на 10 точно

2018-11-13 10:40 UTC, NikitaRzm commented on webpack/common.ts
> +  },
Полагаю, если ядер больше двух - то ускорение более заметно

2018-11-13 10:41 UTC, NikitaRzm commented on webpack/common.ts
> +  },
Но на прошке у меня даже не завелся он на даталайте, мудень

2018-11-13 10:44 UTC, clicktronix commented on webpack/dev.config.ts
> +    } : []),
аа, ну тогда да, два рула для /.tsx?$/, с бабелем тут и общее с разделением тайпчекинга

2018-11-13 10:45 UTC, in19farkt commented on webpack/common.ts
> +  },
ну тада тред лоадер оставляй, кеш убирай, и разберись с лоадерами для тс, хз как оно у тебя работало вообще))

2018-11-13 10:47 UTC, clicktronix commented on webpack/prod.config.ts
> -  typescriptRule,
так то да, зря выпилил, поправлю тут

2018-11-14 04:26 UTC, Znack approved these changes

2018-11-14 13:42 UTC, in19farkt requested changes

2018-11-14 13:42 UTC, in19farkt commented on webpack/dev.config.ts
> +    } : []),
а тут ничего не изменилось, у тебя попрежнему 2 рула для тайпскрипта.

```typescript
const rules: webpack.Rule[] = [
   typescriptRule, // тут первый с бабелем
   ...commonRules, // тут второй с тред лоадером
   ...getStyleRules('dev'),
 ];
```

2018-11-22 11:07 UTC, in19farkt requested changes

2018-11-22 11:07 UTC, in19farkt commented on package.json
> +        "TS_NODE_FILES": true,
что этот параметр делает?

2018-11-22 11:07 UTC, in19farkt commented on package.json
> +    "ts-node": "^7.0.1",
тесты проверял? работают с новым ts-node?

2018-11-22 11:07 UTC, in19farkt commented on package.json
> +    "ts-node": "^7.0.1",
там вроде трабл был с этим какой-то

2018-11-22 11:07 UTC, in19farkt commented on server/starters.ts
> +    process.stdout.write('request');
это зачем?

2018-11-22 11:07 UTC, in19farkt commented on server/starters.ts
> +    process.stdout.write('request');
типа консоль лог забыл убрать? )) или так задумано?

2018-11-22 11:07 UTC, in19farkt commented on tsconfig.json
> +    "module": "commonjs",
с комонжс вроде был какой-то косяк в работе асинхронных импортов. Проверь бандл анализатором, что создаются соответствующие бандлы для асинхронных фич (npm run analyze:dev).

2018-11-22 11:07 UTC, in19farkt commented on tsconfig.json
> +    "allowSyntheticDefaultImports": true,
тесты проверял? там был косяк из-за синтетик импортов. Попробуй затестить компоненту использующую bem-cn и скорее всего поймешь о чем я))

2018-11-22 11:07 UTC, in19farkt commented on webpack/dev.config.ts
> +const devConfig: (type?: BuildType) => webpack.Configuration = (type) => {
переименуй в get или makeDevConfig

2018-11-22 11:07 UTC, in19farkt commented on webpack/dev.config.ts
> +const devConfig: (type?: BuildType) => webpack.Configuration = (type) => {
аналогично для prodConfig

2018-11-22 11:11 UTC, NikitaRzm commented on server/starters.ts
> +    process.stdout.write('request');
Это я забыл, когда заводил там какую то хрень да)

2018-11-23 05:12 UTC, clicktronix commented on package.json
> +        "TS_NODE_FILES": true,
Эт чтобы тайпинги подхватывались глобальные, вот ссыля на это https://github.com/TypeStrong/ts-node#help-my-types-are-missing

2018-11-23 06:04 UTC, clicktronix commented on package.json
> +    "ts-node": "^7.0.1",
да, потестил, ошибку выдавал. Поставил ts-jest, все норм стало

2018-11-23 06:05 UTC, clicktronix commented on tsconfig.json
> +    "allowSyntheticDefaultImports": true,
вроде норм все

2018-11-23 06:07 UTC, clicktronix commented on webpack/dev.config.ts
> +const devConfig: (type?: BuildType) => webpack.Configuration = (type) => {
Поправил

2018-11-23 06:12 UTC, clicktronix commented on tsconfig.json
> +    "module": "commonjs",
Все бандлы фич показывает 
![image](https://user-images.githubusercontent.com/15245608/48930164-45466280-ef21-11e8-87b0-d79068dab811.png)

2018-11-28 06:43 UTC, in19farkt requested changes

2018-11-28 06:43 UTC, in19farkt commented on server/index.ts
> +const starter = NODE_ENV && (starters as any)[NODE_ENV] || startDevelopmentMode;
Давай any уберем

2018-11-28 06:43 UTC, in19farkt commented on server/index.ts
> +const starter = NODE_ENV && (starters as any)[NODE_ENV] || startDevelopmentMode;
из-за этого скорее всего тип starter'a тоже any. можешь starters дать тип Record<string, ...>

2018-11-28 06:43 UTC, in19farkt commented on webpack/common.ts
> +export const commonPlugins: (type: BuildType) => webpack.Plugin[] = (type) => [
переименуй в getCommonPlugins

2018-11-28 06:43 UTC, in19farkt commented on webpack/common.ts
> +  return order.findIndex(item => b.name === item) - order.findIndex(item => a.name === item);
дебажил это? в name точно лежит только имя?

Например если кусок вендоров будет одновременно в двух асинхронных фичах, то должен создасться дополнительный чанк, нейм которого будет выглядеть примерно так `vendor~firstFeature~secondFeature`. Но такой чанк возможно и не нужно сортировать, т.к. он должен подгружаться с одной из этих двух фич.

2018-11-28 06:43 UTC, in19farkt commented on webpack/dev.config.ts
> +    .concat(withHot ? new webpack.HotModuleReplacementPlugin() : []);
можно тоже перенести в commonPlugins, раз уже там проверка нужен ли бабель-лоадер

2018-11-28 06:43 UTC, in19farkt commented on webpack/isomorphic/server.config.ts
>    module: {
это похоже уже можно не переопределять, т.к. всё тоже самое сейчас должно быть в `config.module`

2018-11-28 08:38 UTC, clicktronix commented on webpack/isomorphic/server.config.ts
>    module: {
не, тут же мы прокидываем тип `server` в getStyleRules и getCommonRules

2018-11-28 08:44 UTC, clicktronix commented on webpack/common.ts
> +export const commonPlugins: (type: BuildType) => webpack.Plugin[] = (type) => [
поправил

2018-11-28 08:45 UTC, clicktronix commented on server/index.ts
> +const starter = NODE_ENV && (starters as any)[NODE_ENV] || startDevelopmentMode;
переделал

2018-11-28 08:45 UTC, clicktronix commented on webpack/dev.config.ts
> +    .concat(withHot ? new webpack.HotModuleReplacementPlugin() : []);
перенес

2018-11-28 11:45 UTC, in19farkt commented on webpack/isomorphic/server.config.ts
>    module: {
ну, ты когда вызываешь getProdConfig или getDevConfig, ты уже отдаешь server, а они внутри себя прокидывают это дальше в getStyleRules и getCommonRules. Поэтому получается что ты просто повторяешь уже проделанную работу и смысла в этом нет.

2018-11-28 11:52 UTC, clicktronix commented on webpack/isomorphic/server.config.ts
>    module: {
аа, ну да, замылился уже видимо

2018-11-28 13:31 UTC, in19farkt approved these changes

2018-11-28 14:31 UTC, merged