Added built-route-tree for routes
fullstack-development/react-redux-starter-kit pull request #38
Opened 2018-11-22 09:35 UTC by clicktronix

2018-11-22 13:02 UTC, in19farkt requested changes

2018-11-22 13:02 UTC, in19farkt commented on src/core/routes.tsx
> +          <Redirect exact from={ROUTES_PREFIX} to={homeRoutes.home.getRoutePath()} />
а вот тут ты поломал сборку для gh-pages. нужно апгрейдить build-route-tree, чтобы оно могло принимать раут_префикс

2018-11-22 13:02 UTC, in19farkt commented on src/core/routes.tsx
>      <Route path={ROUTES_PREFIX}>
а тут нужно научить build-route-tree чтобы `homeRoutes.getRoutePath()` вернул строку в формате `/${раут_префикс}`

2018-11-23 06:43 UTC, clicktronix commented on src/core/routes.tsx
> +          <Redirect exact from={ROUTES_PREFIX} to={homeRoutes.home.getRoutePath()} />
а то, что у нас это обернуто в <Route path={ROUTES_PREFIX}> не поможет? я поэтому подумал что должно работать и без префикса тут

2018-11-23 06:46 UTC, clicktronix commented on src/core/routes.tsx
>      <Route path={ROUTES_PREFIX}>
я думал через getRedirectPath прокинуть его туда

2018-11-23 07:16 UTC, in19farkt commented on src/core/routes.tsx
> +          <Redirect exact from={ROUTES_PREFIX} to={homeRoutes.home.getRoutePath()} />
Не поможет, мы же в рауты пишем полный путь

2018-11-23 07:19 UTC, in19farkt commented on src/core/routes.tsx
>      <Route path={ROUTES_PREFIX}>
а при чем тут getRedirectPath? и как ты это себе представляешь?

2018-11-23 07:23 UTC, clicktronix commented on src/core/routes.tsx
>      <Route path={ROUTES_PREFIX}>
Оно бы работало, если бы ROUTES_PREFIX не принимал значения пустой строки ''. Вот так было `routePrefix.homeRoutes.home.getRedirectPath({ routePrefix: ROUTES_PREFIX })`

2018-11-23 07:28 UTC, in19farkt commented on src/core/routes.tsx
>      <Route path={ROUTES_PREFIX}>
не, это похоже на костыль, т.к. ты getRedirectPath используешь не по назначению.

Ну и при таком подходе как ты будешь формировать например такой путь для раута `${route_prefix}/loan/:uuid/repay`? Тут тебе нужен функционал getRedirectPath, чтобы вставить префикс, и одновременно с этим getRoutePath, чтобы вставить в путь `:uuid`

2018-11-26 07:15 UTC, clicktronix commented on src/core/routes.tsx
>      <Route path={ROUTES_PREFIX}>
я чет запутался, у нас getRoutePath не принимает же аргументов, судя по коду. Поэтому здесь все можно через getRedirectPath сделать. Допустим так:  `routePrefix.loan.uuid.repay.getRedirectPath({ routePrefix: ROUTES_PREFIX, uuid: '123' })`

2018-11-26 11:19 UTC, in19farkt commented on src/core/routes.tsx
>      <Route path={ROUTES_PREFIX}>
и запихнуть в Route path строку "/prefix/loan/123/repay"?

2018-11-26 11:19 UTC, in19farkt commented on src/core/routes.tsx
>      <Route path={ROUTES_PREFIX}>
нам туда нужно передать такую строку "/prefix/loan/:uuid/repay"

2018-11-26 11:20 UTC, in19farkt commented on src/core/routes.tsx
>      <Route path={ROUTES_PREFIX}>
как ты это собираешься сделать?

2019-01-08 15:53 UTC, closed without merging