43 add wrappers for mui elems
fullstack-development/react-redux-starter-kit pull request #46
Opened 2018-12-27 06:23 UTC by clicktronix

2019-01-07 04:36 UTC, NikitaRzm commented on src/shared/view/elements/ToggleButton/ToggleButton.style.ts
> +    boxSizing: 'border-box',
На заметку: код стилей читается очень тяжело. Нужно работать над код-стайлом.

2019-01-07 04:40 UTC, NikitaRzm commented on src/shared/view/elements/ToggleButton/ToggleButton.style.ts
> +    '&$selected': {
Соберите, если не сложно - краткий гайд по каскаду в jss, выдержку. Бывает в редких случаях надо быстро сделать каскад - а в итоге роем доки и не понимаем че нам надо.

2019-01-07 07:15 UTC, clicktronix commented on src/shared/view/elements/ToggleButton/ToggleButton.style.ts
> +    '&$selected': {
окей, сделаю

2019-01-07 15:52 UTC, in19farkt requested changes

2019-01-07 15:52 UTC, in19farkt commented on src/shared/styles/theme.ts
> +  governorBay: '##3631B6',
две решетки

2019-01-07 15:52 UTC, in19farkt commented on src/shared/view/elements/FormControlLabel/FormControlLabel.tsx
> +export default FormControlLabel;
в таких компонентах кстати можно сразу экспортнуть MuiFormControlLabel без лишней обертки

2019-01-07 15:52 UTC, in19farkt commented on src/shared/view/elements/MenuItem/MenuItem.tsx
> +export default MenuItem;
тоже давай сразу экспортнем MuiMenuItem

2019-01-07 15:52 UTC, in19farkt commented on src/shared/view/elements/Radio/Radio.tsx
> +export default Radio;
и тут

2019-01-07 15:52 UTC, in19farkt commented on src/shared/view/elements/Typography/Typography.tsx
> +export default Typography;
и тут))

2019-01-07 19:06 UTC, merged

2019-01-08 04:25 UTC, NikitaRzm commented on src/shared/view/elements/FormControlLabel/FormControlLabel.tsx
> +export default FormControlLabel;
Я думаю, необязательно ) так расширять и переписывать проще было бы )

2019-01-08 06:43 UTC, in19farkt commented on src/shared/view/elements/FormControlLabel/FormControlLabel.tsx
> +export default FormControlLabel;
это да, но в таких мелких компонентах зачастую достаточно в теме переопределить стили, там можно указать overides и кастомизировать всё что нужно.