43 set up theme
fullstack-development/react-redux-starter-kit pull request #55
Opened 2019-01-14 11:10 UTC by clicktronix

2019-01-14 12:16 UTC, in19farkt requested changes

2019-01-14 12:16 UTC, in19farkt commented on src/core/App.tsx
> +import { ThemeProvider } from 'services/themeProvider';
предлагаю назвать сервис просто theme

2019-01-14 12:16 UTC, in19farkt commented on src/services/themeProvider/themeFactory/themeFactory.ts
> +import { theme as themeFactory, Theme } from 'shared/styles/theme';
переименуй функцию theme в themeFactory, раз уж теперь это функция.

2019-01-14 12:16 UTC, in19farkt commented on src/services/themeProvider/themeFactory/themeFactory.ts
> +          main: extraTheme.colors.redRibbon,
цвет ошибки наверное тоже нужно брать из extraTheme.palette. В разных темах же может быть немного разный цвет ошибок

2019-01-14 12:16 UTC, in19farkt commented on src/services/themeProvider/view/containers/ThemeProvider/ThemeProvider.tsx
> +      <MuiThemeProvider theme={getTheme(uiTheme)} disableStylesGeneration={disableStylesGeneration}>
Плохо, каждый рендер этой компоненты приводит к созданию новой темы, что приводит к пересборке всех стилей зависящих от темы, а по факту тема то не поменялась

2019-01-14 12:16 UTC, in19farkt commented on src/services/themeProvider/view/containers/ThemeProvider/ThemeProvider.tsx
> +      <MuiThemeProvider theme={getTheme(uiTheme)} disableStylesGeneration={disableStylesGeneration}>
нужно ложить тему в локальный стейт компоненты, слушать изменение uiTheme и обновлять тему

2019-01-14 12:16 UTC, in19farkt commented on src/services/themeProvider/view/containers/ThemeProvider/ThemeProvider.tsx
> +class ThemeProvider extends React.PureComponent<Props> {
нет смысла в PureComponent, если компонента принимает в пропсах JSX в данном случае такой пропс это children

2019-01-14 12:16 UTC, in19farkt commented on src/services/themeProvider/view/containers/ThemeSelector/ThemeSelector.tsx
> +function mapDispatch(dispatch: Dispatch): IActionProps {
сделай так:
```
const mapDispatch: IActionProps = {
  setTheme: actions.setTheme,
}
```

2019-01-14 12:16 UTC, in19farkt commented on src/shared/styles/theme.ts
> +export const darkBlueThemePalette = {
не зафиксирован тип палеты, может привести к тому что палеты разных тем будут иметь разную структуру

2019-01-14 14:45 UTC, in19farkt requested changes

2019-01-14 14:45 UTC, in19farkt commented on src/services/theme/view/containers/ThemeProvider/ThemeProvider.tsx
> +  themes: Record<UITheme, Theme>;
а если у нас будет 1000 тем? будем все их держать в памяти? ))

2019-01-14 14:45 UTC, in19farkt commented on src/services/theme/view/containers/ThemeProvider/ThemeProvider.tsx
> +  themes: Record<UITheme, Theme>;
можно же в стейт положить только текущую тему и в didUpdate смотреть изменение uiTheme и обновлять локальный стейт.

2019-01-14 14:45 UTC, in19farkt commented on src/services/theme/view/containers/ThemeProvider/ThemeProvider.tsx
> +  themes: Record<UITheme, Theme>;
стейт в классе можно будет объявить так:
```
  public state: IState = {
    theme: getTheme(this.props.uiTheme),
  };
```

2019-01-14 14:45 UTC, in19farkt commented on src/shared/styles/theme.ts
> +  },
можно написать проще))
```
palette: themePalettesMap[themeName],
```

2019-01-14 15:03 UTC, clicktronix commented on src/services/theme/view/containers/ThemeProvider/ThemeProvider.tsx
> +  themes: Record<UITheme, Theme>;
я думал будет быстрее переключать темы, но нифига, все равно задержка где то в полл секунды =/

2019-01-15 08:16 UTC, in19farkt approved these changes

2019-01-15 08:16 UTC, merged