wip 60 demo app
fullstack-development/react-redux-starter-kit pull request #70
Opened 2019-02-05 01:49 UTC by chmnkh

2019-02-18 04:07 UTC, Znack approved these changes

2019-02-19 06:48 UTC, NikitaRzm commented on src/features/repositoriesSearch/view/containers/RepositoriesSearchForm/RepositoriesSearchSettings/RepositoriesSearchSettings.tsx
> +  function renderFirstRowSettings() {
Тогда можно и полноценной компонентой сделать: <FirstRowSettings /> <SecondRowSettings />, канонично и можно еще мемоизировать )

2019-02-19 07:10 UTC, NikitaRzm requested changes

2019-02-19 07:10 UTC, NikitaRzm commented on src/features/repositoriesSearch/view/containers/RepositoriesSearchResults/RepositoriesSearchResults.tsx
> +        {this.renderPagination()}
Render-method все-же менее предпочтителен там, где возможен безболезненный переход в функциональным компонентам, this не шумят, отчетливо видна сразу структура представления за счет однородности дсл, код чище )

```
<div className={b()}>
        {repositories.map(this.renderRepositoryPreview)}
        <Pagination total={paginationState.otalPages} page={paginationState.page} />
{displayedRepositoryOwner &&
          <UserDetails username={displayedRepositoryOwner} onClose={this.handleUserDetailsClose} />
        }
      </div>
```

2019-02-19 07:10 UTC, NikitaRzm commented on src/features/repositoriesSearch/view/containers/RepositoriesSearchResults/RepositoriesSearchResults.tsx
> +        {this.renderPagination()}
Или же прямо сюда и вставлять, не вижу смысла убирать оберную в див пагинацию в другой метод, тут рендер не жирный

2019-02-19 07:10 UTC, NikitaRzm commented on src/features/usersSearch/view/containers/UserDetails/UserDetails.tsx
> +          {this.renderMain(userDetails)}
Вот еще почему не стоит злоупотреблять рендер-методами: концов не найти - один рендерметод вызывает другие и сиди ищи, как выглядит структура разметки и где что править надо. Чейнить нельзя так, это как минимум переусложнено. Максимум рендерметод из render-а основного, но вот вкладывать еще и еще - это очень усложняет поддержку.

2019-02-19 07:10 UTC, NikitaRzm commented on src/features/usersSearch/view/containers/UsersSearchForm/UsersSearchSettings/UsersSearchSettings.tsx
> +  function renderFirstRowSettings() {
Почему не функциональные компоненты снова?)

2019-02-19 07:10 UTC, NikitaRzm commented on src/services/api/helpers.ts
> +  if (link !== void 0) {
Условие инвертировать - уйдет вложенности один уровень

2019-02-19 07:10 UTC, NikitaRzm commented on src/services/api/helpers.ts
> +    } else {
else не нужен, выше ранний возврат - тоже на один уровень вложенность уйдет )

2019-02-19 07:10 UTC, NikitaRzm commented on src/shared/view/components/Dialog/Dialog.tsx
> +              {renderActions()}
Тут можно написать более красивый апи, время есть же:
```
<Dialog>
    <Dialog.Content>content here</Dialog.Content>
    <Dialog.Action>action 1</Dialog.Action>
    <Dialog.Action>action 2</Dialog.Action>
</Dialog>
```

Такие штуки на сложные компоненты дают больше гибкости на расширение апи компонента и как слпдствие на кастомизацию структуры) Внутри компонента все нмного усложняется - но оно того стоит )

2019-02-20 02:45 UTC, chmnkh commented on src/features/repositoriesSearch/view/containers/RepositoriesSearchForm/RepositoriesSearchSettings/RepositoriesSearchSettings.tsx
> +  function renderFirstRowSettings() {
А зачем еще дальше разбивать компоненту на 50 строк?
Про мемоизацию не понял о чем ты.

2019-02-20 02:54 UTC, chmnkh commented on src/features/repositoriesSearch/view/containers/RepositoriesSearchResults/RepositoriesSearchResults.tsx
> +        {this.renderPagination()}
про функциональные компоненты согласен

2019-02-20 02:58 UTC, chmnkh commented on src/features/usersSearch/view/containers/UsersSearchForm/UsersSearchSettings/UsersSearchSettings.tsx
> +  function renderFirstRowSettings() {
Тупо в силу привычки по инерции писал классы(
В целом мне казалось что они аккуратнее выглядят чем функциональные компоненты, хотя попробовав последние - мне таки понравилось, но везде на них я тупо забыл переписать

2019-02-20 04:41 UTC, chmnkh commented on src/shared/view/components/Dialog/Dialog.tsx
> +              {renderActions()}
https://github.com/fullstack-development/react-redux-starter-kit/pull/70/commits/329d43376d80144841a98048daf44bba2478c084

2019-02-20 04:42 UTC, chmnkh commented on src/services/api/helpers.ts
> +  if (link !== void 0) {
https://github.com/fullstack-development/react-redux-starter-kit/pull/70/commits/f3d00a95919988655a8a14809f6169becf081cf9

2019-02-20 04:43 UTC, chmnkh commented on src/features/usersSearch/view/containers/UserDetails/UserDetails.tsx
> +          {this.renderMain(userDetails)}
https://github.com/fullstack-development/react-redux-starter-kit/pull/70/commits/b3e21729860d71e9657d3301d98726e1bf2674a8

renderAttribute оставил, имхо маст-хэв

2019-02-20 04:43 UTC, chmnkh commented on src/features/repositoriesSearch/view/containers/RepositoriesSearchResults/RepositoriesSearchResults.tsx
> +        {this.renderPagination()}
https://github.com/fullstack-development/react-redux-starter-kit/pull/70/commits/780c5a225ebc3493bf01a9b99596c2e8e5f16acf

2019-02-20 04:56 UTC, NikitaRzm commented on src/features/usersSearch/view/containers/UserDetails/UserDetails.tsx
> +      onEnter={handleDialogEnter}
Нене, у тебя тут есть обработчики, надо вернуться к классу в этом случае )

2019-02-20 04:56 UTC, NikitaRzm commented on src/features/usersSearch/view/containers/UserDetails/UserDetails.tsx
> +  function renderAttribute(URL: string, title: string, value: number) {
Это тоже функциональногй компонентой: параметры пропсом и один узел в виртуалдоме  + доступные оптимизации.

2019-02-20 07:22 UTC, in19farkt commented on src/features/usersSearch/view/containers/UserDetails/UserDetails.tsx
> +      onEnter={handleDialogEnter}
или обработчики заверни в useCallback

2019-02-20 08:20 UTC, chmnkh commented on src/features/usersSearch/view/containers/UserDetails/UserDetails.tsx
> +      onEnter={handleDialogEnter}
про useCallback думал
имхо - каждый раз о нем помнить и писать его - это чересчур

2019-02-20 09:33 UTC, in19farkt commented on src/features/usersSearch/view/containers/UserDetails/UserDetails.tsx
> +      onEnter={handleDialogEnter}
Ну это почти тоже самое, что помнить про bind, ну и useCallback нужен только если ты отдаешь колбек в PureComponent (memo), в остальных случаях в этом нет смысла.

Конкретно в данном случае Dialog принимает чилдрена, поэтому нет смысла делать его Pure, поэтому можно вообще сразу в пропс отдать стрелочную функцию и это ничего не изменит.

2019-02-20 09:33 UTC, in19farkt commented on src/features/usersSearch/view/containers/UserDetails/UserDetails.tsx
> +      onEnter={handleDialogEnter}
По крайней мере в современных браузерах

2019-02-21 10:55 UTC, NikitaRzm commented on src/features/repositoriesSearch/view/containers/RepositoriesSearchForm/RepositoriesSearchSettings/RepositoriesSearchSettings.tsx
> +  function renderFirstRowSettings() {
Так тыж сам ее разбил )

2019-02-21 11:01 UTC, NikitaRzm commented on src/core/ContainersProvider.tsx
> +      // TODO: УДОЛИ
Кстати забыл: а тут что надо сделать?

2019-02-21 11:06 UTC, NikitaRzm approved these changes

2019-02-21 12:20 UTC, chmnkh commented on src/core/ContainersProvider.tsx
> +      // TODO: УДОЛИ
Короче тут был вариант дефолтный прелоадер передать (та тема с нуллами), чтобы ничего не рендерилось, например, если не передали предоадер вторым аргументом.

А еще Дима предлагал с перегрузкой сделать: если прелоадер не передали, то будет падать не просто контейнер, а опциональный контейнер. Тогда можно будет сразу в компоненте с контейнер провайдером загружающийся контейнер заткнуть чем угодно. Это имхо гибче и лучше 1 варианта.

2019-02-22 05:14 UTC, chmnkh commented on src/features/repositoriesSearch/view/containers/RepositoriesSearchForm/RepositoriesSearchSettings/RepositoriesSearchSettings.tsx
> +  function renderFirstRowSettings() {
Почему разбить основной рендер на рендер функции, чтобы он был не такой жирный = разбить на компоненты?

2019-02-22 06:51 UTC, NikitaRzm commented on src/features/repositoriesSearch/view/containers/RepositoriesSearchForm/RepositoriesSearchSettings/RepositoriesSearchSettings.tsx
> +  function renderFirstRowSettings() {
потому что у тебя в реакт-архитектуре - структурный комопнент - реакт-компонент, а функция != реакт-компонент :)

2019-02-22 06:52 UTC, NikitaRzm commented on src/features/repositoriesSearch/view/containers/RepositoriesSearchForm/RepositoriesSearchSettings/RepositoriesSearchSettings.tsx
> +  function renderFirstRowSettings() {
Точнее реакт-компонент != функция )

2019-02-22 07:14 UTC, in19farkt requested changes

2019-02-22 07:14 UTC, in19farkt commented on src/features/profile/redux/initial.ts
> +import avatar from 'assets/profile_avatar.png';
Давай эту дефолтную аватарку перенесем в фичу, я думаю на уровне всего приложения она нам не нужна

2019-02-22 07:14 UTC, in19farkt commented on src/core/App.tsx
> +        <notificationContainers.Notification />
С большой буквы симпатичнее будет выглядеть :)

2019-02-22 07:14 UTC, in19farkt commented on src/features/profile/view/containers/ProfileEdit/ProfileEdit.tsx
> +function mapDispatch(dispatch: Dispatch): IActionProps {
мапДиспатчи можно так оформлять:
```
type IActionProps = typeof mapDispatch;
const mapDispatch = {
  saveProfile: actions.saveProfile,
  setNotification: notificationServiceActions.setNotification,
}
```

2019-02-22 07:14 UTC, in19farkt commented on src/shared/helpers/form.ts
> +export function makeFormFieldNames<T>(names: Array<keyof T>) {
тут нужно поправить. Проблема в том что в таком виде мы можем не все филды передать в массиве, и получим багу когда будем читать из результата не существующее поле.

Безопасный вариант будет более многословен, но исключает возникновение ошибки по недосмотру. Нам нужно отдавать не массив, а Record<keyof T, null>, ну и тело функции нужно немного поправить. Но если мы используем такую громоздкую конструкцию, то можно вообще отказаться от этого хелпера и просто писать такой объект руками:
```typescript
const names: <[key in keyof IForm]: key> = {
  field: 'field';
  // ...
}
```

Если найдешь более адекватный способ сделать этот хелпер безопасным, то напиши))

2019-02-22 07:14 UTC, in19farkt commented on src/features/profile/view/containers/ProfileEdit/ProfileEdit.tsx
> +        render={this.renderForm}
если ты в this.renderForm используешь только handleSubmit, то нужно обнулить подписку на все изменения формы, чтобы не происходило лишних перерисовок всего контента формы на каждое изменение стейта формы:
```typescript
      <Form
        onSubmit={this.handleFormSubmit}
        initialValues={profile}
        render={this.renderForm}
        subscriptions={{}} // <-- уоттакуот
      />
```

2019-02-22 07:14 UTC, in19farkt commented on src/features/profile/view/containers/ProfileEdit/ProfileEdit.tsx
> +        render={this.renderForm}
И давай еще добавим какую-нибудь элементарную валидацию, например, на максимальное кол-во символов и реквайред

2019-02-22 07:14 UTC, in19farkt commented on src/features/profile/view/containers/ProfilePreview/ProfilePreview.scss
> +/* doiuse-disable word-break */
а это что и зачем? по другому решить нельзя?

2019-02-22 07:14 UTC, in19farkt commented on src/shared/styles/variables.scss
> +$change-view-breakpoint: 590px;
как назовешь следующий брейкпоинт?

Вообще нормальная практика разбивать на несколько брейкпоинтов и именовать их так:
```
... | xxs | xs | sm | md | lg | xl | xxl | ...
```
В качестве отправной точки можешь взять следующие значения:
```
xs: 320
sm: 600
md: 960
lg: 1280
xl: 1920
```

2019-02-22 07:14 UTC, in19farkt commented on src/features/profile/view/containers/ProfilePreview/ProfilePreview.scss
> +    @media (max-width: $change-view-breakpoint) {
Не соблюдается принцип mobile first. Раз уж мы начали делать какой-то адаптив, то я думаю нужно делать его по уму. И давай напишем для этого миксин, синтаксис должен быть примерно такой:
```scss
.block {
  width: 100%;

  @include breakpoint-up(sm) {
    width: 10rem;
  }

  @include breakpoint-up(md) {
    width: 14rem;
  }
}
```

[Дока по миксинам](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#mixins)

2019-02-22 07:14 UTC, in19farkt commented on src/features/profile/view/containers/ProfilePreview/ProfilePreview.scss
> +    transition-property: display;
разве транзишн работает с дисплеем? 0_0

2019-02-22 07:14 UTC, in19farkt commented on src/features/profile/view/containers/ProfilePreview/ProfilePreview.tsx
> +  }
Тут чтобы не городить этот огород с клик хендлерами, можно воспользоваться [Popover из mui](https://material-ui.com/utils/popover/). Он еще и с анимацией аккуратной будет))

2019-02-22 07:14 UTC, in19farkt commented on src/features/repositoriesSearch/view/components/RepositoryPreview/RepositoryPreview.scss
> +    background: url('./img/star.png') no-repeat;
Давай найдем svg и сделаем нормальную иконку в shared/view/elements/Icons. Каждая иконка - это отдельный файл. [Тут можешь найти как оформить компоненту иконки](https://material-ui.com/style/icons/#svg).

Если в svg коде будет где-то указан color, то можно заменить конкретное значение на `current-color`, так мы можем красить иконку с помощью `color` родителя

2019-02-22 07:43 UTC, chmnkh commented on src/features/repositoriesSearch/view/containers/RepositoriesSearchForm/RepositoriesSearchSettings/RepositoriesSearchSettings.tsx
> +  function renderFirstRowSettings() {
блин, это понятно, когда есть какой-то самостоятельный элемент, но здесь, в этих функциях, 2 части одного целого по сути находятся. У того, что они рендерят, даже стили общие. Почему я не могу вместо одной функции написать две тупо чтобы лучше читалось без того, чтобы это было "структурным компонентом"?

2019-02-22 07:50 UTC, chmnkh commented on src/features/profile/view/containers/ProfilePreview/ProfilePreview.scss
> +/* doiuse-disable word-break */
цимес в том, что мне нужен `word-break: break-all`
некоторые браузеры имеют partial поддержку ворд брейка, причем она заключается в том, что [эти браузеры поддерживают](https://caniuse.com/#feat=word-break) `word-break: break all`, но `word-break: keep-all` не поддерживают. Т.е. то значения свойства, что нужно мне, поддерживается, но doiuse меня тем не менее посылает.

2019-02-22 07:51 UTC, NikitaRzm commented on src/shared/styles/variables.scss
> +$change-view-breakpoint: 590px;
лучше в отдельный мерж тогда - тут много всего уже )

2019-02-22 07:51 UTC, NikitaRzm commented on src/features/profile/view/containers/ProfilePreview/ProfilePreview.scss
> +    @media (max-width: $change-view-breakpoint) {
Весь мобайлферст в  смысле в отдельный мр)

2019-02-22 08:23 UTC, in19farkt commented on src/features/profile/view/containers/ProfilePreview/ProfilePreview.scss
> +/* doiuse-disable word-break */
для этого есть игнор лист в конфиге и в стайллинтрц, чтобы в стилях это не дисейблить

2019-02-22 08:47 UTC, NikitaRzm commented on src/features/repositoriesSearch/view/containers/RepositoriesSearchForm/RepositoriesSearchSettings/RepositoriesSearchSettings.tsx
> +  function renderFirstRowSettings() {
на мой взгляд, ты либо делишь на структурные юниты либо не делишь: и если делишь - то делаешь это единообразно - т.е. выделяя другие компоненты. Это понятно, формализованно, и react-way. А тут - просто функция, возвращающая верстку непонятно зачем вынесена в соседнюю функцию. От чего она абстрагирует тебя? Что скрывает внутри? Где-то или как-то переиспользууется? Тут уж даже тогда под вопросом сам факт деления тогда встает. Я не сторонник таких вещей, деление должно быть понятно, обоснованно, и структурный юнит должен удовлетворять спеке, требованиям контракта. У реакта контракт - это ComponentType для структурных юнитов. Ровно потому-же я не особо приемлю какое-то сумбурное деление на рендерметоды )

Иными словами: бардак начинается :)

2019-02-22 09:47 UTC, chmnkh commented on src/features/profile/view/containers/ProfilePreview/ProfilePreview.scss
> +    transition-property: display;
нет, я упрлс

2019-02-22 09:49 UTC, chmnkh commented on src/features/profile/view/containers/ProfilePreview/ProfilePreview.scss
> +/* doiuse-disable word-break */
глобально опаснее это делать, вдруг кто-то захочет `keep-all` написать и не увидит, что он не поддерживается

2019-02-22 09:50 UTC, in19farkt commented on src/features/profile/view/containers/ProfilePreview/ProfilePreview.scss
> +/* doiuse-disable word-break */
да, действительно)

2019-02-22 10:22 UTC, chmnkh commented on src/shared/helpers/form.ts
> +export function makeFormFieldNames<T>(names: Array<keyof T>) {
Мы на тио подобный хэлпер юзали (тот что сейчас написан), да, есть такая проблема. Тут скорее компромисс, более опасно, но зато и более удобно, чем объект городить. 
Наверное в нашем случае лучше выпилить хэлпер и руками писать объект, да.

2019-02-25 05:17 UTC, in19farkt commented on src/features/repositoriesSearch/view/components/RepositoryPreview/RepositoryPreview.tsx
> +  private renderAttribute(title: string, value: string | number) {
Я бы сделал функциональную компоненту, возможно прямо в этом же файле, чтобы лишние блоки не городить, и дал бы ему, помимо пропсов `title` и `value`, 2 опциональных пропса - `type?: 'owner'` и `onValueClick`.

2019-02-25 05:20 UTC, in19farkt commented on src/features/profile/view/containers/ProfilePreview/ProfilePreview.scss
> +    @media (max-width: $change-view-breakpoint) {
Создал ишу https://github.com/fullstack-development/react-redux-starter-kit/issues/78

2019-02-25 06:08 UTC, chmnkh commented on src/features/repositoriesSearch/view/components/RepositoryPreview/RepositoryPreview.tsx
> +  private renderAttribute(title: string, value: string | number) {
о, забыл про это, уже в другом месте было подобное ишью, поправлю

2019-02-25 07:31 UTC, chmnkh commented on src/features/repositoriesSearch/view/components/RepositoryPreview/RepositoryPreview.tsx
> +  private renderAttribute(title: string, value: string | number) {
Хотя я бы не делал в одном файле >1 компоненты, неочевидно.

2019-02-25 10:11 UTC, in19farkt commented on src/features/repositoriesSearch/helpers.ts
> +export function injectSizeToAvatarURL(URL: string, sizeInPixels: number) {
неиспользуемая функция, видимо копипасту забыл удалить

2019-02-27 11:51 UTC, in19farkt approved these changes

2019-02-27 12:09 UTC, merged