63 react 18next configure
fullstack-development/react-redux-starter-kit pull request #71
Opened 2019-02-05 07:12 UTC by clicktronix

#63

2019-02-08 06:38 UTC, in19farkt commented on src/core/configureApp.ts
> +import './configurationI18n';
what for?

2019-02-08 06:38 UTC, in19farkt commented on src/modules/Demo/view/DemoTranslations/DemoTranslations.tsx
> +import { withI18n, tKeys, ITranslateProps } from 'core/configurationI18n';
странно что мы импортим это из файла с названием configuration)

2019-02-08 06:38 UTC, in19farkt commented on src/core/configurationI18n.ts
> +  en: {
а с помощью асинхронных импортов мы можем собрать переводы? Может там есть какие-то решения для этого. А то мы увеличили размер gzipped бандла примерно на 15kB, а профита я пока не вижу.

Еще вроде с помощью этой штуки можно вынести переводы в отдельную админку, причем ключи автоматом там появляются в процессе разработки. Есть платный сервис для этого. Мы сможем использовать такую возможность бесплатно? Что для этого нужно сделать?

2019-02-08 06:38 UTC, in19farkt commented on src/core/configureApp.ts
> +import './configurationI18n';
Первый раз где-нибудь заберешь withI18n и всё инициализируется)

2019-02-08 15:38 UTC, clicktronix commented on src/core/configureApp.ts
> +import './configurationI18n';
Чото да, видимо копипаста.

2019-02-08 15:39 UTC, clicktronix commented on src/modules/Demo/view/DemoTranslations/DemoTranslations.tsx
> +import { withI18n, tKeys, ITranslateProps } from 'core/configurationI18n';
Я просто думаю куда это можно так положить, чтобы выпилить максимально без болезненно

2019-02-08 15:41 UTC, clicktronix commented on src/core/configurationI18n.ts
> +  en: {
Там вообще много как можно эти переводы ворочать, можно сами переводы разбить на чанки, можно грузить с сервера или с locize.com, можно просто с приложением грузить все. Можно попробовать на locize.com залить наши переводы

2019-02-09 06:25 UTC, clicktronix commented on src/modules/Demo/view/DemoTranslations/DemoTranslations.tsx
> +import { withI18n, tKeys, ITranslateProps } from 'core/configurationI18n';
Хотя если подрубать подгрузку переводов все равно придется его создавать, перенесу в сервисы.

2019-03-21 13:13 UTC, in19farkt commented
@clicktronix а что с ПРом? Он у тебя в статусе WIP.

2019-03-23 06:58 UTC, clicktronix commented
@in19farkt забыл про него уже, мы подрубаем переводы из locize.io? Там вроде какое то количество ключей бесплатно, плюс надо подумать как типизировать это дело. Можно оставить англ переводы в проекте, на фоллбэк и как раз для типов

2019-03-31 20:40 UTC, clicktronix commented
Переписал ПР для мержа в мастер. Тесты пока поломаны из-за добавления пропсов перевода, не стал здесь исправлять, чтоб ПР не захламлять, поправлю тесты в отдельной ветке, заодно напилю новых для i18n. @in19farkt @chmnkh @NikitaRzm @Znack посмотри по возможности пр плз

2019-04-01 08:51 UTC, Znack commented
а как без тестов работающих мержить в мастер? :) Это странные приоритеты, не добавлять тесты, чтобы не захламлять, лучше тогда разбить функциональность на два ПР, но каждый с норм тестами :)

2019-04-01 17:40 UTC, clicktronix commented
Тесты поправил, новые на локализацю в другом пр сделаю

2019-04-03 05:04 UTC, Znack commented
@chmnkh не смотрел ПР ещё?

2019-04-03 05:35 UTC, in19farkt requested changes

2019-04-03 05:35 UTC, in19farkt commented on src/features/repositoriesSearch/view/containers/RepositoriesSearchForm/RepositoriesSearchForm.tsx
> +export default withTranslation()(connectedComponent);
мне такая запись больше нравится:
```
export default (
  connect(mapState, mapDispatch)(
    withTranslation()(connectedComponent),
  )
);
```

2019-04-03 05:35 UTC, in19farkt commented on src/features/usersSearch/view/containers/UserDetails/__tests__/index.test.ts
> +  ...getMockedLocaleProps(),
зачем это делать функцией?

2019-04-03 05:35 UTC, in19farkt commented on src/modules/shared/Layout/Layout.tsx
> +    const menuItems: IHeaderMenuItem[] = [
желательно бы такое замемоизировать

2019-04-03 05:35 UTC, in19farkt commented on src/shared/view/components/SearchForm/SearchForm.tsx
> +import { TranslateFunction, tKeys } from 'services/i18n';
а вот в шередах дергать сервисы - по-моему это дичь

2019-04-03 05:35 UTC, in19farkt commented on src/shared/view/components/SearchForm/SearchForm.tsx
> +import { TranslateFunction, tKeys } from 'services/i18n';
нужно подумать как такие ситуации разруливать на прямую не завязываясь на сервис.

2019-04-03 05:38 UTC, in19farkt commented on src/features/usersSearch/view/containers/UserDetails/__tests__/index.test.ts
> +  ...getMockedLocaleProps(),
хотя норм, на каждый вызов новые пропсы

2019-04-03 05:42 UTC, NikitaRzm commented on src/features/repositoriesSearch/view/containers/RepositoriesSearchForm/RepositoriesSearchForm.tsx
> +export default withTranslation()(connectedComponent);
Лучше разыменовывать каждое применение хока - часто ыбвает полезно увидеть инферинг типа ) ну и можно гранулярный экспорт сделать при надобности. Экспортировать отдельно законнеченный, переведенный и чистый компоненты

2019-04-03 05:43 UTC, NikitaRzm commented on src/shared/view/components/SearchForm/SearchForm.tsx
> +import { TranslateFunction, tKeys } from 'services/i18n';
Такие вещи развязываются через генерики или в рантайме. Закон такой: если не можешь развязать в компайлтайме - развязывать в рантайме)

2019-04-03 05:49 UTC, in19farkt commented on src/features/repositoriesSearch/view/containers/RepositoriesSearchForm/RepositoriesSearchForm.tsx
> +export default withTranslation()(connectedComponent);
В том виде что я предлагаю, это тупо читается и воспринимается намного легче, ты последовательно видишь применения хоков и когда их больше 3 это реально помогает понять че вообще происходит. Именованные применения хоков (вариант который продемонстрировал Влад) по мне только нагружают код и делают его не читабельным.

> ну и можно гранулярный экспорт сделать при надобности

мне оно ни разу не пригодилось за 2 с лишним года работы)) Ради какого-то единичного случая можно и поименовать, но делать это всегда ради фантомной надобности гранулярного экспорта - мне кажется странным.

2019-04-03 05:51 UTC, NikitaRzm commented on src/features/repositoriesSearch/view/containers/RepositoriesSearchForm/RepositoriesSearchForm.tsx
> +export default withTranslation()(connectedComponent);
Не ради единичного случая, а ради возможности дебажить типы. А этим ребята занимаются постоянно, и периодически перекидываем как раз из такой записи в гранулярную и обратно. Это очень полезно в разработке - а читается как-раз гораздо легче, нежели каша из вложенных вызовов хоков.

Ужас наяву:

![image](https://user-images.githubusercontent.com/16317879/55455791-34b0a200-560f-11e9-84bc-e7f64cf86506.png)

2019-04-03 05:55 UTC, in19farkt commented on src/features/repositoriesSearch/view/containers/RepositoriesSearchForm/RepositoriesSearchForm.tsx
> +export default withTranslation()(connectedComponent);
ну хз) видимо дело привычки) Я наоборот именованные не воспринимаю, отвлекают как раз таки промежуточные константы.

2019-04-03 05:58 UTC, in19farkt commented on src/features/repositoriesSearch/view/containers/RepositoriesSearchForm/RepositoriesSearchForm.tsx
> +export default withTranslation()(connectedComponent);
Про дебаг типов соглашусь, но в моей практике это тоже единичные случаи, хотя хоки писать я люблю и тоже активно использую.

2019-04-03 06:00 UTC, NikitaRzm commented on src/features/repositoriesSearch/view/containers/RepositoriesSearchForm/RepositoriesSearchForm.tsx
> +export default withTranslation()(connectedComponent);
Я не знаю, конечно, какая тут привычка нужна - но вот в этой каше работать сложнее. 🙈

2019-04-03 06:08 UTC, in19farkt commented on src/features/repositoriesSearch/view/containers/RepositoriesSearchForm/RepositoriesSearchForm.tsx
> +export default withTranslation()(connectedComponent);
Искренне не понимаю где тут каша)) я код со скрина выше прочитал на раз, ни чего лишнего, всё только по делу, именно то что нужно когда хочу понять чем усилена компонента))

а если бы у нас был нормально типизированный compose, чтобы эти хоки выстроить в ряд на одном уровне, получить итоговый хок, применить его к компоненте и не просрать типы, то для меня было бы вообще идеально)

2019-04-05 07:04 UTC, clicktronix commented on src/features/repositoriesSearch/view/containers/RepositoriesSearchForm/RepositoriesSearchForm.tsx
> +export default withTranslation()(connectedComponent);
Мне такие вложения тоже не удобно читать. Взять те же три хока, плюс фича коннектор туда приписюнить и уже страшная конструкция выходит. А с компоузом не спорю, было б красиво:) Можем на обсуждение в диалоге вынести

2019-04-05 07:47 UTC, clicktronix commented on src/shared/view/components/SearchForm/SearchForm.tsx
> +import { TranslateFunction, tKeys } from 'services/i18n';
@NikitaRzm можешь подробнее расписать, этот момент?)

2019-04-05 08:15 UTC, NikitaRzm commented on src/shared/view/components/SearchForm/SearchForm.tsx
> +import { TranslateFunction, tKeys } from 'services/i18n';
Во первых - что такое SearchForm? Если сюда нуэно пробросить тексты, принимай их в пропсах, делегируй выставление текстов верхним уровням, они переведут тексты и уже их сюда прокинут. titleText, descriptionText. Не нужны тебе тут сервисы. Это развязка в рантайме.

2019-04-05 08:19 UTC, clicktronix commented on src/shared/view/components/SearchForm/SearchForm.tsx
> +import { TranslateFunction, tKeys } from 'services/i18n';
Понял)

2019-04-05 11:39 UTC, chmnkh requested changes

2019-04-05 11:39 UTC, chmnkh commented on package.json
> -    "stylelint": "^9.6.0",
![image](https://user-images.githubusercontent.com/18498637/55624129-2dd08d80-57cf-11e9-9a73-25504c2c5e28.png)
я так понял он в локал сторадже язык хранит?
если его почистить или зайти первый раз - вот такая вот дичь: язык русский, хотя выбран английский

2019-04-05 11:39 UTC, chmnkh commented on package.json
> +    "stylelint": "^9.10.1",
![image](https://user-images.githubusercontent.com/18498637/55624200-653f3a00-57cf-11e9-81e1-db19c0abb17d.png)

селект так себе чот

2019-04-05 11:39 UTC, chmnkh commented on package.json
>      "@types/classnames": "^2.2.6",
![image](https://user-images.githubusercontent.com/18498637/55624259-9455ab80-57cf-11e9-9ff5-f336fe3403c8.png)

2019-04-05 11:39 UTC, chmnkh commented on package.json
>      "@types/compression": "0.0.36",
![image](https://user-images.githubusercontent.com/18498637/55624414-fa423300-57cf-11e9-9e3f-c1106929141e.png)

Мб здесь лучше написать
> Искать
Пользователей
Организации
Пользователей и организации

2019-04-05 11:39 UTC, chmnkh commented on package.json
>      "@types/cookie-parser": "^1.4.1",
![image](https://user-images.githubusercontent.com/18498637/55624516-67ee5f00-57d0-11e9-83eb-f41576d04088.png)
значения тоже перевести надо по-хорошему наверное)

2019-04-05 11:39 UTC, chmnkh commented on package.json
>      "@types/node-polyglot": "^0.4.31",
![image](https://user-images.githubusercontent.com/18498637/55624606-b0a61800-57d0-11e9-981d-ff67c8e0a74f.png)
мне кажется можно "мин." "макс." написать, лаконичнее было бы

2019-04-05 11:39 UTC, chmnkh commented on package.json
>      "@types/ramda": "^0.25.29",
![image](https://user-images.githubusercontent.com/18498637/55624650-d0d5d700-57d0-11e9-93e0-4b7d9d29cad1.png)
репозитори**ев**

2019-04-05 11:39 UTC, chmnkh commented on package.json
>      "@types/node-polyglot": "^0.4.31",
и "количество" на "число" бы заменил, имхо проще воспринимается

2019-04-05 11:39 UTC, chmnkh commented on package.json
>      "file-loader": "^2.0.0",
![image](https://user-images.githubusercontent.com/18498637/55624989-b2241000-57d1-11e9-9ed5-e37a9717c035.png)
тут идея в том была, чтобы читалось как предложение:
> Искать: Пользователей | Репозитории

2019-04-05 11:39 UTC, chmnkh commented on package.json
>      "inversify": "^5.0.1",
![image](https://user-images.githubusercontent.com/18498637/55625067-e0095480-57d1-11e9-807c-1e12952f3e81.png)
тут тоже мин. и макс. написал бы (см. дискашн выше)
\+ у тебя тут мин 2 раза))

2019-04-05 11:39 UTC, chmnkh commented on package.json
>      "inversify-inject-decorators": "^3.1.0",
![image](https://user-images.githubusercontent.com/18498637/55625100-f8796f00-57d1-11e9-82c6-e03321740efa.png)
там же Owner - Владелец)

2019-04-05 11:39 UTC, chmnkh commented on package.json
>      "jss": "^9.8.3",
![image](https://user-images.githubusercontent.com/18498637/55625141-1c3cb500-57d2-11e9-8716-989a70c2f7ae.png)
тут забыл перевести

2019-04-05 11:40 UTC, chmnkh commented on package.json
>      "@types/classnames": "^2.2.6",
тут можно как минимум сократить лейбл до "результатов на страницу", ну и мб еще что-то подумать

2019-04-05 20:25 UTC, clicktronix commented on package.json
>      "inversify": "^5.0.1",
с минимальным вроде ровно, там звезды, там форки. Остальное поправил)

2019-04-05 20:28 UTC, clicktronix commented on package.json
> -    "stylelint": "^9.6.0",
Он подхватывает язык браузера и запихивает в начальное значение. Косяк был в другом, он почему то строку другую ждал. Нижнее тоже должно решится с пустым селектом, у меня не получилось повторить

2019-04-08 03:12 UTC, chmnkh commented on package.json
> +    "stylelint": "^9.10.1",
я имел в виду почему он не стилизован никак? на скрине то, как у меня на убунте в хроме этот селект выглядит: там текст белый, блин)

на фаерфоксе какой-то виндовс-98-стайл селект тоже
![image](https://user-images.githubusercontent.com/18498637/55696351-b9703700-59e6-11e9-9513-cea9f7a762e9.png)
почему муи селект не сделать, например, чтобы он не выпадал из общей картины?

2019-04-08 04:03 UTC, chmnkh requested changes

2019-04-08 04:03 UTC, chmnkh commented on src/features/usersSearch/view/containers/UsersSearchForm/UsersSearchForm.tsx
> +        getFilters={this.makeFiltersGetter(filtersValuesFormattersMap)}
![image](https://user-images.githubusercontent.com/18498637/55696618-0b658c80-59e8-11e9-92d5-9010260924d9.png)
Тут не должно быть просто `min` и `max`, а должно быть `Min repositories` и `Max repositories`.
Ну и на русском та же фигня.

2019-04-08 04:03 UTC, chmnkh commented on src/features/usersSearch/view/containers/UsersSearchForm/UsersSearchSettings/UsersSearchSettings.tsx
> +              <RadioField name={fieldNames.searchFor} value="user" label={t(userSearch.user.getKey())} />
в лэйбле тут должно быть User**s**

2019-04-08 04:03 UTC, chmnkh commented on src/shared/view/elements/TotalSearchResults/TotalSearchResults.tsx
> +        {title}
пробел после двоеточия верните как-то, пожалуйста))

2019-04-08 04:03 UTC, chmnkh commented on src/services/i18n/locales/ru.ts
> +      email: 'Почта',
![image](https://user-images.githubusercontent.com/18498637/55697249-c2fb9e00-59ea-11e9-8881-48000a8fdedb.png)
Почт**е**?
Полн**ому** **имени**?

2019-04-08 04:03 UTC, chmnkh commented on src/services/i18n/locales/ru.ts
> +      minStars: 'мин. звезд',
![image](https://user-images.githubusercontent.com/18498637/55697286-ee7e8880-59ea-11e9-9cbb-16db433b80bf.png)
с большой буквы лэйблы плиз

плюс здесь:
![image](https://user-images.githubusercontent.com/18498637/55697376-677de000-59eb-11e9-8a2a-33fef6388f56.png)

должно быть по идее тоже мин и макс так же написано, а не намбер, это мой косяк видимо, исправь тоже плиз если не сложно)

2019-04-08 04:03 UTC, chmnkh commented on src/features/usersSearch/view/containers/UsersSearchForm/UsersSearchForm.tsx
> +    const getMemoOptions: () => OptionType = R.memoizeWith<() => OptionType>(R.identity, () => [
а что здесь мемоизируется? у мемоизируемой функции аргументов же нету даже

2019-04-08 04:07 UTC, chmnkh requested changes

2019-04-08 04:07 UTC, chmnkh commented on src/services/i18n/locales/ru.ts
> +      usersSearch: 'Поиск пользователя GitHub',
Пользовател**ей** и репозитори**ев**

2019-04-08 04:44 UTC, chmnkh commented on src/features/usersSearch/view/containers/UsersSearchForm/UsersSearchForm.tsx
> +    const getMemoOptions: () => OptionType = R.memoizeWith<() => OptionType>(R.identity, () => [
Сейчас вообще коряво сделано в том плане, что список опшнов и лейблов для сеттингов в двух местах задаются. `getMemoOptions` - тупо копипаста здесь и в сеттинг форме. Зачем накладывать на себя обязательство эту херню и там и там синхронизировать? Лейблы для инпутов тоже в общем случае из одного источника исходить должны, с небольшими расширениями. [Здесь](https://github.com/fullstack-development/react-redux-starter-kit/pull/101#discussion_r272532044) я это подробно описывал. Есть вариант это пробрасывать пропсами в Сеттингс компонент, например.

2019-04-08 13:16 UTC, clicktronix commented on src/features/usersSearch/view/containers/UsersSearchForm/UsersSearchForm.tsx
> +        getFilters={this.makeFiltersGetter(filtersValuesFormattersMap)}
тут не влезает нормально лейбл, сокращенные сделал

2019-04-09 03:21 UTC, chmnkh commented on src/services/i18n/locales/en.ts
> +      min: 'Min repos',
![image](https://user-images.githubusercontent.com/18498637/55771152-091b3500-5ab1-11e9-9a2b-71fb8e67a7d3.png)
![image](https://user-images.githubusercontent.com/18498637/55771162-10424300-5ab1-11e9-8a2f-66268f9f37cc.png)

а вот теперь прикол в том, что в форме должно быть просто Min и Max, потому что там общий лейбл Repositories number и слово repos повторять это избыточно, а в фильтрах должно показываться что это репы, потому что иначе не понятно что это такое вообще.

2019-04-09 04:56 UTC, chmnkh commented on src/features/usersSearch/view/containers/UsersSearchForm/UsersSearchForm.tsx
> +    const getMemoOptions = R.memoizeWith(R.identity, (x: OptionType[]) => x);
а зачем это мемоизировать?

2019-04-09 04:59 UTC, chmnkh commented on src/features/usersSearch/view/containers/UsersSearchForm/UsersSearchForm.tsx
> +    const getMemoOptions = R.memoizeWith(R.identity, (x: OptionType[]) => x);
какой профит от мемоизации такой функции
```
function(x) {
  return x;
}
```

2019-04-09 05:18 UTC, chmnkh commented on src/services/i18n/view/LanguageSelector/LanguageSelector.scss
> +  & div {
зачем так жестко, можно же сделать так:
```
<Select
  ...
  InputProps={{ classes: { input: b('rofl') } }}
  SelectProps={{ classes: { icon: b('nice rofl') } }}
/>
```

2019-04-09 05:46 UTC, chmnkh commented on src/features/repositoriesSearch/view/containers/RepositoriesSearchForm/RepositoriesSearchForm.tsx
> +        errorFormText={t(tKeys.shared.fieldIsRequiredError.getKey())}
такое апи как минимум нерасширяемое вообще же, у нас щас количество таких пропсов = количеству валидаторов, мне кажется логичнее тогда уж вообще валидатор извне прокидывать, чтобы не было такой проблемы

2019-04-09 07:02 UTC, clicktronix commented on src/features/usersSearch/view/containers/UsersSearchForm/UsersSearchForm.tsx
> +    const getMemoOptions = R.memoizeWith(R.identity, (x: OptionType[]) => x);
Да чет стукнуло все замемоизировать. Вообще в react-i18n советовали мемоизировать ткие штуки, я думал как пример больше это сделать

2019-04-09 07:23 UTC, NikitaRzm commented on src/services/i18n/view/LanguageSelector/LanguageSelector.scss
> +  & div {
Селекторы по тэгам в целом мы запрещаем :)

2019-04-09 07:58 UTC, in19farkt requested changes

2019-04-09 07:58 UTC, in19farkt commented on src/core/configureApp.ts
> +import 'services/i18n/i18nContainer';
Зачем здесь этот пустой импорт?

2019-04-09 07:58 UTC, in19farkt commented on src/core/configureApp.ts
> +import 'services/i18n/i18nContainer';
Если там происходит какая-то инициализация чего-либо, то лучше это всё завернуть в функцию и явно тут вызвать, иначе не понятно че это за импорт и нахера он тут нужен.

2019-04-09 07:58 UTC, in19farkt commented on src/services/i18n/i18nContainer.ts
> +i18n
а мы можем тут новый чистый экземпляр i18n создать? А то получается что сейчас мы пользуемся глобальной переменной, которую можно заимпортить из любого места и чего-нибудь в ней натворить, я думаю лучше избегать такого :)

Если есть возможность создать новый экземпляр i18n, то нужно создать его здесь и инициализировать, а импорт из `i18next` запретить на уровне тслинта, на всякий случай, чтобы не импортили `i18n` из библиотеки, а забирали инстанс отсюда. Или если это будет завернуто в функцию, то пусть она возвращает проинициализированный инстанс `i18n`, а мы уже его отдадим в deps или забиндим в IOC контейнер, если понадобится.

2019-04-09 07:58 UTC, in19farkt commented on src/features/profile/view/containers/ProfileEdit/ProfileEdit.tsx
> +  private makeValidateName() {
тут есть одна проблемка, ошибка валидации будет переводиться во время самой валидации, и сформированный перевод будет попадать в стейт формы. Если мы, увидев ошибку валидации, переключим язык, то ошибка валидации не переведется, а это мне кажется не очень.

Мы это решали расширением функции translate следующим образом:
1. валидатор возвращает объект:
```
{
  key: 'some.translate.key',
  params: {
    // ...
  }
}
```
2. функция translate видит что первым аргументом прилетел объект с полями `key` и `params`, и вызвала оригинальную функцию `translate(key, params)`

Поэтому нужно поглядеть доки `i18next` и найти каким образом мы можем расширить функцию `translate`. Еще раз уж мы будем модифицировать функцию `translate`, я бы добавил возможность передавать ключ без вызова `getKey()`, чтобы она могла обрабатывать такое:
```
t(tKeys.shared.save)
```

2019-04-09 07:58 UTC, in19farkt commented on src/features/profile/view/containers/ProfileEdit/ProfileEdit.tsx
> +  private makeValidateName() {
Такой подход избавит нас от таких монструозных конструкций на валидацию. Мы как обычно будем передавать в филд массив валидаторов, а они будут возвращать ключ или объект для перевода.

2019-04-09 07:58 UTC, in19farkt commented on src/features/repositoriesSearch/view/components/RepositoryPreview/RepositoryPreview.tsx
> +const { repositoriesSearch } = tKeys.features;
предлагаю такие штуки переименовывать как-то одинаково во всех файлах, чтобы во всех рендерах однообразно было.

2019-04-09 07:58 UTC, in19farkt commented on src/shared/view/components/SearchForm/SearchForm.tsx
> +          validate={makeRequired(errorFormText)}
таже проблема с валидатором что я описал выше.

2019-04-09 07:58 UTC, in19farkt commented on src/features/profile/view/containers/ProfileEdit/ProfileEdit.tsx
> +  private makeValidateName() {
Ну и получается что переводить ошибки нужно непосредственно перед отрисовкой.

2019-04-09 10:07 UTC, clicktronix commented on src/services/i18n/i18nContainer.ts
> +i18n
Я вот думаю, может быть такой кейс, что нам понадобится два инстанса i18n? Просто если нет, то может в синглтон это все завернуть тогда? Добавить статичный метод для инициализации

2019-04-09 10:12 UTC, clicktronix commented on src/features/profile/view/containers/ProfileEdit/ProfileEdit.tsx
> +  private makeValidateName() {
Так то да, есть такая беда. Не до конца понял ваш подход, в телеге напишу))

2019-04-09 10:16 UTC, clicktronix commented on src/features/repositoriesSearch/view/components/RepositoryPreview/RepositoryPreview.tsx
> +const { repositoriesSearch } = tKeys.features;
какие именно? вот эти переводы `repositoriesSearch`? Бывает же что и из `tKeys.shared` берем переводы.

Или ты имеешь в виду например `repositoriesSearch` разыменовывать как то одинаково? чтобы везде было что то типо `translations.button.getKey()`?

2019-04-09 10:18 UTC, clicktronix commented on src/services/i18n/locales/en.ts
> +      min: 'Min repos',
Думаю нормально, что будет два лейбла, один будет для описания фильтров на главной. А другой будет привязан к инпутам min и max и не будет завязан на репозитории. Обновил :)

2019-04-09 10:31 UTC, in19farkt commented on src/features/usersSearch/view/containers/UsersSearchForm/UsersSearchForm.tsx
> +    const getMemoOptions = R.memoizeWith(R.identity, (x: OptionType[]) => x);
@clicktronix @chmnkh Это имело бы смысл если:

1. `getMemoOptions` была бы объявлена в замыкании рендера
2. `const getMemoOptions = R.memoizeWith(R.equals, (x: OptionType[]) => x);`
Тогда в первом рендере при вызове `getMemoOptions(options)` переданный массив `options` замемоизируется, а на каждый следующий рендер, будет создаваться новый массив `options`, но `getMemoOptions` вернет ссылку на массив `options` из первого рендера
3. то что возвращает `getMemoOptions` прямиком попадает в пропс Pure компоненты

При использовании такого подхода мы избежим лишней перерисовки, но потратим ресурс на глубокое сравнение.

2019-04-09 10:35 UTC, in19farkt commented on src/features/repositoriesSearch/view/components/RepositoryPreview/RepositoryPreview.tsx
> +const { repositoriesSearch } = tKeys.features;
Ага, чтобы в одной компоненте ты пишешь так:
```
const { repositoriesSearch: keys } = tKeys.features;
```
а в другой так:
```
const { roflSearch: keys } = tKeys.features; // тоже порофлю немного :)
```
и в обоих компонентах в рендере ты будешь использовать `keys`.

PS: `keys` наверное не самое удачное имя.

2019-04-09 10:44 UTC, clicktronix commented on src/features/repositoriesSearch/view/components/RepositoryPreview/RepositoryPreview.tsx
> +const { repositoriesSearch } = tKeys.features;
Главное тут, чтобы все переводы фичи лежали в ветке переводов данной фичи) и не лезли в другие. Хотя такой подход с разыменовыванием может как раз и будет намекать на это

2019-04-09 10:46 UTC, in19farkt commented on src/services/i18n/i18nContainer.ts
> +i18n
по сути, то что ты забираешь из `i18next`, это уже синглтон.

Т.к. нам инстанс i18n сейчас вообще нигде не нужен, то я предлагаю всё что тут есть просто завернуть в функцию, по возможности нужно создать новый инстанс i18n (а не инициализировать дефолтный импорт из библиотеки), и эту функцию дернуть на старте приложения.

2019-04-09 10:50 UTC, in19farkt commented on src/features/repositoriesSearch/view/components/RepositoryPreview/RepositoryPreview.tsx
> +const { repositoriesSearch } = tKeys.features;
да это же не обязательно про фичи. у тебя может быть какая-то компонента, которая юзает определенную ветку дерева переводов, вот эту ветку ты и разыменовываешь. А какие-то единичные ключи мимо этой ветки можно и напрямую из `tKeys` взять.

2019-04-09 10:56 UTC, clicktronix commented on src/services/i18n/i18nContainer.ts
> +i18n
https://github.com/fullstack-development/react-redux-starter-kit/commit/c9ae97ff4ac3ac33363bb05f6eeedcf4ac6bfddf

2019-04-09 11:13 UTC, chmnkh commented on src/features/usersSearch/view/containers/UsersSearchForm/UsersSearchForm.tsx
> +    const getMemoOptions = R.memoizeWith(R.identity, (x: OptionType[]) => x);
я согласен, что так можно сделать в теории, но не уверен вообще, что прямо "имело бы смысл"))
так можно упороться и все ссылочные типы таким образом мемоизировать, причем еще и с глубоким сравнением приколы лишний раз устраивать, ну такое, тут прямо мотивация хорошая нужна

2019-04-09 11:18 UTC, in19farkt commented on src/features/usersSearch/view/containers/UsersSearchForm/UsersSearchForm.tsx
> +    const getMemoOptions = R.memoizeWith(R.identity, (x: OptionType[]) => x);
не, ну если мы в рендере собираем какой нибудь объект из простых данных, что-бы не расчехлять его на 8 пропсов, а прокинуть одним пропсом. Вот тут можно такую хрень использовать чтобы не перерисовывался компонент каждый раз.

2019-04-10 11:43 UTC, clicktronix commented on src/features/profile/view/containers/ProfileEdit/ProfileEdit.tsx
> +  private makeValidateName() {
https://github.com/fullstack-development/react-redux-starter-kit/pull/71/commits/3dfaad7b9ca051ef3b3a15e119885683b6360ea0

2019-04-11 07:35 UTC, chmnkh commented on src/features/repositoriesSearch/view/components/RepositoryPreview/RepositoryPreview.tsx
> +type IProps = IOwnProps & WithTranslation;
Это, может переименуем в TranslationProps? А то как хок называется

2019-04-11 08:16 UTC, chmnkh commented on src/features/profile/view/containers/ProfileEdit/ProfileEdit.tsx
> +  private makeValidateName() {
я предлагаю эти валидаторы за класс вынести, им ничего из него не нужно, и тем более уж на каждом рендере создания новых фунций можно избежать)

2019-04-11 08:32 UTC, clicktronix commented on src/features/profile/view/containers/ProfileEdit/ProfileEdit.tsx
> +  private makeValidateName() {
ну так то да, теперь можно и вынести

2019-04-11 08:45 UTC, chmnkh commented on src/features/usersSearch/view/containers/UsersSearchForm/UsersSearchForm.tsx
> +      { value: 'username-email', label: t(translations.usernameAndEmail.getKey()) },
блин, мне не нравится вообще что у нас из-за переводов сейчас будут всюду новые объекты плодиться, из-за чего будут ререндеры вечные, притом что функция транслэйта может вообще не меняться долгое время

как с этим борются обычно? самый адекватный способ, который мне на ум приходит, это как-то мемоизировать такие штуки, типа там
```
@memoize
private getOptions(t: TranslateFunction) {
  return [{ value: '...', label: t(...) }];
}
```
@in19farkt  @clicktronix  @NikitaRzm че вы думаете? можно как-то лучше мб сделать

2019-04-11 08:45 UTC, chmnkh commented on src/features/usersSearch/view/containers/UsersSearchForm/UsersSearchForm.tsx
> +      { value: 'username-email', label: t(translations.usernameAndEmail.getKey()) },
тогда и эта фигня 
```
    const filtersValuesFormattersMap: KeysToValuesFormattersMap<IUsersSearchFilters> = {
      searchBy: x => getSelectValuesToLabelsMap(options)[x].toLowerCase(),
      searchFor: x => (labels)[x].toLowerCase(),
    };
```
сможет в свойство класса уйти

и эта фигня:
```
private makeFiltersGetter(filtersValuesFormattersMap: KeysToValuesFormattersMap<IUsersSearchFilters>) {
```
перестанет быть ФВП и не будет каждый раз новая функция создаваться

2019-04-11 08:46 UTC, chmnkh commented on src/features/usersSearch/view/containers/UsersSearchForm/UsersSearchForm.tsx
> +    const renderUsersSearchSettings = () => <UsersSearchSettings options={options} />;
тут лучше в метод вынести, чтобы новая функция в пропсы не падала при каждом рендере

2019-04-11 09:06 UTC, chmnkh commented on src/features/usersSearch/view/containers/UsersSearchForm/UsersSearchForm.tsx
> +      { value: 'username-email', label: t(translations.usernameAndEmail.getKey()) },
хотя я вроде как упоролся и тут достаточно будет просто убрать лишние переменные из рендера и из 
```
 private makeFiltersGetter(filtersValuesFormattersMap: KeysToValuesFormattersMap<IUsersSearchFilters>) 
```
сделать просто метод, вместо фвп

2019-04-12 06:31 UTC, in19farkt commented on src/features/usersSearch/view/containers/UsersSearchForm/UsersSearchForm.tsx
> +      { value: 'username-email', label: t(translations.usernameAndEmail.getKey()) },
Можно воспользоваться хуком useMemo.
```
const options: OptionType[] = useMemo(() => [...], [t]);
```

Или написать мемоизатор с помощью рамды, по принципу useMemo, чтобы мемоизация происходила по массиву переданному вторым аргументом.

2019-04-12 07:01 UTC, chmnkh commented on src/features/usersSearch/view/containers/UsersSearchForm/UsersSearchForm.tsx
> +      { value: 'username-email', label: t(translations.usernameAndEmail.getKey()) },
там же класс компонент(
+ хуки щас юзать не огонь, потому что они с шеллоу рендером не работают (по крайней мере месяц назад не работали точно)

короче у меня немного сумбурно изначальный дискашн вышел, мне короче не нравятся эта фвп:
```
 private makeFiltersGetter(filtersValuesFormattersMap: KeysToValuesFormattersMap<IUsersSearchFilters>)
```
и эта константа:
```
const renderUsersSearchSettings = () => <UsersSearchSettings options={options} />;
```
потому что результат вызова фвп и эта константа в пьюр компонент падают и там ререндер сразу же 

итого надо:
1) константу `renderUsersSearchSettings` в метод вынести, при этом `options` надо как-то вынести, чтобы его можно было передать в `UsersSearchSettings` и в метод, который заменит `makeFiltersGetter` (об этом дальше);
2) `makeFiltersGetter` можно запросто из фвп сделать обычным методом, для чего надо просто `filtersValuesFormattersMap` перенести внутрь этого метода (не понятно зачем там в принципе фвп). 

другой вопрос, что конкретно делать со всеми этими объектами с переводами, типа там:
```
    const labels: LabelsType = {
      both: t(translations.usersAndOrganizations.getKey()),
      org: t(translations.organizations.getKey()),
      user: t(translations.users.getKey()),
    };
```
я за то, чтобы эту фигню (т.е. все подобные объекты с переводами: `filtersLabels`, `options`, `labels`) в геттеры запихать, чтобы она нам не мешалась в коде, и пусть каждый раз пересчитывается
если уж какая-то совсем жопа будет, то можно будет мемоизацию подключить на функцию транслэйта, и тогда, самое простое, это, как мне кажется, написать как в примере в первом сообщении здесь

2019-04-12 07:32 UTC, in19farkt commented on src/features/usersSearch/view/containers/UsersSearchForm/UsersSearchForm.tsx
> +      { value: 'username-email', label: t(translations.usernameAndEmail.getKey()) },
нужно тогда свой мемоизатор написать, потому что `@memoize` из `decko` - это дно. Плюс memoize наверняка работает только с входными параметрами, а нум нужно мемоизировать по пропсам. Я думаю апи мемоизатора для методов КомпонентКласса, должен быть примерно таким:
```
@memoize((params: ParamsType) => [this.props.t, params.something, ...])
private getLabels(_params: ParamsType) {
  const { t } = this.props;
  return {
      both: t(translations.usersAndOrganizations.getKey()),
      org: t(translations.organizations.getKey()),
      user: t(translations.users.getKey()),
    };
}
```

2019-04-12 07:32 UTC, in19farkt commented on src/features/usersSearch/view/containers/UsersSearchForm/UsersSearchForm.tsx
> +      { value: 'username-email', label: t(translations.usernameAndEmail.getKey()) },
> хуки щас юзать не огонь, потому что они с шеллоу рендером не работают
Забавно получается, мы не юзаем нормальный инструмент, во многих местах упрощающий жизнь, потому что библиотека, с помощью которой мы гоняем тесты, еще не умеет с этим инструментом работать :)

Я не говорю что это не правильно, я говорю что это забавно) И судя по этой ише https://github.com/airbnb/enzyme/issues/2011, ситуация не скоро изменится

2019-04-12 08:25 UTC, chmnkh commented on src/features/usersSearch/view/containers/UsersSearchForm/UsersSearchForm.tsx
> +      { value: 'username-email', label: t(translations.usernameAndEmail.getKey()) },
> нужно тогда свой мемоизатор написать, потому что `@memoize` из `decko` - это дно.

а почему?

> Я думаю апи мемоизатора для методов КомпонентКласса, должен быть примерно таким:

мне пока кажется что пока что такую штуку фигачить нету надобности, хз

2019-04-12 08:53 UTC, in19farkt commented on src/features/usersSearch/view/containers/UsersSearchForm/UsersSearchForm.tsx
> +      { value: 'username-email', label: t(translations.usernameAndEmail.getKey()) },
> а почему?

Зайди в  сорцы `memoize` из `decko` и посмотри) Там дичь полнейшая.

> мне пока кажется что пока что такую штуку фигачить нету надобности, хз
как бы это не оказалось кодом, который просто валяться будет

Ты предлагаешь если че замемоизировать и тут же пишешь что нет надобности писать нормальный мемоизатор для методов классовых компонент. -_-

Как ты предлагаешь, скинуть в геттеры и забить хер на то что каждый рендер - это новый объект, который мы передаем в PureComponent, мне кажется не очень нормально. Мы знаем о проблеме, но забиваем на нее, а потом эта проблема поползет по проектам, потому что не все знают и понимают ее.

Этот момент нужно решить, и я вижу два пути: либо нужно убрать PureComponent, либо замемоизировать объект. В случае с мемоизацией, чтобы не засирать память, нужно запоминать только последнее значение и пересчитывать его только при изменении одного из маркеров. И возможно стоит вынести это в стандарты.

Возможно это преждевременная оптимизация, но я считаю пусть лучше она будет и это будет стандартизировано, чем как сейчас - каждый второй бездумно использует PureComponents. @Znack @NikitaRzm вы что думаете?

2019-04-12 08:59 UTC, chmnkh commented on src/features/usersSearch/view/containers/UsersSearchForm/UsersSearchForm.tsx
> +      { value: 'username-email', label: t(translations.usernameAndEmail.getKey()) },
а, блэ, на самом деле я тупанул, надо же в сеттинги опшны пробрасывать, я чото увлекся фвп и об этом забыл)

2019-04-12 15:13 UTC, clicktronix commented on src/features/usersSearch/view/containers/UsersSearchForm/UsersSearchForm.tsx
> +      { value: 'username-email', label: t(translations.usernameAndEmail.getKey()) },
Мне кажется писать отдельный мемоизатор пропсов для КомпонентКласса это оверхед в данном случае, учитывая что там всего пара лейблов переводятся и мы можем вполне обойтись заменой формы с PureComponent на Component. 

В мемоизации пропсов нам все равно придется их глубоко сравнивать, но зачем писать свое, если Component может сравнить пропсы за нас сделать

2019-04-12 16:31 UTC, in19farkt commented on src/features/usersSearch/view/containers/UsersSearchForm/UsersSearchForm.tsx
> +      { value: 'username-email', label: t(translations.usernameAndEmail.getKey()) },
не надо нам ничего глубоко сравнивать. Я предлагаю написать декоратор по принципу useMemo. Конкретно в этом случае это будет выглядеть так:
```
@memoizeBy(() => [this.props.t]) // не уверен что тут будет доступ к this, возможно в декораторе придется вызывать эту функцию с помощью apply
private getLabels() {
  const { t } = this.props;
  return {
      both: t(translations.usersAndOrganizations.getKey()),
      org: t(translations.organizations.getKey()),
      user: t(translations.users.getKey()),
    };
```
Декоратор будет вызывать оборачиваемую функцию на изменение одного из элементов массива (в данном случае там будет одна функция `t`), если изменений нет, то будет возвращать результат предыдущего вызова оборачиваемой функции.

2019-04-18 05:35 UTC, chmnkh commented on src/features/repositoriesSearch/view/containers/RepositoriesSearchForm/RepositoriesSearchForm.tsx
> +import { memoizeByProps } from 'shared/helpers/decorators';
а че может это как и все остальные хелперы из индекса импортить?

2019-04-18 06:02 UTC, chmnkh commented on src/shared/helpers/decorators.ts
> +        const fn = descriptor.value.bind(this) || descriptor.get && descriptor.get.call(this);
не понял эту строчку, когда у нас вообще `fn = descriptor.get && descriptor.get.call(this)` ?

2019-04-18 06:04 UTC, chmnkh commented on src/shared/helpers/decorators.ts
> +        if (typeof fn !== 'function') {
это надо проверять на `descriptor.value` тогда уж, ты же блин на value пытаешься `bind` уже вызвать, а это `Function.prototype`)

2019-04-18 06:21 UTC, in19farkt requested changes

2019-04-18 06:21 UTC, in19farkt commented on src/core/configureApp.ts
> +import { initI18n } from 'services/i18n/i18nContainer';
я за то чтобы писать полностью `initializeI18n`, а то не понятно `init` это сокращение от `initialize` или от `initial`.

2019-04-18 06:21 UTC, in19farkt commented on src/services/i18n/i18nContainer.ts
> +    if (typeof key !== 'string' && !Array.isArray(key) && !key.getKey) {
`typeof key !== 'string' && !Array.isArray(key) && ! isTranslateGetKey(key)`

2019-04-18 06:21 UTC, in19farkt commented on src/services/i18n/namespace.ts
> +export interface IExtendedTranslateKey extends IGetKey {
IExtendedTranslateKey не должно экстендиться от IGetKey, это 2 разные вещи и не нужно их мешать

2019-04-18 06:21 UTC, in19farkt commented on src/services/i18n/index.ts
> +type TranslateFunction = i18next.TFunction;
этот тип нужно переопределить, чтобы транслейт мог принимать ITranslateObject или IGetKey (не самое удачное название, нужно как-то переименовать)

2019-04-18 06:21 UTC, in19farkt commented on src/services/i18n/index.ts
> +  options: Record<string, string | number | object | string[] | object[] | undefined>;
Замени это безобразие на такое :)
```
options: i18next.TOptions;
```

2019-04-18 06:21 UTC, in19farkt commented on src/services/i18n/index.ts
> +type TranslateFunction = i18next.TFunction;
Еще нужно переопределить тип `WithTranslation` и `withTranslation`, чтобы они работали с расширенным типом `TFunction`.

2019-04-18 06:21 UTC, in19farkt commented on src/services/i18n/i18nContainer.ts
> +  i18n.t = ((key: string | string[] | IExtendedTranslateKey, options: {}) => {
тут вместо `IExtendedTranslateKey` должно быть `ITranslateObject | IGetKey`

2019-04-18 06:23 UTC, in19farkt commented on src/shared/helpers/decorators.ts
> +        const fn = descriptor.value.bind(this) || descriptor.get && descriptor.get.call(this);
когда перед этим декоратором отработает декоратор `@bind` или `@autobind` из `core-decorators`. посмотри на их код и поймешь)

2019-04-18 06:24 UTC, in19farkt commented on src/shared/helpers/decorators.ts
> +        const fn = descriptor.value.bind(this) || descriptor.get && descriptor.get.call(this);
Хотя тут немного коряво написано, и в текущем варианте декоратор крашнется если в `descriptor.value` придет `undefined`

2019-04-18 06:27 UTC, in19farkt commented on src/shared/helpers/decorators.ts
> +        const fn = descriptor.value.bind(this) || descriptor.get && descriptor.get.call(this);
Должно быть так:
```
const fn = (
  descriptor.value && descriptor.value.bind(this) ||
  descriptor.get && descriptor.get.call(this)
);
```

2019-04-18 06:28 UTC, in19farkt commented on src/shared/helpers/decorators.ts
> +        if (typeof fn !== 'function') {
тут правильно) Выше косяк

2019-04-18 06:30 UTC, in19farkt commented on src/shared/helpers/decorators.ts
> +        if (typeof fn !== 'function') {
а, хотя да, тут в fn по-любому будет функция или андефайнед

2019-04-18 06:32 UTC, in19farkt commented on src/shared/helpers/decorators.ts
> +        if (typeof fn !== 'function') {
а выше нужны проверки на `value` и `get` перед вызовами `bind` и `call`

2019-04-18 06:35 UTC, in19farkt commented on src/shared/helpers/decorators.ts
> +        const fn = descriptor.value.bind(this) || descriptor.get && descriptor.get.call(this);
С поправкой на следующий дискашен тут должно быть так:
```
const { value, get } = descriptor; // возможно get придется переименовать, но это не точно.
const fn = (
  value && typeof value === 'function' && value.bind(this) ||
  get && typeof get === 'function' && get.call(this)
);
```

2019-04-18 08:41 UTC, clicktronix commented on src/services/i18n/i18nContainer.ts
> +    if (typeof key !== 'string' && !Array.isArray(key) && !key.getKey) {
Ну да, теперь можно `!isTranslateGetKey(key)`, когда `IExtendedTranslateKey` и `IGetKey ` разделил

2019-04-18 08:41 UTC, clicktronix commented on src/services/i18n/index.ts
> +  options: Record<string, string | number | object | string[] | object[] | undefined>;
че то вообще кошмар :D

2019-04-18 09:10 UTC, chmnkh commented on src/shared/helpers/decorators.ts
> +          if (!R.equals(deps, cachedDeps)) {
а глубокое сравнение точно адекватно делать? мне кажется мы так можем легко домемоизироваться и хуже сделать)) может быть лучше просто поэлементно через `===` сравнить?

2019-04-18 09:19 UTC, clicktronix commented on src/shared/helpers/decorators.ts
> +          if (!R.equals(deps, cachedDeps)) {
Что значит поэлементно через ===? я не понэл)

2019-04-18 09:20 UTC, clicktronix commented on src/services/i18n/index.ts
> +type TranslateFunction = i18next.TFunction;
https://github.com/fullstack-development/react-redux-starter-kit/pull/71/commits/74dd4716e4943267f631433d47cd90d3cc01eb58

2019-04-18 09:21 UTC, clicktronix commented on src/shared/helpers/decorators.ts
> +          if (!R.equals(deps, cachedDeps)) {
можно с помощью JSON.stringify сравнить, но тут нужно быть уверенным что порядок свойств сохранится

2019-04-18 09:29 UTC, chmnkh commented on src/shared/helpers/decorators.ts
> +          if (!R.equals(deps, cachedDeps)) {
ну типа такого:
```
const areDepsEqual = cachedDeps.every((x, i) => x === deps[i]); 
```

порядок должен быть одинаковым, да, но мы же `transmitter` один раз задаем, т.е. по идее он будет в одном и том же порядке элементы отдавать

2019-04-18 09:42 UTC, chmnkh commented on src/shared/helpers/decorators.ts
> +        const fn = descriptor.value.bind(this) || descriptor.get && descriptor.get.call(this);
стойте, мы нафига проверяем
```
value && typeof value === 'function'
get && typeof get === 'function'
```
вот так вот 

нам же достаточно только
```
typeof value === 'function'
typeof get === 'function'
```
проверить?
если `typeof x === 'function' === true` то `x === true` и подавно

2019-04-18 09:48 UTC, clicktronix commented on src/shared/helpers/decorators.ts
> +          if (!R.equals(deps, cachedDeps)) {
Тут если в массиве будут объекты, то он будет false возвращать

2019-04-18 09:59 UTC, chmnkh commented on src/shared/helpers/decorators.ts
> +        const value = (...args: any[]) => {
а почему вообще эта функция в геттере определена? у нас сейчас при каждом обращении к методу будет эта функция создаваться зачем-то, в то время как по идее она у нас должна быть определена один раз всего лишь.
вся фигня с переменной `fn` тоже по идее должна сверху проверяться в самом начале, а не при попытке вызвать метод. еще хурму с `Object.defineProperty` я не понимаю зачем писать, объясните плез, на же достаточно дескриптор из декоратора просто вернуть, не?

может я чото где-то не так понял?

2019-04-18 10:03 UTC, chmnkh commented on src/shared/helpers/decorators.ts
> +          if (!R.equals(deps, cachedDeps)) {
ну да, у нас вроде бы и так задача в том числе следить за тем, чтобы объекты, которые падали в пропсы, лишний раз ссылки не меняли, разве нет? нам по сути то и надо ссылки ведь сравнить (те же транслейт функции, ради чего это писалось в том числе). если мы будем каждый раз глубокое сравнение делать, и попытаемся замемоизировать по какому-нибудь объекту дофига вложенному, то мне кажется мы рискуем не только не добиться оптимизации, а вообще все только хуже сделать

2019-04-18 10:57 UTC, in19farkt commented on src/shared/helpers/decorators.ts
> +          if (!R.equals(deps, cachedDeps)) {
Леха верно говорит, нужно поэлементно строго сравнивать элементы массива.

2019-04-18 10:59 UTC, in19farkt commented on src/shared/helpers/decorators.ts
> +        const fn = descriptor.value.bind(this) || descriptor.get && descriptor.get.call(this);
Да, верно, я просто в копипасту предыдущую добавил тайпофы.

2019-04-18 11:13 UTC, in19farkt commented on src/shared/helpers/decorators.ts
> +        const value = (...args: any[]) => {
нам нужен доступ к this, чтобы отдать его в трансмиттер, а сверху этого доступа нет, он есть только в геттере или в value, но value не подойдет, потому что если мемоизированную функцию передадут ссылкой куда-нибудь, то контекст отвалится (его можно сохранить на оборачиваемом методе с помощью декоратора bind, но не на трансмиттере).

И еще я не уверен что get будет вызываться при каждом обращении к обернутой функции. У нас декоратор bind в случае когда мы метод отдаем пропсом, приводил бы к созданию новой функции на каждый рендер, а такого вроде не происходит.

2019-04-18 11:51 UTC, clicktronix commented on src/shared/helpers/decorators.ts
> +        const value = (...args: any[]) => {
Да, тут танцы с контекстом. defineProperty тоже для контекста юзался, но мне кажется его в нынешней реализации можно выпилить

2019-04-18 11:55 UTC, in19farkt commented on src/shared/helpers/decorators.ts
> +        const value = (...args: any[]) => {
а мне казалось что дефайн проперти и делает всю эту магию декораторовскую)) или я не прав?

2019-04-18 11:56 UTC, clicktronix commented on src/shared/helpers/decorators.ts
> +        const value = (...args: any[]) => {
Без него тож работает, потестил только что)

2019-04-18 12:00 UTC, in19farkt commented on src/shared/helpers/decorators.ts
> +        const value = (...args: any[]) => {
чето мне кажется там какой-то косяк всё таки. дефайн проперти внутри get похоже на какой-то хак, нужно понять для чего он.

Посмотри код autobind из core-decorators, там перед дефайн проперти куча проверок, такое ощущение, что на первое обращений за методом пройдет биндинг и вызовется дефайн проперти, а на последующие возвращается уже забинженная ранее функция.

И в bind из decko написано таким образом, чтобы дефайн проперти отработал единожды, там какой-то флаг юзают

2019-04-18 12:01 UTC, in19farkt commented on src/shared/helpers/decorators.ts
> +        const value = (...args: any[]) => {
возможно без этого на каждое обращение за методом будет создаваться и возвращаться новыя функция

2019-04-18 19:45 UTC, clicktronix commented on src/shared/helpers/decorators.ts
> +        const value = (...args: any[]) => {
Ну да, `Object.defineProperty` как то запоминает вызванную функцию, потестил этот момент. Но я нихера не наресерчил по этому поводу, как этот хак объяснить я хз. Такое ощущение, что на первый вызов геттера возвращается `value`, а на остальных вызовах геттер, доходя до `Object.defineProperty`, не возвращает `value`, а работает с тем, что уже было вызвано.

2019-04-18 19:46 UTC, clicktronix commented on src/shared/helpers/decorators.ts
> +        const value = (...args: any[]) => {
https://github.com/NoHomey/bind-decorator/blob/master/src/index.ts вот тут коммент есть по этому поводу

2019-04-19 04:32 UTC, in19farkt commented on src/shared/helpers/decorators.ts
> +        const value = (...args: any[]) => {
> Ну да, Object.defineProperty как то запоминает вызванную функцию, потестил этот момент. 
Он ничего не запоминает, он просто объявляет забинженную исходную функцию непосредственно в создаваемом инстансе.

Получается что обявленный в дескрипторе get вызывается единожды при создании инстанса класса, далее обращение идет напрымую к задекорированному методу. Скорее всего в прототипе остается оригинальный не декорированный метод, а в инстансе декорированный.

2019-04-19 04:43 UTC, chmnkh commented on src/shared/helpers/decorators.ts
> +        const value = (...args: any[]) => {
а, блин, точняк
только в бинде это актуально, потому что это бинд, а здесь это нафиг не надо по идее

2019-04-19 04:57 UTC, in19farkt commented on src/shared/helpers/decorators.ts
> +        const value = (...args: any[]) => {
почему не надо? мы же тут в декораторе собираем функцию, которая занимается вызовом трансмиттера, кешированием результатов и пишем получившуюся функцию в инстанс класса с помошью `defineProperty`. Делаем это через гет, потому что при вызове трансмиттера нам нужен `this`.

Или ты не про `defineProperty`?

2019-04-19 05:11 UTC, chmnkh commented on src/shared/helpers/decorators.ts
> +        const value = (...args: any[]) => {
я про `defineProperty`

> Делаем это через гет, потому что при вызове трансмиттера нам нужен this.

не понял, у нас же и так будет `this`, если мы в прототип положим метод
нафига тогда в инстанс его класть?

2019-04-19 05:19 UTC, in19farkt commented on src/shared/helpers/decorators.ts
> +        const value = (...args: any[]) => {
он будет пока мы вызываем метод на инстансе `this.getSomething()`, а если мы решим передать этот метод пропсом, то контекст отвалится, при чем контекст к самой функции мы сможе привязать с помощью `@bind`, а вот к трансмиттеру уже нет (хотя тут я чето уже сомневаюсь, возможно всё будет норм если @bind применить после мемоизатора)

2019-04-19 05:21 UTC, in19farkt commented on src/features/profile/view/containers/ProfileEdit/ProfileEdit.tsx
> +              label={t(translations.name.getKey())}
Давай уберем везде `.getKey()`

2019-04-19 05:21 UTC, in19farkt commented on src/shared/helpers/decorators.ts
> +        const value = (...args: any[]) => {
еще кстати нужно учитывать что для каждого инстанса должен быть свой кеш

2019-04-19 05:35 UTC, chmnkh commented on src/shared/helpers/decorators.ts
> +        const value = (...args: any[]) => {
> он будет пока мы вызываем метод на инстансе `this.getSomething()`, а если мы решим передать этот метод пропсом, то контекст отвалится, при чем контекст к самой функции мы сможе привязать с помощью `@bind`, а вот к трансмиттеру уже нет (хотя тут я чето уже сомневаюсь, возможно всё будет норм если `@bind` применить после мемоизатора)

ну трансмиттер же внутри функции будет вызываться, все там норм будет с контекстом)

> еще кстати нужно учитывать что для каждого инстанса должен быть свой кеш

это аргумент, да, не подумал над этим)
у нас щас вообще кэш шарится между всеми инстансами же, кстати))

2019-04-19 05:58 UTC, in19farkt requested changes

2019-04-19 05:58 UTC, in19farkt commented on src/features/repositoriesSearch/view/containers/RepositoriesSearchForm/RepositoriesSearchForm.tsx
> +  @memoizeByProps((props: IProps) => [props.t])
а может не будем в мемоизаторе вытаскивать пропсы из `this`, а просто будем вызывать трансмиттер через `call` с привязкой `this`, чтобы трансмиттер можно было писать в таком формате:
```
(formValues: IRepositoriesSearchFormFields) => [this.props.t, formValues.something]
```

2019-04-19 05:58 UTC, in19farkt commented on src/modules/shared/Layout/Layout.tsx
> +    const menuItems: IHeaderMenuItem[] = [
Мемоизатор теперь у нас есть, можно мемоизировать

2019-04-19 05:58 UTC, in19farkt commented on src/services/i18n/index.ts
> +export { tKeys, withTranslation, useTranslation, LanguageSelector };
`withTranslation` я так понял работает без переопределения типа, а вот `useTranslation` нужно поправить тип, чтобы этот хук возвращал расширенный тип `TranslateFunction`

2019-04-19 05:58 UTC, in19farkt commented on src/shared/types/guards.ts
> +import { ITranslateKey, ITranslateObject } from 'services/i18n';
опять у нас шереды залезли в сервисы. Можешь тут не импортить всё это, пусть `isTranslateGetKey ` принимает на вход `any`.

2019-04-19 05:58 UTC, in19farkt commented on src/shared/view/components/SearchForm/SearchForm.tsx
> +import { TranslateFunction, ITranslateObject } from 'services/i18n';
и снова шереды залезли в сервис, хоть и по типам, но залезли.

@NikitaRzm вот че в таком случае делать?

Нам в шередах нужен тип `TranslateFunction`, который определяет сервис `i18n`. Нужен он нам, чтобы файнал-форм-филд мог принять функцию переводчик пропсами и мог с ее помощью перевести ошибку. Из вне мы ее перевести не можем, т.к. она у нас пролетает через контекст и появляется только в файнал-форм-филде, где мы и должны ее перевести.

2019-04-19 05:58 UTC, in19farkt commented on src/shared/view/components/SearchForm/SearchSettingsDialog/SearchSettingsDialog.tsx
> +import { useTranslation, tKeys } from 'services/i18n';
и еще раз, только тут уже не по типам, а по серьёзному залезли, за хуком и ключами

2019-04-19 06:03 UTC, NikitaRzm commented on src/shared/view/components/SearchForm/SearchForm.tsx
> +import { TranslateFunction, ITranslateObject } from 'services/i18n';
Повторяю: не возможно развязать в компайл-тайме, развязыват ьв рантайме.
Если компонент действительно переиспользуется, но хочет специфическую функциональность - пишется у этого комопнента контракт того, что вы хотите. Экспортируется, декларируется в пропсах / конструкторе / параметрах.
Там, где компонент используется - подбирается реализация контракта (хоть функция хоть сервис напрямую), и передается под этот контракт. Просто проблема в том, что в серчформе заранее знаете, что будете что-то переводить, а по идее - вы будете получать условный текст какой-то, будет он переведен или нет - это уже другой уровень несколько. Или если вы говорите что форма хочет перевести себя - она должна задекларировать, что она хочет переводчика в таком формате. Короче обыкновенный IoC.  В таких случаях это крайне удобно. Не компонент решает, кого выбрать для задачи, а тот кто использует компонент или кто-то сверху решает, кого назначить исполнителем контракта, который хочет этот компонент.

2019-04-19 06:03 UTC, NikitaRzm commented on src/shared/view/components/SearchForm/SearchSettingsDialog/SearchSettingsDialog.tsx
> +import { useTranslation, tKeys } from 'services/i18n';
Описал выше все те же случаи :)

2019-04-19 06:04 UTC, in19farkt commented on src/shared/helpers/decorators.ts
> +        const value = (...args: any[]) => {
@clicktronix проверь плиз по поводу одного кеша на один инстанс. У Лехи есть подозрение что сейчас кеш шарится между инстансами. Если это действительно так, то попробуй спрятать кеш внутрь get, если get вызывается один раз при создании инстанса, то это сработает.

Ну и было бы круто эту хреновину хорошенько покрыть тестами)) Если у тебя с временем беда, то обязательно создай на это ишу.

2019-04-19 06:07 UTC, NikitaRzm commented on src/shared/view/components/SearchForm/SearchSettingsDialog/SearchSettingsDialog.tsx
> +import { useTranslation, tKeys } from 'services/i18n';
Здесь в рантайме - это скорее всего будет значить создание функции-creator-а, в которую будет скинуто то, что хочет эта компонента, и вернется уже нужная компонента. Типа хока.

2019-04-19 06:32 UTC, chmnkh commented on src/shared/helpers/decorators.ts
> +        const value = (...args: any[]) => {
там же под капотом по идее такая херня должна быть:
```javascript
Object.defineProperty(
  ClassName.prototype, 
  methodName, 
  memoizeByProps(f)(ClassName.prototype, methodName, тут дескриптор для methodName),
)
```
как раз кэш и создастся при вызове функции, которую `memoizeByProps` возвращает, т.е. один раз.

2019-04-19 06:39 UTC, in19farkt commented on src/shared/view/components/SearchForm/SearchForm.tsx
> +import { TranslateFunction, ITranslateObject } from 'services/i18n';
Да это понятно, звучит всё класно и красиво, а на деле мы сейчас этими развязываниями в рантайме знатно всё усложним.

С типами то понятно, мы можем просто вынести тип `TranslateFunction` в шереды, тем самым мы скажем, что в нашем приложении переводами должна заниматься функция с такой сигнатурой, и уже сервис `i18n` должен будет соблюсти контракт объявленный на уровне всего приложения. Так мы в шеред-компонентах, в том числе в файнал-форм-филдах, будем спокойно просить функцию переводчик, а кто-то сверху будет ее нам предоставлять.

А вот с ключами для переводов `tKeys` не однозначно, они сейчас объявляются в сервисе `i18n`. Было бы удобно в шередах иметь доступ к `tKeys.shared` с ключами для каких-нибудь тупых кнопок типа `Ок` или `Cancel`. Возможно стоит вынести `tKeys` и сами тексты переводов из сервиса `i18n`, у нас же есть функция initializeI18n, которая занимается инициализацией сервиса, вот она то и должна принимать на вход тексты, дефолтный язык и возможно что-то еще.

2019-04-19 06:41 UTC, chmnkh commented on src/shared/helpers/decorators.ts
> +        const value = (...args: any[]) => {
> если get вызывается один раз при создании инстанса, то это сработает.

не понял, в смысле гет вызывается при создании?

2019-04-19 06:49 UTC, in19farkt commented on src/shared/helpers/decorators.ts
> +        const value = (...args: any[]) => {
в том смысле, что нужно разобраться как работает декоратор, если из него вернуть дескриптор с `get`, а не с `value`.

Я не углублялся и не дебажил, но если я правильно понял поведение, то `get` срабатывает один раз для каждого инстанса и в случае с `@bind` объявляет в инстансе забинженный метод, а в случае с мемоизатором должен объявлять в инстансе мемоизированный метод, в замыкании которого должен быть кеш конкретно для этого инстанса.

2019-04-19 06:50 UTC, chmnkh commented on src/shared/helpers/decorators.ts
> +        const value = (...args: any[]) => {
короче тут какая-то путаница вообще, как должно работать, если я правильно все понимаю:
1)  при объявлении класса будет такая вот херня
```javascript
Object.defineProperty(
  ClassName.prototype, 
  methodName, 
  memoizeByProps(f)(ClassName.prototype, methodName, тут дескриптор для methodName),
)
```
то есть в прототипе будет `methodName`, который определен дескриптором, который мы вернем в декораторе.
2. Когда мы будем инстанс создавать, при попытке вызова метода, его не будет в инстансе и мы пойдем в прототип. Там он будет, вот здесь как раз: а) должен создасться кэш; б) метод должен полететь в инстанс (дефайн проперти как раз, который в геттере), чтобы в следующие разы он брался с инстанса, а не с прототипа как сейчас, и использовал кэш из замыкания
3. Т.е. в конце концов методы в прототипе и в инстансе будут лишь тем отличаться, что в прототипе будет еще кэш создаваться дополнительно (потому что он должен лишь 1 раз создаваться, а не при каждом обращении), и так же там будет `fn` определяться, потому что ее тоже один раз нужно всего лишь достать.

2019-04-19 07:00 UTC, in19farkt commented on src/shared/helpers/decorators.ts
> +        const value = (...args: any[]) => {
во, круто всё разложил))

`Value` не подойдет, т.к. в `value` мы должны сразу положить готовую к использованию функцию, мы не сможем в `value` использовать `defineProperty`, а в `get` мы можем эту функцию создать с нужным нам замыканием и с помощью `defineProperty` прихерачить ее к инстансу.

2019-04-19 07:03 UTC, NikitaRzm commented on src/shared/view/components/SearchForm/SearchForm.tsx
> +import { TranslateFunction, ITranslateObject } from 'services/i18n';
А по мне - ты усложняешь все перемещениями. Есть принятые практики развязывания юнитов. Про усложнение - так про все можно сказать, увы. Критерии усложнения нужны.

Это не классно и красиво, это принятая практика с 1980 лохматых годов. Практика уменьшения зацепления, облегчения поддерживания связей между юнитами, ослабления силы связи, и обеспечения определенного уровня абстракции и границ юнита.

Почему вы всю работу со связью юнитов пытаетесь уложить в убогую модульную систему js - я упорно не понимаю. Мы закрыли основные дыры основными правилами. Мы предложили способы уменьшения зацепления.

Ну ты спросил - я сказал. Если у тебя есть решение свое -  я не понял, зачем я тут :)

Это то же самое, что я бы в проекте на бэкэнде пытался все рассовать по многочисленным shared. Но их нет, потому что есть IoC. Практически панацея от циклических зависимостей и нежелательных прямых связей.

В сущности и импорт этот не критичный, но если вы хотите следовать хорошим практикам (которые безусловно играют на руку в долгосрочке), то следуйте без "мы все зачем-то усложняем".  Или не следуйте, и решайте проблемы здесь и сейчас. Это два подхода - выбирайте. Работает как в рамках всего проекта - так и в локальных местах.

2019-04-19 07:04 UTC, chmnkh commented on src/shared/helpers/decorators.ts
> +        const value = (...args: any[]) => {
я имел в виду свойство дескриптора `value` использовать, вместо свойства `get`, а не `value`-функцию, как ее Влад назвал)

2019-04-19 07:07 UTC, chmnkh commented on src/shared/helpers/decorators.ts
> +        const value = (...args: any[]) => {
ну то есть блин, не
```
get() { ... }
```
а 
```
value: function() {...}
```
такое, крч

2019-04-19 07:40 UTC, in19farkt commented on src/shared/helpers/decorators.ts
> +        const value = (...args: any[]) => {
не, смотри, `value` юзать нельзя, потому что это `value` будет в итоге лежать в прототипе и будет шариться между всеми инстансами. Разница между `value` и `get` еще в том, что `value` будет вызван в момент вызова метода, а `get` будет вызван в момент считывания метода из прототипа.

2019-04-19 07:44 UTC, clicktronix commented on src/shared/helpers/decorators.ts
> +        const value = (...args: any[]) => {
Мы не сможем в `value` это положить, потому что в `get` определяется значение `value`. Если положим в value то придется вызывать ее. 

Я только не понял почему кэш может шарится между инстансами? Каким образом? Я ща чекну, конечно) но почему такое может произойти?

2019-04-19 07:48 UTC, in19farkt commented on src/shared/helpers/decorators.ts
> +        const value = (...args: any[]) => {
потому что декоратор вызывается один раз и кеш объявлен в его замыкании, а гет вызывается для каждого инстанса при обращении к методу лежащему в прототипе. Леха выше очень хорошо описал весь этот процесс.

2019-04-19 07:56 UTC, clicktronix commented on src/features/repositoriesSearch/view/containers/RepositoriesSearchForm/RepositoriesSearchForm.tsx
> +  @memoizeByProps((props: IProps) => [props.t])
Тут типы продолбаются в `this.props.t`

2019-04-19 08:03 UTC, chmnkh commented on src/shared/helpers/decorators.ts
> +        const value = (...args: any[]) => {
> `value` будет вызван в момент вызова метода, а `get` будет вызван в момент считывания метода из прототипа.

блин, тупанул, да

2019-04-19 08:33 UTC, in19farkt commented on src/shared/view/components/SearchForm/SearchForm.tsx
> +import { TranslateFunction, ITranslateObject } from 'services/i18n';
Оке. Я понял твою позицию. Сорян если отвлёк.

Возможно я загоняюсь и слишком много внимания уделяю контексту конкретно нашего стартер-кита, нашей архитектуры и зря пытаюсь максимально формализовать процессы/зависимости в коде, по возможности что-то упростить, что-то сделать лучше. Походу нужно взять отпутск в плане развития и поддержки кита :)

2019-04-19 08:35 UTC, in19farkt commented on src/features/repositoriesSearch/view/containers/RepositoriesSearchForm/RepositoriesSearchForm.tsx
> +  @memoizeByProps((props: IProps) => [props.t])
Да, точно. Тогда оставляем как есть

2019-04-19 08:42 UTC, NikitaRzm commented on src/shared/view/components/SearchForm/SearchForm.tsx
> +import { TranslateFunction, ITranslateObject } from 'services/i18n';
Вопрос приоритетов: вы делаете стартовый проект в большей мере, чем демоверсию, т.к. скорее всего такие детали заказчики и интересующиеся врядли будут рассматривать - скорее всего на нем будут удалены такие вещи и сделано под потребности. В таких мелочах может внимание и излишне, соблюдайте баланс :) Главное, чтоб общая архитектура выглядела согласованно, но в таких местах в сущности то - ничего критичного. И в целом и сейчас все окей.

Нет проблем с циклическими зависимостями - ну и окей.

С хуками там еще можно попрыгать, максимум, а тут вообще можешь забить болт на типы. Может проще унести компонент на уровень выше.

Я предлагаю решение не на этот кейс - а на множество таких кейсов. Конкретно тут повторяю можно забить, там где хук нужен - либо IoC, либо рассмотреть перенос компонента на другие уровни.

Посыл короче такой. Плюс ты еще должен четко понимать, что при наличии системы правил (читай нашей архитектуры) ты в проценте случаев не сможешь все уложить в нее в любом случае. Поэтому при желании все формализовать ты обречен на вечный поиск путей формализации :)

2019-04-19 08:44 UTC, NikitaRzm commented on src/shared/view/components/SearchForm/SearchForm.tsx
> +import { TranslateFunction, ITranslateObject } from 'services/i18n';
Да я и не говорил, что такое внимание к мелочам - это плохо. Немного не понял твоего вижна относительно твоего вклада в скит и желания формализации. Просто хорошие практики в подобных небольших случаях будет выглядеть оверхедом при желании формализации всего и вся.

2019-04-19 11:02 UTC, clicktronix commented on src/shared/types/guards.ts
> +import { ITranslateKey, ITranslateObject } from 'services/i18n';
Перенес гвард в сервис, без типов от него толку нет https://github.com/fullstack-development/react-redux-starter-kit/pull/71/commits/6082f1e91aa59fefd4320129eeff8bdd378189be

2019-04-19 11:03 UTC, clicktronix commented on src/services/i18n/index.ts
> +export { tKeys, withTranslation, useTranslation, LanguageSelector };
https://github.com/fullstack-development/react-redux-starter-kit/pull/71/commits/986de5bb55adbb83da2bee1c2216a117d52b52ae

2019-04-19 11:03 UTC, clicktronix commented on src/features/profile/view/containers/ProfileEdit/ProfileEdit.tsx
> +              label={t(translations.name.getKey())}
https://github.com/fullstack-development/react-redux-starter-kit/pull/71/commits/e180ae6c0c5becec0fad834c5ff9ea1be7956daa

2019-04-19 11:08 UTC, clicktronix commented on src/shared/view/components/SearchForm/SearchSettingsDialog/SearchSettingsDialog.tsx
> +import { useTranslation, tKeys } from 'services/i18n';
https://github.com/fullstack-development/react-redux-starter-kit/pull/71/commits/04dfbcee3fe0c3b44b5dff02ae0c3cdd4e1d2f7c

Убрал, но пробрасывать тексты в форму пропсами вообще не очень =/, особенно если форма разрастется. Возможно стоит tKeys добавить в IoC и инжектить где надо ключи, а пробрасывать пропсами только функцию перевода(только давайте отдельно это сделаем, а то пр так никогда не вмержится:)). А вот что с типами делать из сервиса хз, не думаю что круто будет переносить их в шереды, может оставить такое допущения для типов. Это к обсуждениям выше

2019-04-19 11:18 UTC, NikitaRzm commented on src/shared/view/components/SearchForm/SearchSettingsDialog/SearchSettingsDialog.tsx
> +import { useTranslation, tKeys } from 'services/i18n';
Господа, просьба: привыкайте доводы оформлять несколько более конкретно, чем "вообще не очень", мне интересны не эмоциональные чувства и абстрактные суждения, а критика и доводы в пользу тех или иных решений, сугубо на будущее, учитесь аргументировать и критиковать :)

2019-04-19 11:24 UTC, clicktronix commented on src/shared/view/components/SearchForm/SearchSettingsDialog/SearchSettingsDialog.tsx
> +import { useTranslation, tKeys } from 'services/i18n';
Я к тому, что чем больше будет в форме текста, тем больше придется прокидывать переводов пропсами. И объявление формы будет из-за этого получится большим и плохо читаемым

2019-04-19 11:26 UTC, NikitaRzm commented on src/shared/view/components/SearchForm/SearchSettingsDialog/SearchSettingsDialog.tsx
> +import { useTranslation, tKeys } from 'services/i18n';
Если текста будет больше - то видимо и функционала, а с этим уже надо будет глобально что-то делать, тут короче по ситуации решать.

2019-04-19 11:49 UTC, in19farkt commented on src/shared/types/guards.ts
> +import { ITranslateKey, ITranslateObject } from 'services/i18n';
Да, точно, тут тупанул, нам же нужно из гварда вернуть тип `ITranslateKey`...

2019-04-19 12:03 UTC, in19farkt commented on src/shared/view/components/SearchForm/SearchSettingsDialog/SearchSettingsDialog.tsx
> +import { useTranslation, tKeys } from 'services/i18n';
Мне кажется основная проблема в том, что такая форма не должна лежать в шередах на уровне всего приложения. Если в компоненте много текстов и много функционала, то и лежать она должна на более высоком уровне, там где мы можем юзать сервис для переводов, чтобы сформировать наполнение этой формы.

А если мы пишем компоненту в шередах на уровне приложения, то и хардкода в ней не должно быть (например, тексты или ключи для переводов), и не должно быть каких-то прямых зависимостей, а тем более импорта чего-то осязаемого из сервисов или от куда-то еще с верхних уровней. Импорты типов, я думаю, в некоторых случаях можно допускать, их в рантайме нет.

2019-04-20 09:19 UTC, chmnkh commented on src/shared/helpers/decorators.ts
> +        const fn: undefined | false | ((...args: any[]) => any) = (
Как смотрите на то, чтобы заюзать на `fn` тип `unknown`, и ниже проверять не просто `!fn`, а `typeof fn !== 'function'`? Потому что тогда мы ни на что завязываться не будем вообще. Учитывая, что у нас `oldValue` и `getter` могут вообще чем угодно быть теоретически, мне кажется то, как сейчас затипизировано - это вообще небезопасно нифига и не очевидно.

2019-04-20 09:20 UTC, chmnkh commented on src/shared/helpers/decorators.ts
> +        const fn: undefined | false | ((...args: any[]) => any) = (
Кстати get уже по определению function, не понял нафиг мы его ниже проверяем на это

2019-04-20 09:45 UTC, chmnkh commented on src/shared/view/components/SearchForm/SearchForm.tsx
> +import { TranslateFunction, ITranslateObject } from 'services/i18n';
Мне вообще грустно смотреть, как отразилось добавление переводов на коде демо-приложения: все компоненты с текстом стали жирнее раза в два, логика усложнилась, появилось куча дополнительных пропсов. То есть даже "частичное" соблюдение "правил" архитектуры нихерово так все усложнило.

2019-04-20 11:05 UTC, in19farkt commented on src/shared/helpers/decorators.ts
> +        const fn: undefined | false | ((...args: any[]) => any) = (
Да, точно, тут небольшой просер по типам, т.к. `getter.call(this)` может вернуть всё что угодно. Поддерживаю Лехино предложение по поводу `unknown`  и дополнительной проверки ниже.

2019-04-20 11:07 UTC, in19farkt commented on src/shared/helpers/decorators.ts
> +        const fn: undefined | false | ((...args: any[]) => any) = (
> Кстати get уже по определению function, не понял нафиг мы его ниже проверяем на это

`getter` и `oldValue` могут быть равны `undefined`

2019-04-22 07:39 UTC, chmnkh commented on src/shared/helpers/decorators.ts
> +type Transmitter = (deps: any, args?: any) => any[];
щас полез проверять приложение:
поиск реп сломался, потому что ты там мемоизируешь `getFilters` только по фунции транслейта, в то время как тебе надо еще и `formValues` мемоизировать

Во-первых, я чо вообще на этой строчке дискашн-то оставляю, я когда это пофиксить попытался, обнаружил, что тип трансмиттера странно объявлен: по идее он же ведь таким должен быть:
```
type Transmitter = (props: any, ...args: any[]) = >any;`
```

Во-вторых, я бы в данном случае (на `getFilters`) мемоизацию убрал в принципе, потому что одно дело мемоизировать всякие вещи, которые постоянно пересоздаются, что в свою очередь ререндер вызывает, а другое дело просто функции, ссылка на которые не меняется (как в данном случае, например). Мне кажется здесь от мемоизации вполне отказаться можно.

2019-04-22 07:55 UTC, in19farkt commented on src/shared/helpers/decorators.ts
> +type Transmitter = (deps: any, args?: any) => any[];
Да, с `formValues` продолбались.

А вообще сама мемоизация здесь уместна, т.к. `getFilters` собирает объект и при каждом вызове это будет новый объект. Но если результат вызова `getFilters`, где-нибудь на глубине, не передается пропсом, а сразу отрисовывается в рендере, то смысла в этой мемоизации вроде бы и нет.

2019-04-22 08:02 UTC, chmnkh commented on src/shared/helpers/decorators.ts
> +type Transmitter = (deps: any, args?: any) => any[];
Ну она теоретически уместна, но это как минимум в `SearchForm` надо делать, а не в каждой компоненте, которая `SearchForm` использует и передает туда `getFilters` коллбэк, это не забота этих внешних компонент вообще.

Но с другой стороны `SearchForm` на это забить может, т.к. там не большой оверхед на ререндере будет, имхо.

2019-04-22 08:04 UTC, NikitaRzm commented on src/shared/view/components/SearchForm/SearchForm.tsx
> +import { TranslateFunction, ITranslateObject } from 'services/i18n';
Это ты еще арабский инвертированный вид не добавлял :)

2019-04-22 11:17 UTC, clicktronix commented on src/shared/helpers/decorators.ts
> +type Transmitter = (deps: any, args?: any) => any[];
Думаю все таки стоит замемоизировать там как минимум при вызове попапа настроект не будет лишних вызовов. Но почему в `SearchForm` надо это делать? Я думаю наоборот надо в `SearchForm` передавать готовые пропсы, мемоизированные или нет. А что если я не захочу мемоизировать, а у меня вшита мемоизация внутри `SearchForm`? Писать функционал на отключение мемоизации?)

2019-04-22 11:59 UTC, chmnkh commented on src/shared/helpers/decorators.ts
> +type Transmitter = (deps: any, args?: any) => any[];
> Думаю все таки стоит замемоизировать там как минимум при вызове попапа настроект не будет лишних вызовов. 

Не понял про попап, можешь подробнее?

> Но почему в `SearchForm` надо это делать? 

Короч щас глянул более тщательно, да, надо сверху таки мемоизировать.

И кстати обрати внимание, у тебя в юзер серч форме мемоизация на `getLabels`, хотя должна быть на `getFitltersGetter` (кстати просто `getFilters` лучше, щас как фвп названо почему-то). Смысла от мемоизации `getLabels` особо нету, все равно `getFiltersGetter` каждый раз новый объект вернет.

2019-04-23 02:41 UTC, chmnkh approved these changes

2019-05-06 12:32 UTC, clicktronix commented
@in19farkt мержим его?)

2019-05-06 18:31 UTC, in19farkt commented
@clicktronix конфликты :(

2019-05-06 18:39 UTC, in19farkt approved these changes

2019-05-08 09:52 UTC, clicktronix commented
@in19farkt порешал

2019-05-08 12:54 UTC, in19farkt commented
@chmnkh @clicktronix надо локально всё проверить, и если всё нормально работает, тесты норм и ничего не поломали, то наверное можно мержнуть.

2019-05-18 10:39 UTC, Znack commented
@chmnkh @clicktronix а какой тут статус сейчас? :)

2019-05-18 11:01 UTC, clicktronix commented
Я тесты поправил, все протыкал, вроде работает. Но у нас изоморфность в мастере поломана, стили не рендерятся

2019-05-19 05:41 UTC, chmnkh commented
запамятовал про пр, завтра гляну тоже

2019-05-20 03:59 UTC, NikitaRzm approved these changes

2019-05-20 03:59 UTC, NikitaRzm commented on src/features/repositoriesSearch/view/components/RepositoryPreview/RepositoryPreview.tsx
> +const { repositoriesSearch: translations } = tKeys.features;
Можешь называть короче: `translations` -> `intl` - в разы короче и уже похоже на ДСЛ чем-то )

2019-05-20 10:49 UTC, clicktronix commented on src/features/repositoriesSearch/view/components/RepositoryPreview/RepositoryPreview.tsx
> +const { repositoriesSearch: translations } = tKeys.features;
Не очень очевидно было сначало, почему именно intl :) да и тема dsl оказалась куда обширнее, чем читка пары статей.

2019-05-20 14:55 UTC, chmnkh commented
приложение и тесты проверил: все нормас

2019-05-21 09:21 UTC, clicktronix commented on src/features/repositoriesSearch/view/components/RepositoryPreview/RepositoryPreview.tsx
> +const { repositoriesSearch: translations } = tKeys.features;
Переименовал, выглядит эргономичнее :D

2019-05-22 17:39 UTC, merged