wip 74 demo app tests
fullstack-development/react-redux-starter-kit pull request #81
Opened 2019-02-28 04:30 UTC by chmnkh

2019-02-28 10:37 UTC, Znack approved these changes

2019-03-02 18:01 UTC, kinda-neat commented
Sorry, wanted to report a bug when searching repos using single space - the request failed with 422 code. Recommend to use .trim() for such kinds of things.
![image](https://user-images.githubusercontent.com/27883524/53685617-9ef3cf80-3d4f-11e9-8db4-0b378aebb4c2.png)

2019-03-03 12:14 UTC, chmnkh commented
![image](https://user-images.githubusercontent.com/18498637/53694999-96030c80-3de8-11e9-8030-b4083acd92fe.png)
а ты хорош

2019-03-06 06:16 UTC, in19farkt commented on src/features/profile/view/components/ProfileAvatar/__tests__/index.test.tsx
> +  it('should match snapshot', () => {
я предлагаю такие тесты вообще не писать, т.к. смысла в них вообще никакого не вижу. Они просто фиксируют внутреннюю структуру компоненты, при этом не защищают от кривой верстки вообще никак. Ну и еще фиксирует какие пропсы мы передали в дочерние компоненты, при этом если пропс функциональный, то опять же мы в снапшоте не видим что это за функция, мы видим сам факт того что какая-то функция передается.

Я думаю стоит использовать снапшоты только если в верстке есть какая-то логика (ветвления/циклы, рисуем массив с предварительной фильтрацией, и т.д.), чтобы убедиться что эта логика правильно отрабатывает, при тех или иных входных значениях.

2019-03-11 10:47 UTC, chmnkh commented on src/features/profile/view/components/ProfileAvatar/__tests__/index.test.tsx
> +  it('should match snapshot', () => {
Перепилил тесты, можно еще раз пытаться смотреть)

2019-03-14 07:00 UTC, in19farkt commented on src/features/profile/view/containers/ProfilePreview/__tests__/index.test.tsx
> +    const info = component.find('.profile-preview__info');
предлагаю брать блок (b) из компоненты, тогда в случае переименовывания блока не придется переписывать тесты:
```
import { ProfilePreview, IProfilePreviewProps, b } from '../ProfilePreview';
// ...
const info = component.find(b('info'));
```

2019-03-14 07:00 UTC, in19farkt commented on src/features/profile/view/containers/ProfilePreview/__tests__/index.test.tsx
> +  const component = mount(<ProfilePreview {...props}/>); // mount required for popover to work
ты шаришь один и тот же компонент для всех тест-кейсов, т.е. твои тест-кейсы не являются чистыми, и если поменять местами первый и второй тест-кейс, то тесты крашнутся.

Каждый тест-кейс должен быть самодостаточным и тест-кейсы не должны шарить между собой какие-либо потенциально мутируемые данные. На крайняк нужно сбрасывать такой общий стейт с помощью beforeEach перед каждым тест-кейсом. Но использование beforeEach тоже спорно, т.к. инициализация каждого тест-кейса размазывается по файлу и их сложнее читать. Поэтому наверное не стоит без лишней необходимость использовать beforeEach.

2019-03-14 07:00 UTC, in19farkt commented on src/features/profile/view/containers/ProfilePreview/__tests__/index.test.tsx
> +    const info = component.find('.profile-preview__info');
с маунтом конечно этот тест выглядит более абстрактно и без привязки к внутренней реализации компонента, но маунт более тяжелый и предпочтительнее использовать шелоу. Я бы наверное в этом случае написал примерно такой тест-кейс "should open popover with profile info on avatar click" и затестил изменение пропса `open` на поповере.

2019-03-14 07:00 UTC, in19farkt commented on src/features/repositoriesSearch/view/containers/RepositoriesSearchForm/__tests__/index.test.tsx
> +  const searchForm = component.find('SearchForm');
мне кажется такие компоненты внутри шелоу врапера нужно искать передавая в find непосредственно ComponentType, так шелоу врапер подхватит тип пропсов и не нужно будет типизировать searchForm.prop, а также при изменении апи SearchForm, мы на уровне типов увидим ошибку в тестах.

2019-03-14 07:00 UTC, in19farkt commented on src/features/repositoriesSearch/view/containers/RepositoriesSearchForm/__tests__/index.test.tsx
> +  const searchForm = component.find('SearchForm');
и еще мы в тестах увидим изменение сигнатуры функционального пропса, сейчас же ты каждый такой пропс перед вызовом типизируешь вручную.

2019-03-14 07:00 UTC, in19farkt commented on src/features/repositoriesSearch/view/containers/RepositoriesSearchResults/__tests__/index.test.tsx
> +    paginationControls.prop<(page: number) => void>('onPageRequest')(page);
такие штуки кстати можно писать так:
```
paginationControls.simulate('pageRequest', page);
```
но текущий вариант будет предпочтительнее, если шелоу врапер будет знать тип пропсов компоненты. Симулейт, в отличие от ShallowWrapper.prop, полностью игнорирует типы.

2019-03-14 08:50 UTC, chmnkh commented on src/features/profile/view/containers/ProfilePreview/__tests__/index.test.tsx
> +    const info = component.find('.profile-preview__info');
Во-первых, тесты все равно придется переписывать, потому что имя блока там и так и так фигурирует во всяких мессаджах, импортах и так далее. И попутно там поменять имя блока в классах большой проблемы не составит.
Во-вторых, придется так писать:
```
const info = component.find(`.${b('info')}`);
```
писать такие строки (пусть даже копипастить) - так себе удовольствие, имхо. И выглядит это сильно всратее, чем тупо дублировать имя блока в этих селекторах. 
Имхо - тут неоднозначно, но если на твой взгляд писать так, как я написал выше, прямо лучше - то ок.

2019-03-14 09:23 UTC, in19farkt commented on src/features/profile/view/containers/ProfilePreview/__tests__/index.test.tsx
> +    const info = component.find('.profile-preview__info');
Да, точно. Забыл что поиск идет по селектору и нужно к имени класса добавлять точку. Вот дно...
```typescript
component.find('.' + b('info')); // так тоже дерьмово выглядит...
```

2019-03-14 09:32 UTC, Znack commented on src/features/profile/view/containers/ProfilePreview/__tests__/index.test.tsx
> +    const info = component.find('.profile-preview__info');
Здесь Леха хотел скорее всего интеграционно проверить уже, mount для этого как раз. Но пару юнит тестов на те правила что ты описал тоже стоит добавить. Я бы просто два файлика сделал: юнит тесты с проверкой как у тебя, и эти бы тестыв файле интеграционных бы оставил

2019-03-14 10:33 UTC, chmnkh commented on src/features/profile/view/containers/ProfilePreview/__tests__/index.test.tsx
> +    const info = component.find('.profile-preview__info');
Маунт здесь тупо чтобы поповер рендерился и прятал профайл инфо. В принципе, если написать как Дима предлагает, то потребность в маунте на самом деле отпадет. То что, поповер с open={true} рендерит чилдренов нам уже известно.

2019-03-14 12:08 UTC, chmnkh commented on src/features/repositoriesSearch/view/containers/RepositoriesSearchResults/__tests__/index.test.tsx
> +    paginationControls.prop<(page: number) => void>('onPageRequest')(page);
кул, не знал)

2019-03-14 12:09 UTC, chmnkh commented on src/features/profile/view/containers/ProfilePreview/__tests__/index.test.tsx
> +    const info = component.find('.profile-preview__info');
че в итоге, оставляем?

2019-03-14 12:23 UTC, in19farkt commented on src/features/profile/view/containers/ProfilePreview/__tests__/index.test.tsx
> +    const info = component.find('.profile-preview__info');
думаю да, не очень удобно конечно, но других вариантов я не вижу.

2019-03-14 12:24 UTC, in19farkt commented on src/features/profile/view/containers/ProfilePreview/__tests__/index.test.tsx
> +    const info = component.find('.profile-preview__info');
еще мне интересно как мы это будем разруливать, когда прикрутим css модули, наверняка есть какие-то нюансы.

2019-03-14 14:37 UTC, Znack commented on src/features/profile/view/containers/ProfilePreview/__tests__/index.test.tsx
> +    const info = component.find('.profile-preview__info');
А мы их будем прикручивать? :) Там точно будут ещё какие нюансы, я в птичке css модули в том числе из-за тестов и выпилил (ну и плюс по аналитике мешали, так как там желательно на проде иметь четкие читаемые классы)

2019-03-14 14:47 UTC, clicktronix commented on src/features/profile/view/containers/ProfilePreview/__tests__/index.test.tsx
> +    const info = component.find('.profile-preview__info');
Еще интеграционные тесты писать больно будет, на даталайте с этим трабл был из-за постфиксов рандомных

2019-03-15 03:25 UTC, chmnkh commented on src/features/profile/view/containers/ProfilePreview/__tests__/index.test.tsx
> +    const info = component.find('.profile-preview__info');
тэк, анрезолвлю чтобы это не терялось пока

2019-03-15 06:09 UTC, chmnkh commented on src/features/profile/view/containers/ProfilePreview/__tests__/index.test.tsx
> +  const component = mount(<ProfilePreview {...props}/>); // mount required for popover to work
ну поскольку там шарится `component` (почти везде только он), то я более адекватного способа чем `beforeEach` не вижу, потому что каждый раз руками его рендерить не огонь

2019-03-15 06:47 UTC, Znack commented on src/features/profile/view/containers/ProfilePreview/__tests__/index.test.tsx
> +  const component = mount(<ProfilePreview {...props}/>); // mount required for popover to work
Не, ну в `beforeEach` ещё можно, а у тебя тут прямо один и тот же компонент шарится, с мутабельным стейтом :) Поэтому и будут зависимости тестов друг от друга, что не очень хорошо. Надо в `beforeEach` каждый раз сбрасывать все в `component`

2019-03-15 06:59 UTC, clicktronix commented on src/features/profile/view/containers/ProfilePreview/__tests__/index.test.tsx
> +  const component = mount(<ProfilePreview {...props}/>); // mount required for popover to work
Можно такое юзать, мне кажется, в этом случае:
```
function getComponent(props?: Partial<IProps>) {

  const defaultProps: IProps = {
    onEditClick: jest.fn(),
    profile,
  };

  return shallow(<ProfilePreview {...defaultProps} {...props} />);
}
```

2019-03-15 08:03 UTC, in19farkt commented on src/features/profile/view/containers/ProfilePreview/__tests__/index.test.tsx
> +  const component = mount(<ProfilePreview {...props}/>); // mount required for popover to work
в данном случае beforeEach хорош до тех пор, пока не нужно тестить какую-то логику в зависимости от входных пропсов, как только такая потребность возникнет, нужно будет переходить на способ который Влад описал в прошлом комментарии.

Я хотел написать хелпер, что-то типа
```typescript
function makeShallowGenerator(Component: React.CompoenntType, defaultProps?: Partial<Props>): (props: ResultProps) => Enzime.ShallowWrapper; 
```
тут ResultProps - это тип который равен Props, но с опциональными полями переданными в defaultProps.

И я не придумал как это всё нормально затипизировать. Проблема в том, что нужно сделать чтобы в defaultProps нельзя было передать лишние поля и в тоже время нам нужно получить тип переданного defaultProps, чтобы пометить соответствующие поля Props как опциональные.

2019-03-15 08:25 UTC, chmnkh commented on src/features/profile/view/containers/ProfilePreview/__tests__/index.test.tsx
> +  const component = mount(<ProfilePreview {...props}/>); // mount required for popover to work
Я в подобных хэлперах вообще не вижу смысла. Вызов хэлпера нам тупо заменит вызов `shallow`, в чем смысл тогда?

Если нам нужно тестить логику в зависимости от пропсов, то можно `setProps` использовать. Отказываться от `beforeEach` и везде руками заново рендерить компонент, только потому что нам где-то в одном тест кейсе понадобилось с другой пропсой потестить, это жестко. В чем проблема использовать `setProps` в таких случаях?

2019-03-15 08:30 UTC, Znack commented on src/features/profile/view/containers/ProfilePreview/__tests__/index.test.tsx
> +  const component = mount(<ProfilePreview {...props}/>); // mount required for popover to work
Если ты в `beforeEach` всегда четко вычищаешь старую компоненту и делаешь новую, то проблем нет (ну кроме неявных мутаций, что кстати уже "попахивает"). А с обычным компонентом в замыкании как у тебя сейчас и setProps все очень плохо, так как у тебя может быть стейт помимо пропсов (локальный стейт, контекст, замыкания и тд), которые будут влиять на последующие тесты крайне непредсказуемо.

2019-03-15 08:40 UTC, chmnkh commented on src/features/profile/view/containers/ProfilePreview/__tests__/index.test.tsx
> +  const component = mount(<ProfilePreview {...props}/>); // mount required for popover to work
Ну с тем как сейчас я понимаю, я именно в связке с beforeEach имел в виду.
Насчет "неявных мутаций", а что неявного?

2019-03-15 08:48 UTC, Znack commented on src/features/profile/view/containers/ProfilePreview/__tests__/index.test.tsx
> +  const component = mount(<ProfilePreview {...props}/>); // mount required for popover to work
У тебя код, который запускают твои тесты, может разным образом мутировать компоненту, запуская разные коллбеки или обновляя пропсы. В тестах ты ничего про внутреннее устройство компонента знать не можешь, поэтому нельзя надеяться на то, что у тебя там какой-нибудь componentWillReceiveProps не висит, который в локальный стейт фигню какую-нибудь складывает :)

2019-03-15 09:04 UTC, chmnkh commented on src/features/profile/view/containers/ProfilePreview/__tests__/index.test.tsx
> +  const component = mount(<ProfilePreview {...props}/>); // mount required for popover to work
так, а почему при тестировании конкретного тест кейса, т.е. конкретной узкой части функциональности компоненты, притом, что на каждый тест кейс "свежая" компонента поступает, меня это волновать должно?
в чем принципиальная разница тестов с обновлением пропсы, и тестов с рендером новой компоненты с определенным значением пропсы? почему мы можем полагаться на то, что на инишиал рендере у нас того, о чем ты говоришь, не будет, а при последующих рендерах, внезапно, будет?

2019-03-15 09:39 UTC, Znack commented on src/features/profile/view/containers/ProfilePreview/__tests__/index.test.tsx
> +  const component = mount(<ProfilePreview {...props}/>); // mount required for popover to work
Погоди, я все говорю без учета beforeEach. У тебя тут код был написан без него, просто сверху определялся компонент и напрямую везде юзался :) Ты тоже про этот кейс или про beforeEach, где у тебя каждый раз компонента переопределятся и просто перезаписывает прошлую прееменную?

2019-03-15 09:56 UTC, chmnkh commented on src/features/profile/view/containers/ProfilePreview/__tests__/index.test.tsx
> +  const component = mount(<ProfilePreview {...props}/>); // mount required for popover to work
> Если ты в beforeEach всегда четко вычищаешь старую компоненту и делаешь новую, то проблем нет (ну кроме неявных мутаций, что кстати уже "попахивает").

ты написал так, как будто это к случаю с `beforeEach` относится)

2019-03-15 10:12 UTC, Znack commented on src/features/profile/view/containers/ProfilePreview/__tests__/index.test.tsx
> +  const component = mount(<ProfilePreview {...props}/>); // mount required for popover to work
А, не, я там имел ввиду, что с beforeEach есть проблема неявной мутации той переменной `component`, что в идеале бы конечно тоже избежать бы, но мир жесток и в принципе тут это приемлимый trade off :)

2019-03-15 11:55 UTC, in19farkt commented on src/features/profile/view/containers/ProfilePreview/__tests__/index.test.tsx
> +  const component = mount(<ProfilePreview {...props}/>); // mount required for popover to work
@chmnkh Смотри, на сколько я помню, шеллоу вызывает некоторые методы жизненного цикла (как минимум willMount), и setProps тоже имеет некоторый сайд эффект в этом плане (componentWilReceiveProps). Т.е. если ты отрисуешь компоненту внутри тесткейса (с помощью хелпера или без него), то ты получишь чистую, отрендеренную один раз компоненту, а если ты отрисуешь ее в beforeEach и в тесткейсе на компоненте дернешь setProps, то получишь не факт что чистую компоненту, которая один раз уже перерендерилась и побывала в componentWilReceiveProps.

Ну и еще один пример: представь что у тебя в componentWillMount есть некоторая логика, например, ветвление от пропса. И тебе нужно в одном тесткейсе затестить одну ветку твоей логики, а в другом вторую. Это не возможно сделать используя beforeEach, т.к. начальные пропсы, которые попадут в componentWillMount жестко захардкожены.

2019-03-15 12:13 UTC, kinda-neat commented on src/features/profile/view/containers/ProfilePreview/__tests__/index.test.tsx
> +  const component = mount(<ProfilePreview {...props}/>); // mount required for popover to work
> Можно такое юзать, мне кажется, в этом случае:
> 
> ```
> function getComponent(props?: Partial<IProps>) {
> 
>   const defaultProps: IProps = {
>     onEditClick: jest.fn(),
>     profile,
>   };
> 
>   return shallow(<ProfilePreview {...defaultProps} {...props} />);
> }
> ```
> и в каэжом тесте получается независимый компонент без beforeEach

здесь `const defaultProps = ...` вынести выше функции надо. вообще, мы так же делаем на импровадо, у нас есть функция которая возвращает shallow компоненту и мы в нее partial пропсы прокидываем, которые нужны в данном конкретном тест-кейсе

2019-03-15 12:39 UTC, chmnkh commented on src/features/profile/view/containers/ProfilePreview/__tests__/index.test.tsx
> +  const component = mount(<ProfilePreview {...props}/>); // mount required for popover to work
> если ты отрисуешь ее в beforeEach и в тесткейсе на компоненте дернешь setProps, то получишь не факт что чистую компоненту, которая один раз уже перерендерилась и побывала в componentWilReceiveProps

Если нужно протестить кейс "если у компоненты пропса Х равна Y, то ожидается такое-то поведение", то по идее неважно должно быть, поменялась ли пропса в рантайме, или была изначально задана. Если вдруг на апдейте какая-то особая логика (чисто в рамках тесткейса, опять же) происходит, то для этого должны отдельные тест кейсы писаться.

> Ну и еще один пример: представь что у тебя в componentWillMount есть некоторая логика, например, ветвление от пропса. И тебе нужно в одном тесткейсе затестить одну ветку твоей логики, а в другом вторую. Это не возможно сделать используя beforeEach, т.к. начальные пропсы, которые попадут в componentWillMount жестко захардкожены.

ну это нетипичный случай, и его надо в порядке исключения рассматривать
сейчас ни одного такого случая в проекте нету, например)

2019-03-20 07:36 UTC, chmnkh commented on src/features/profile/view/containers/ProfilePreview/__tests__/index.test.tsx
> +  const component = mount(<ProfilePreview {...props}/>); // mount required for popover to work
ну так чо :(

2019-03-20 08:52 UTC, in19farkt commented on src/features/profile/view/containers/ProfilePreview/__tests__/index.test.tsx
> +  const component = mount(<ProfilePreview {...props}/>); // mount required for popover to work
В жизненном цикле компоненты есть метод `componentWillReceiveProps`, и не важно объявили мы его или нет, он всё равное есть и никуда от этого нам не уйти. Исходя из этого мое мнение по поводу использования `setProps`: мы должны использовать `setProps`, ТОЛЬКО если хотим затестить какую-то логику завязанную на смену пропсов, во всех остальных случаях мы должны рендерить новую компоненту.

По поводу `beforeEach` и хелпера `getComponent`. `beforeEach` экономит нам одну строку кода в каждом тесткейсе (больше преимуществ я не вижу) и вместе с этим накладывает определенные ограничения. `beforeEach` можно использовать до тех пор, пока не нужно изменять входные пропсы. Как только кто-то добавит в компоненту логику которая зависит от входных пропсов, ему придется переписать `beforeEach` на хелпер `getComponent`.

@NikitaRzm @Znack @clicktronix @chmnkh @kinda-neat поправьте если я несу бред))

2019-03-20 09:49 UTC, chmnkh commented on src/features/profile/view/containers/ProfilePreview/__tests__/index.test.tsx
> +  const component = mount(<ProfilePreview {...props}/>); // mount required for popover to work
Укажи плиз на конкретную проблему, которая возникает, если мы тестируем поведение компоненты, которое не зависит от того, была ли зарендерена новая компонента или апдейтнута старая (а это в большинстве случаев так) через сетпропс.

2019-03-20 12:05 UTC, in19farkt commented on src/features/profile/view/containers/ProfilePreview/__tests__/index.test.tsx
> +  const component = mount(<ProfilePreview {...props}/>); // mount required for popover to work
Т.е. для тебя наличие сайд эффекта на этапе подготовки компоненты к тестированию - не проблема?

И я не понимаю в чем проблема использовать чистый и гибкий `getComponent` вместо проблемной связки `beforeEach + setProps`?

2019-03-20 15:36 UTC, Znack commented on src/features/profile/view/containers/ProfilePreview/__tests__/index.test.tsx
> +  const component = mount(<ProfilePreview {...props}/>); // mount required for popover to work
@chmnkh Лех, конкретная проблема в том, что у тебя componentWillReceiveProps может неожиданно изменить состояние внутреннее компоненты. И таким образом результаты теста будут зависеть всегда от вызова этой функции, хотя ты в тестах не должен думать о том, что у тебя componentWillReceiveProps каким-то образом что то делает, это по-хорошему должно быть инкапсулировано

2019-03-21 05:22 UTC, chmnkh commented on src/features/profile/view/containers/ProfilePreview/__tests__/index.test.tsx
> +  const component = mount(<ProfilePreview {...props}/>); // mount required for popover to work
> Т.е. для тебя наличие сайд эффекта на этапе подготовки компоненты к тестированию - не проблема?

Для меня потенциальное наличие сайд эффекта - это потенциальное наличие сайд эффекта) Тупо факт возможности наличия чего-то !== проблема в общем случае.

> И я не понимаю в чем проблема использовать чистый и гибкий getComponent вместо проблемной связки beforeEach + setProps?

В том, о чем ты сам писал: в необходимости каждый раз руками рендерить компонент.

> И таким образом результаты теста будут зависеть всегда от вызова этой функции

Вообще, есть два кейса. Тестируемое поведение компоненты с определенным набором пропсов:
1. одинаково при маунте и при апдейте;
2. различается при маунте и при апдейте.

Так вот результаты теста будут зависеть от вызова этой функции только во втором случае.

> хотя ты в тестах не должен думать о том, что у тебя componentWillReceiveProps каким-то образом что то делает

На мой взгляд, напротив, я должен быть четко в курсе, есть ли какая-то доп. логика при апдейте компоненты. Потому что если она есть - это нужно дополнительно покрывать. Но чаще поведение компоненты с какими-то пропсами в произвольный момент ее жизненного цикла одинаково.

Вы мне как будто предлагаете закрыть глаза и притвориться, что апдейта не существует, а есть только маунт. И вот на маунте все хорошо, а на апдейте происходит неконтролируемая дичь и лучше туда не соваться. А я говорю о том, что нам по дефолту без разницы, тестим ли мы после апдейта или после маунта. Например, когда я тещу рендер стрелки пагинации на первой странице (типа левая стрелка не рендерится на первой странице), мне неважно, когда пришла эта пропса. Может я неверно мыслю, но для меня, по дефолту, компонента ведет себя именно так. Если же это не так и на апдейте какая-то дополнительная фигня появляется - то это дополнительная логика и она должна дополнительно тестироваться.

2019-03-21 08:49 UTC, Znack commented on src/features/profile/view/containers/ProfilePreview/__tests__/index.test.tsx
> +  const component = mount(<ProfilePreview {...props}/>); // mount required for popover to work
Не, тестировать апдейт надо, просто не надо думать о том, что ты всегда на это рассчитываешь. просто это должно быть двумя разными тестами — один набор для самого рендера, который работает при определенном наборе пропсов, и другой набор тестов, который демонстрирует, как компонент реагирует на изменения пропсов, и вот тут тебе как раз setProps и нужен будет, в других случаях его лучше избегать.

> На мой взгляд, напротив, я должен быть четко в курсе, есть ли какая-то доп. логика при апдейте компоненты.
Главное тут не нарушать инкапсуляцию. Я не хочу в тестах знать и полагаться на то, что у меня каким-то образом componentWillReceiveProps отработает даже в тривиальных случаях. Ну и ты оставляешь неоттестированным начальный рендер компонента с таким подходом, а я предлагаю и начальный рендер сразу после конструирования компоненты тестить, и конкретный на изменения пропсов после setProps

> Для меня потенциальное наличие сайд эффекта - это потенциальное наличие сайд эффекта) Тупо факт возможности наличия чего-то !== проблема в общем случае.
На самом деле лишние сайд эффекты — это проблема, их надо по максимуму укрощать и контролировать :)

2019-03-21 11:56 UTC, chmnkh commented on src/features/profile/view/containers/ProfilePreview/__tests__/index.test.tsx
> +  const component = mount(<ProfilePreview {...props}/>); // mount required for popover to work
> Главное тут не нарушать инкапсуляцию. Я не хочу в тестах знать и полагаться на то, что у меня каким-то образом componentWillReceiveProps отработает даже в тривиальных случаях. 

почему полагаться на то, как componentWillReceiveProps отработает - это нарушение инкапсуляции, а полагаться на то, как отработает, например, рендер или конструктор, ну или даже componentDidMount (в случае с mount) - это не нарушение инкапсуляции?

> Ну и ты оставляешь неоттестированным начальный рендер компонента с таким подходом, а я предлагаю и начальный рендер сразу после конструирования компоненты тестить, и конкретный на изменения пропсов после setProps

не понял, ты предлагаешь тестировать одно и то же поведение 2 раза всегда?

> На самом деле лишние сайд эффекты — это проблема, их надо по максимуму укрощать и контролировать :)

Я может быть не познал еще дзен какой-то, но для меня сайд-эффекты - это явление, и оно уже может вызывать проблемы. А само по себе явление это просто явление. Я ожидал просто увидеть конкретные проблемы, которые эти сайд-эффекты вызывать могут в данном конкретном случае, а не просто указание на наличие сайд эффектов как таковых)

2019-03-21 12:17 UTC, in19farkt commented on src/features/profile/view/containers/ProfilePreview/__tests__/index.test.tsx
> +  const component = mount(<ProfilePreview {...props}/>); // mount required for popover to work
Если мы будем использовать setProps даже там где можно обойтись без него, то это уйдет в народ, и многие опираясь на пример из стартеркита, будут повсеместно юзать setProps, не задумываясь о том что скрыто под этим вызовом. Рано или поздно кто-нибудь наступит на эти грабли и потратит кучу времени пока поймет в чем причина крашнутых тестов.

Да, если ты один на проекте будешь писать тесты и ты знаешь про эту особенность, то для тебя это не проблема. Но проекты в одиночку не пишутся, разработчики на них меняются, тесты дописываются/редактируются и у всех разный уровень знаний. Поэтому-то в тестах должно быть как можно меньше сайд-эффектов и как можно меньше неочевидного (и не только в тестах :) )

2019-03-23 06:17 UTC, Znack commented on src/features/profile/view/containers/ProfilePreview/__tests__/index.test.tsx
> +  const component = mount(<ProfilePreview {...props}/>); // mount required for popover to work
> почему полагаться на то, как componentWillReceiveProps отработает - это нарушение инкапсуляции, а полагаться на то, как отработает, например, рендер или конструктор, ну или даже componentDidMount (в случае с mount) - это не нарушение инкапсуляции?

Ну окей, я криво сформулировал мысль :) Писать тесты, в которых в каждом кейсе по-любому будет неявный вызов componentWillReceiveProps, это значит не оттестировать кейс начального рендера в принципе. Также при написании таких тестов ты скорее всего не будешь в голове держать, что у тебя там componentWillReceiveProps вызывается, и если ты не придерживаешься строго TDD, то можешь в итоге написать тесты, которые проверяют с учетом вызова (ну потому что ты в ассертах будешь такие условия вставлять, которые только при componentWillReceiveProps будут иметь смысл).

> не понял, ты предлагаешь тестировать одно и то же поведение 2 раза всегда?

не, я предлагаю тестить отдельно то, как компонент реагирует на изменения пропсов в отдельных тестах только тогда, когда это дейсвтительно надо тестить. В остальных случаях теста только начального рендера без setProps будет достаточно.

> Я ожидал просто увидеть конкретные проблемы, которые эти сайд-эффекты вызывать могут в данном конкретном случае, а не просто указание на наличие сайд эффектов как таковых)

Сайд-эффект это просто явление, и ты можешь на него смотреть просто как на явление как таковое. Однако это явление неявное, непредсказуемое и чаще всего, трудноконтролируемое извне (из тестов). Поэтому сами по себе сайд эффекты делают по умолчанию код менее тестируем (или труднотеструемым), и от этого их применение стоит ограничивать

2019-03-24 15:17 UTC, chmnkh commented on src/features/profile/view/containers/ProfilePreview/__tests__/index.test.tsx
> +  const component = mount(<ProfilePreview {...props}/>); // mount required for popover to work
> Писать тесты, в которых в каждом кейсе по-любому будет неявный вызов componentWillReceiveProps, это значит не оттестировать кейс начального рендера в принципе. Также при написании таких тестов ты скорее всего не будешь в голове держать, что у тебя там componentWillReceiveProps вызывается, и если ты не придерживаешься строго TDD, то можешь в итоге написать тесты, которые проверяют с учетом вызова (ну потому что ты в ассертах будешь такие условия вставлять, которые только при componentWillReceiveProps будут иметь смысл).

я чего не понимаю сейчас: все то, что вы мне с Димой пытаетесь донести, можно применить на случай изначального рендера, заменив вызов componentWillReceiveProps на componentDidMount. В чем разница-то? По существу это же та же самая фигня, только разные методы будут вызываться.

2019-03-24 15:20 UTC, in19farkt commented on src/features/profile/view/containers/ProfilePreview/__tests__/index.test.tsx
> +  const component = mount(<ProfilePreview {...props}/>); // mount required for popover to work
не понял причем тут componentDidMount. Если мы не используем setProps, то из методов жизненного цикла отрабатывает только componentWillMount, и тот скоро станет депрекейтед и будет випилен из реакта.

2019-03-24 15:26 UTC, chmnkh commented on src/features/profile/view/containers/ProfilePreview/__tests__/index.test.tsx
> +  const component = mount(<ProfilePreview {...props}/>); // mount required for popover to work
> As of Enzyme v3, the shallow API does call React lifecycle methods such as componentDidMount and componentDidUpdate.

2019-03-24 15:29 UTC, in19farkt commented on src/features/profile/view/containers/ProfilePreview/__tests__/index.test.tsx
> +  const component = mount(<ProfilePreview {...props}/>); // mount required for popover to work
эм, ну вообще это оч странно, ладно диди маунт, но еще и дид апдейт дергает...

2019-03-25 07:33 UTC, chmnkh commented on src/features/profile/view/containers/ProfilePreview/__tests__/index.test.tsx
> +  const component = mount(<ProfilePreview {...props}/>); // mount required for popover to work
обсудили с Серегой ирл, итого:
1) теоретически сайд эффекты могут быть везде (в том числе и в componentDidMount, в рендере, где угодно), но поскольку мы их вообще в целом стараемся избегать, то если у нас есть возможность потенциальный источник сайд эффектов (componentWillReceiveProps, например) убрать из логики, то лучше это сделать;
2) даже если сайд эффекты в componentWillReceiveProps не влияют на текущий тест кейс в большинстве случаев, лучше все равно такой штуки избегать (аргументация та же что и в п.1);
3) подход с beforeEach не оч, потому что подготовка компоненты к тестам разбросана по коду (тест кейсы берут component, который рендерится в beforeEach). По сути, в тест кейсе ты должен быть уверен, что снаружи где-то кто-то нормально этот компонент для тебя подготовит. Если делать рендер компоненты отдельно в каждом тест кейсе, то тесты будут по настоящему независимы и будет проще видеть что вообще за компонента тестится;
4) в принципе использование setProps говорит о том, что компонента уже была создана и апдейтится, что выглядит не совсем естественно и сложнее, чем нам нужно, а нужно нам проверить поведение при каких-то значениях пропсов. Для этого достаточно просто создать компоненту. 

@Znack глянь, может я что-то переврал/не дописал случайно)

2019-03-25 08:14 UTC, in19farkt commented on src/features/profile/view/containers/ProfilePreview/__tests__/index.test.tsx
> +  const component = mount(<ProfilePreview {...props}/>); // mount required for popover to work
@chmnkh а мы можем как-то по дефолту для всех тестов вырубить componentDidMount and componentDidUpdate на шелоу?

2019-03-25 08:29 UTC, chmnkh commented on src/features/profile/view/containers/ProfilePreview/__tests__/index.test.tsx
> +  const component = mount(<ProfilePreview {...props}/>); // mount required for popover to work
это то можно, но если нам их затестить нужно будет где-то?

2019-03-25 08:34 UTC, in19farkt commented on src/features/profile/view/containers/ProfilePreview/__tests__/index.test.tsx
> +  const component = mount(<ProfilePreview {...props}/>); // mount required for popover to work
[Тут](https://airbnb.io/enzyme/docs/guides/migration-from-2-to-3.html#lifecycle-methods) нашел
```
const wrapper = shallow(<Component />, { disableLifecycleMethods: true });
```

2019-03-25 08:36 UTC, in19farkt commented on src/features/profile/view/containers/ProfilePreview/__tests__/index.test.tsx
> +  const component = mount(<ProfilePreview {...props}/>); // mount required for popover to work
Я так понял дидАпдейт вызывается только на setProps или setContext, и если мы по дефолту вырубим методы жизненного цикла, то на setProps не будет вызван дид апдейт...

2019-03-25 08:58 UTC, chmnkh commented on src/features/profile/view/containers/ProfilePreview/__tests__/index.test.tsx
> +  const component = mount(<ProfilePreview {...props}/>); // mount required for popover to work
да, но я бы таким заниматься наверное все-таки не стал, сильно неочевидная херня)

2019-03-25 10:37 UTC, chmnkh commented on src/features/profile/view/containers/ProfilePreview/__tests__/index.test.tsx
> +  const component = mount(<ProfilePreview {...props}/>); // mount required for popover to work
перепилил здесь https://github.com/fullstack-development/react-redux-starter-kit/pull/81/commits/1bf34e76218170c1c556e501354b4e2838fac754

я кстати внезапно осознал, что у меня все тест кейсы шарили в ассертах на коллбэки одну и ту же функцию, это тоже переписал вот тут https://github.com/fullstack-development/react-redux-starter-kit/pull/81/commits/6b4e78429b018cb61ba539277e3b556b85c07219

2019-03-26 07:32 UTC, chmnkh commented
@clicktronix @in19farkt @NikitaRzm эсли у вас нету замечаний то аппруве, пожалуйста)

2019-03-26 07:40 UTC, in19farkt commented
Я сейчас сяду просматривать ПР, сегодня дам фидбек

2019-03-26 09:30 UTC, clicktronix approved these changes

2019-03-26 12:06 UTC, in19farkt requested changes

2019-03-26 12:06 UTC, in19farkt commented on src/features/profile/view/containers/ProfilePreview/__tests__/index.test.ts
> +  });
тут еще можно затестить факт закрытия поповера, что-то типа "should hide popover with profile info on popover close"

2019-03-26 12:06 UTC, in19farkt commented on src/features/repositoriesSearch/view/components/RepositoryPreview/RepositoryPreview.tsx
> +export { IProps as IRepositoryPreviewProps };
Нет тестов на эту компененту

2019-03-26 12:06 UTC, in19farkt commented on src/features/repositoriesSearch/view/containers/RepositoriesSearchForm/__tests__/index.test.ts
> +    const searchForm = component.find(SearchForm);
Можно было в константу не писать, было бы немного короче) Во многих местах ты так пишешь

2019-03-26 12:06 UTC, in19farkt commented on src/features/usersSearch/view/containers/UsersSearchResults/__tests__/index.test.ts
> +  });
Не хватает теста на скрытие UserDetails

2019-03-26 12:06 UTC, in19farkt commented on src/modules/Profile/view/components/ProfileLayout/ProfileLayout.tsx
> +export default withLayout('Edit profile')(
Не понимаю зачем ты переписал это на HOC, по мне так прошлый вариант в данном случае уместнее, привычнее и гибче.

2019-03-26 12:06 UTC, in19farkt commented on src/modules/shared/Layout/LayoutHeaderMenu/__tests__/index.test.ts
> +describe('(modules/shared) LayoutHeaderMenu component', () => {
Практически все тесты крашатся из-за типов

2019-03-26 12:06 UTC, in19farkt commented on src/modules/shared/Layout/__tests__/index.test.ts
> +    const history = R.clone(props.history);
Разве `R.clone` пересоздает функцию `push` находящуюся внутри `props.history`?

Тут похоже между тест-кейсами будет шариться один и тот же экземплар функции push.

2019-03-26 12:06 UTC, in19farkt commented on src/modules/shared/Layout/__tests__/index.test.ts
> +    const history = R.clone(props.history);
Поидее нужно сделать что-то типа
```
const history = { ...props.history, push: jest.fn() };
```

2019-03-26 12:06 UTC, in19farkt commented on src/shared/view/components/PaginationControls/__tests__/index.test.ts
> +describe('(shared/view) PaginationControls component', () => {
Не хватает теста на соблюдение ограниечения на кол-во отрисовываемых элементов `page`

2019-03-26 12:06 UTC, in19farkt commented on src/shared/view/components/PaginationControls/__tests__/index.test.ts
> +describe('(shared/view) PaginationControls component', () => {
И еще, в компоненте я бы все кликабельные div заменил на button, а вместо хидена стрелок вешал бы на них disabled и делал бы opacity на disabled.

2019-03-26 12:06 UTC, in19farkt commented on src/shared/view/components/SearchForm/__tests__/index.test.ts
> +describe('(shared/view) SearchForm component', () => {
Не затестил:
- наличие/отсутствие элемента `settings` в зависимости от пропса `renderSettings`
- открытие/закрытие `SearchSettingsDialog`

2019-03-26 12:06 UTC, in19farkt commented on src/shared/mocks.ts
> +export const makeMockContainer: any = (containerName: string) => {
Тут похоже `any` не там написано, наверное должно быть так:
```
export const makeMockContainer = (containerName: string): any => {
```
А мы не можем тут вместо `any` написать `React.ComponentType<any>`?

2019-03-26 12:12 UTC, chmnkh commented on src/modules/shared/Layout/__tests__/index.test.ts
> +    const history = R.clone(props.history);
> Разве `R.clone` пересоздает функцию `push` находящуюся внутри `props.history`?

блин, на самом деле, все объекты копируются, а вот функция - нет :<

2019-03-26 12:35 UTC, in19farkt commented
Сейчас просматривал тесты и пришел к выводу, что тесты на снапшотах, которые мы на многих проектах нахерачили, полная дич. 

## Как со снапшотами:
- мы подготавливаем компоненту
- делаем снапшот
- и тупо сравниваем снапшот с компонентой
### Плюсы:
- тесты очень быстро и легко писать
### Минусы:
- нихера не понятно из прочтения тесткейса, какой именно результат мы зафиксировали в снапшоте, и не понятно что именно из всего снапшота важно в конкретном тесткейсе.

## Как без снапшотов:
- мы подготавливаем компоненту
- с помощью энзима достаем из нее важные в данном тесткейсе детали
- точечно делаем конкретные проверки
### Плюсы:
- читаешь тесткейс и сразу понимаешь что именно тестируется, как оно должно работать, какие действия к какому результату должны привести
- если ты первый раз видишь компоненту, то прочитав такие тесты ты намного быстрее и полнее поймешь логику работы компоненты, чего нельзя сказать про тесты на снапшотах
### Минусы:
- тесты писать немного сложнее.

2019-03-26 13:40 UTC, clicktronix commented
@in19farkt я думаю снэпшопты все равно полезное говно. Особенно со сторонними либами - отслеживать прокидываемые пропсы куда проще. Они просто выступают в роли индикатора изменений в компоненте, особо сильной тестовой нагрузки не несут, но если сделать пару снэпшотов для компоненты, то при малейших изменениях они проинформируют тебя о том, что что-то изменилось. И по хорошему надо идти и смотреть, что ты накодил, а не нажимать U в консоли) Я думаю пара тестов на сравнение снэпшотов с разными пропсами для каждой вьюхи будет полезно. А более сложную логику, конечно, лучше тестить энзимом

2019-03-26 14:12 UTC, in19farkt commented
По поводу пропсов. Фиксируются только не функциональные пропсы, и мне кажется смысла в этой фиксации не очень много. Ну зафиксировали что какой-то пропс куда-то передается, и че? 

Опять же если тебе надо потестить преобразование какого-то пропса с дальнейшим прокидыванием вглубь, ты нахерачишь гору снапшотов, в которых помимо того что нужно, будет огромное кол-во лишнего хлама.

По поводу индикации изменений. А гит разве с этим не справляется? 99% крашнутых снапшотов будут информировать об измененной верстке, о добавленном поле в какой нибудь пропс-объект и о прочей не важной херне. Особенно мне нравилось изменять интерфейсы модели: добавляешь поле и у тебя 100500 снапшотов крашится :)

Я к тому, что снапшоты слишком громоздкие и использовать их так как мы использовали их раньше - нельзя. В тупой фиксации верстки и прокидываемых вглубь пропсов я особого смысла не вижу, а для остального снапшоты не очень-то подходят.

2019-03-26 14:42 UTC, clicktronix commented
Не понял при чем тут гит) Ты накодил изменений во вьюхах, поменял пропсы. Запустились тесты, крашнулись снэпшоты, это заставляет тебя пойти в код тестов, посмотреть что там не так и если нужно, дописать тестов на новую логику. Тут главное не обновлять бездумно снэпшоты. 

Я не говорю что надо тестить прокидывание пропсов в глубь с помощью снжпшотов, а просто сделать пару снэпшотов с разными пропсами, чтобы изменения во вьюхах заставляли заглянуть потом в тесты

2019-03-27 05:35 UTC, chmnkh commented on src/features/profile/view/containers/ProfilePreview/__tests__/index.test.ts
> +  });
а это ж функционал либы уже, а не наш

2019-03-27 06:16 UTC, chmnkh commented on src/features/repositoriesSearch/view/components/RepositoryPreview/RepositoryPreview.tsx
> +export { IProps as IRepositoryPreviewProps };
https://github.com/fullstack-development/react-redux-starter-kit/pull/81/commits/22c7df3f7c15a622e331a3c48baa5e78170cbfcf

2019-03-27 06:22 UTC, chmnkh commented on src/features/repositoriesSearch/view/containers/RepositoriesSearchForm/__tests__/index.test.ts
> +    const searchForm = component.find(SearchForm);
Убрал в некоторых местах. Оставил, где здоровый селектор и неудобно становится читать.

2019-03-27 06:32 UTC, chmnkh commented on src/modules/Profile/view/components/ProfileLayout/ProfileLayout.tsx
> +export default withLayout('Edit profile')(
мне кажется вариант просто вызвать функцию с тайтлом проще, чем писать дополнительную компоненту, немного да засирая рендер. Да, хок так же засирает код, но на уровне экспортов это менее страшно, имхо.

2019-03-27 06:45 UTC, chmnkh commented on src/modules/shared/Layout/LayoutHeaderMenu/__tests__/index.test.ts
> +describe('(modules/shared) LayoutHeaderMenu component', () => {
https://github.com/fullstack-development/react-redux-starter-kit/pull/81/commits/5f04389d9d6fa8017b4daca5265eea8008083e2d

2019-03-27 06:59 UTC, chmnkh commented on src/shared/view/components/PaginationControls/__tests__/index.test.ts
> +describe('(shared/view) PaginationControls component', () => {
> И еще, в компоненте я бы все кликабельные div заменил на button, а вместо хидена стрелок вешал бы на них disabled и делал бы opacity на disabled.

мне это очень неестественным кажется
стрелки еще может быть можно баттонами сделать, а цифры - хз, какая-то дичь

2019-03-27 08:24 UTC, chmnkh commented on src/shared/view/components/SearchForm/__tests__/index.test.ts
> +describe('(shared/view) SearchForm component', () => {
https://github.com/fullstack-development/react-redux-starter-kit/pull/81/commits/734273de66199427d9f8d7c0ec2f80787b918fba

2019-03-27 08:27 UTC, chmnkh commented on src/shared/mocks.ts
> +export const makeMockContainer: any = (containerName: string) => {
хм, оказалось, что можем

2019-03-27 08:43 UTC, NikitaRzm commented on src/shared/view/components/PaginationControls/__tests__/index.test.ts
> +describe('(shared/view) PaginationControls component', () => {
Любой интерактив должен быть выполнен интерактивными html элементами, кнопки тоже в баттон.

2019-03-27 08:58 UTC, in19farkt commented on src/features/profile/view/containers/ProfilePreview/__tests__/index.test.ts
> +  });
Не, ты протестил что флаг open становится true при нажатии на аватар, а закрытие не протестил, что флажок можно вернуть обратно в false.

2019-03-27 09:16 UTC, in19farkt commented on src/modules/Profile/view/components/ProfileLayout/ProfileLayout.tsx
> +export default withLayout('Edit profile')(
По мне так единственное место где нужны хоки, это когда нужно изменить сигнатуру оборачиваемой компоненты, а именно тип принимаемых компонентой пропсов, для того чтобы прокинуть какие-то данные в компоненту (возможно исходя из принятых пропсов). 

Здесь же ты просто добавляешь одну обертку вокруг верстки этой компоненты. По мне это не очень очевидно и немного сложнее поддерживать.

Если мы будем для такого использовать хоки, то потенциально можем вообще отказаться от jsx и вернуться к React.createElement, синтаксис получится примерно такой же :)

2019-03-27 09:19 UTC, in19farkt commented on src/modules/Profile/view/components/ProfileLayout/ProfileLayout.tsx
> +export default withLayout('Edit profile')(
ну и опять же, это сейчас у тебя в лаяут можно отдать только тайтл. Но там со временем может появиться больше пропсов, и тогда вариант с хоком будет намного менее читаемым и удобным.

А еще может понадобиться перенаправить входящий пропс в лаяут, тут вообще не понятно как такое с хоком сделать.

2019-03-27 09:20 UTC, NikitaRzm commented on src/modules/Profile/view/components/ProfileLayout/ProfileLayout.tsx
> +export default withLayout('Edit profile')(
Тут в пользу отказаться от хока - где можно без него вставлю свои пять копеек: хоки увеличивают вложенность в дереве virtual-dom, это сказывается на перфомансе, если вдруг хок достаточно часто используется, структура виртуал-дома становится солидно и неоправданно увеличена и вложена, замечается лишь на реально большом количестве компонентов - сложность O(n), чем их меньше - тем лучше )

2019-03-27 09:23 UTC, in19farkt commented on src/modules/Profile/view/components/ProfileLayout/ProfileLayout.tsx
> +export default withLayout('Edit profile')(
@NikitaRzm это у нас с переводами такая проблема, они на каждом углу и прокидываются хоками. Хуки как раз решают эту проблему)

2019-03-27 09:40 UTC, chmnkh commented on src/features/profile/view/containers/ProfilePreview/__tests__/index.test.ts
> +  });
да, чото я дичь сказал

2019-03-27 10:09 UTC, chmnkh commented on src/shared/mocks.ts
> +export const makeMockContainer: any = (containerName: string) => {
оказалось что не можем, потому что нужны разные типы для контейнеров и не-контейнеров

2019-03-27 10:57 UTC, chmnkh commented on src/shared/view/components/PaginationControls/__tests__/index.test.ts
> +describe('(shared/view) PaginationControls component', () => {
с аутлайнами чо делать тогда раз уж на то пошло? если уберу табаться нельзя будет, оставлять какие-то доп стили после того, как тыкнул на элемент, тоже дичь, как поступить?

2019-03-27 13:22 UTC, in19farkt commented on src/shared/view/components/PaginationControls/__tests__/index.test.ts
> +describe('(shared/view) PaginationControls component', () => {
а чем тебе аутлайны не угодили? Просто убирать их точно нельзя, можно переопределить обработку фокусов.

Можешь посмотреть как муишные кнопки обрабатывают всё это, или вообще взять MuiButtonBase и на его основе написать свою кнопку

Тут апи https://material-ui.com/api/button-base/
Тут пример написания своей кнопки https://material-ui.com/demos/buttons/#complex-buttons

2019-03-28 05:47 UTC, chmnkh commented on src/shared/view/components/PaginationControls/__tests__/index.test.ts
> +describe('(shared/view) PaginationControls component', () => {
> Можешь посмотреть как муишные кнопки обрабатывают всё это

да там понятно что js, просто не хотелось руками это напиливать

ButtonBase помог, да, спасибо

https://github.com/fullstack-development/react-redux-starter-kit/pull/81/commits/1d52289543a1cf4b008137f59fd280b3c9587489

2019-03-28 07:43 UTC, in19farkt approved these changes

2019-03-28 07:45 UTC, in19farkt commented
@NikitaRzm если тебя всё устраивает, то дай аппрув и буду мержить)

2019-03-28 10:11 UTC, NikitaRzm approved these changes

2019-03-28 12:46 UTC, merged

2019-03-28 12:48 UTC, Znack commented
Ееееее!!!