wip 74 demo app tests helpers
fullstack-development/react-redux-starter-kit pull request #86
Opened 2019-03-12 10:01 UTC by chmnkh

2019-03-29 09:13 UTC, Znack requested changes

2019-03-29 09:13 UTC, Znack commented on src/shared/helpers/__tests__/makeFeatureEntry.ts
> +    expect(featureEntry.sagas).toBe(reduxEntry.sagas);
А там никакой логики нигде нету? Просто так мапание из аргументов в структурку не очень интересно тестить :)

2019-03-29 09:13 UTC, Znack commented on src/shared/helpers/react/__tests__/areComponentsEqual.test.ts
> +    expect(areComponentsEqual(FirstComponent, FirstComponent)).toBe(true);
а если сравнить два вызова `makeMockComponent('FirstComponent')`?

2019-03-29 09:13 UTC, Znack commented on src/shared/helpers/react/__tests__/getFieldWithComponent.test.ts
> +    expect(areAllPropsPassed).toBe(true);
```
    const passedProps = R.intersection(
      outerPropsNames.concat('component', 'type'),
      fieldPropsNames,
    )
    expect(passedProps.length).toBe(fieldPropsNames.length)
```

я бы так лучше написал, слишком вербозная конструкций areAllPropsPassed, в объявлении которой много деталей и то что именно длины сравниваются сразу не увидишь

2019-03-29 09:13 UTC, Znack commented on src/shared/helpers/react/__tests__/withComponent.test.ts
> +    expect(areAllPropsPassed).toBe(true);
тут тоже как выше

2019-03-29 09:13 UTC, Znack commented on src/shared/helpers/style/__tests__/rule.test.ts
> +    expect(rule(props)).toBe(props);
а тут больше нет кейсов? :) Я из тестов не совсем понял, что делает rule

2019-03-29 09:13 UTC, Znack commented on src/shared/helpers/redux/__tests__/makeResetStateReducer.test.ts
> +  it('should reset state if dispatched action is reset action', () => {
лучше сначала позитивные тест кейсы тестить, которые говорят об основном назначении компонента, а потом все негативные, которые тестят, что тест не меняет то, что не должен :)

2019-03-29 09:15 UTC, chmnkh commented on src/shared/helpers/style/__tests__/rule.test.ts
> +    expect(rule(props)).toBe(props);
это тупо для типизации жсс стилей

2019-03-29 10:51 UTC, in19farkt commented on src/shared/helpers/__tests__/makeFeatureEntry.ts
> +    expect(featureEntry.sagas).toBe(reduxEntry.sagas);
тут было бы интереснее затестить типы, например, с помощью вот этой штуки https://github.com/Microsoft/dtslint

2019-03-29 10:53 UTC, in19farkt commented on src/shared/helpers/react/__tests__/areComponentsEqual.test.ts
> +    expect(areComponentsEqual(FirstComponent, FirstComponent)).toBe(true);
должно получиться true, по сути этот хелпер - это костыль, чтобы сравнение работало с react-hot-reload'ом

2019-03-29 11:00 UTC, Znack commented on src/shared/helpers/style/__tests__/rule.test.ts
> +    expect(rule(props)).toBe(props);
Не, ну а как именно функцией пользоваться, тесты на это должны отвечать в том числе :)

2019-04-01 09:04 UTC, chmnkh commented on src/shared/helpers/style/__tests__/rule.test.ts
> +    expect(rule(props)).toBe(props);
https://github.com/fullstack-development/react-redux-starter-kit/pull/86/commits/1355cd0a79df5add82f655d0a52faf04680f9162

2019-04-01 09:05 UTC, chmnkh commented on src/shared/helpers/__tests__/makeFeatureEntry.ts
> +    expect(featureEntry.sagas).toBe(reduxEntry.sagas);
мм, я мб не понял чото, ноа смысл тестить типы, если они и без того проверяются?

2019-04-01 09:11 UTC, in19farkt commented on src/shared/helpers/__tests__/makeFeatureEntry.ts
> +    expect(featureEntry.sagas).toBe(reduxEntry.sagas);
Смысл этого хелпера: по мимо того чтобы собрать всё в кучку, он формирует тип без лишних полей. Вот это и нужно затестить, что если ты не отдал контейнеры в хелпер, то в возвращаемом типе нет поля контейнерс

2019-04-01 09:22 UTC, in19farkt commented on src/shared/helpers/__tests__/makeFeatureEntry.ts
> +    expect(featureEntry.sagas).toBe(reduxEntry.sagas);
ну и вывод типа можно немного модифицировать, на новой версии тс я думаю можно поаккуратнее это реализовать

2019-04-01 09:30 UTC, chmnkh commented on src/shared/helpers/__tests__/makeFeatureEntry.ts
> +    expect(featureEntry.sagas).toBe(reduxEntry.sagas);
то о чем ты говоришь, можно только с последним параметром (redux) проделать
в остальных случаях, если мы ничего не хотим передавать, то мы передаем `null`, и у нас поле есть, но с `null` внутри 

вообще кстати не совсем понятно, почему все параметры вот таким вот образом сделаны, а redux - иначе

2019-04-01 09:40 UTC, in19farkt commented on src/shared/helpers/__tests__/makeFeatureEntry.ts
> +    expect(featureEntry.sagas).toBe(reduxEntry.sagas);
не, мы должны отдать туда null, но в возвращаемом типе нет этого поля.

2019-04-01 09:41 UTC, in19farkt commented on src/shared/helpers/__tests__/makeFeatureEntry.ts
> +    expect(featureEntry.sagas).toBe(reduxEntry.sagas);
в случае с редаксом нам не важно что там внутри этого редаксЭнтри, а для всего остального нам важен тип

2019-04-01 09:53 UTC, chmnkh commented on src/shared/helpers/__tests__/makeFeatureEntry.ts
> +    expect(featureEntry.sagas).toBe(reduxEntry.sagas);
> не, мы должны отдать туда null, но в возвращаемом типе нет этого поля.

в смысле в типе нету но на самом деле есть? это норм?

2019-04-01 10:01 UTC, in19farkt commented on src/shared/helpers/__tests__/makeFeatureEntry.ts
> +    expect(featureEntry.sagas).toBe(reduxEntry.sagas);
да, действительно странно)) нужно тогда дописать такое `containers: containers || void 0`

2019-04-01 10:40 UTC, Znack approved these changes

2019-04-01 11:35 UTC, chmnkh commented on src/shared/helpers/__tests__/makeFeatureEntry.ts
> +    expect(featureEntry.sagas).toBe(reduxEntry.sagas);
там вообще с типами муть какая-то
мы возвращаем `export type ResultEntry<C, A, S> = C & A & S & IReduxEntry;`, при `redux?: IReduxEntry` -_-

2019-04-01 13:21 UTC, in19farkt commented on src/shared/helpers/__tests__/makeFeatureEntry.ts
> +    expect(featureEntry.sagas).toBe(reduxEntry.sagas);
Да, типы там корявые, скорее всего раньше чтобы сделать нормально пришлось бы еще больше усложнить сборку результирующего типа. Если есть возможность приведи там всё в порядок.

2019-04-02 18:51 UTC, in19farkt commented
@chmnkh посмотри этот коммит https://github.com/fullstack-development/react-redux-starter-kit/pull/86/commits/36223587af5a1df7cafc309aa6b4930ed9f04b2c, немного изменил makeFeatureEntry. Я хз зачем там раньше было так сложно))

И еще в этой ветке сейчас тесты на PaginationControls крашатся.

2019-04-03 05:23 UTC, chmnkh commented
то что пагинация крашится это норм, последний закрытый пр это фиксит, в мастере все ок)
а нафиг ты тест для мейкфичаентри удалил? :<

2019-04-03 05:30 UTC, chmnkh commented on src/shared/helpers/__tests__/makeFeatureEntry.ts
> +    expect(featureEntry.sagas).toBe(reduxEntry.sagas);
уот такой вот тест вышел после рефакторинга https://github.com/fullstack-development/react-redux-starter-kit/pull/86/commits/8de787fcccf295a1ba644f1426cdf12c318ecabb

тест похож на тест для rule

2019-04-03 05:41 UTC, in19farkt commented
> то что пагинация крашится это норм, последний закрытый пр это фиксит, в мастере все ок)

Ну дык надо мастера мержнуть сюда, негоже ветку с корявыми тестами мержить))

> а нафиг ты тест для мейкфичаентри удалил? :<

А там теперь тестить нечего) Оно теперь работает как rule для jss

2019-04-03 05:51 UTC, chmnkh commented
> Ну дык надо мастера мержнуть сюда, негоже ветку с корявыми тестами мержить))

вмержил

> А там теперь тестить нечего) Оно теперь работает как rule для jss

ну по крайней мере с тестом (как и в случае с rule) будет явно видно, что только для типизации написано и так задумано)

2019-04-03 05:52 UTC, in19farkt commented
> ну по крайней мере с тестом (как и в случае с rule) будет явно видно, что только для типизации написано и так задумано)

Ну да, тоже аргумент. Допиши, плиз, если ты сейчас в этой ветке)

2019-04-03 05:54 UTC, chmnkh commented
да оно запушено уже))

2019-04-03 05:58 UTC, chmnkh commented on src/shared/helpers/__tests__/makeFeatureEntry.ts
> +    expect(featureEntry.sagas).toBe(reduxEntry.sagas);
заменил в тесте toBe на toEqual https://github.com/fullstack-development/react-redux-starter-kit/pull/86/commits/65bec9a021e6ba4567d9da7e4e3a48eaa207cf51

2019-04-03 06:02 UTC, in19farkt commented on src/shared/helpers/__tests__/makeFeatureEntry.test.ts
> +    expect(featureEntry).toEqual(entry);
@chmnkh  а тебе не кажется что здесь уместнее всё же toBe, ведб он делает строгое стравнение по ссылке, а toEqual делает глубокое сравнение.

2019-04-03 06:02 UTC, in19farkt commented on src/shared/helpers/style/__tests__/rule.test.ts
> +    expect(JSSStyles).toEqual(JSSStylesWithType);
тут тоже самое.

2019-04-03 06:13 UTC, chmnkh commented on src/shared/helpers/__tests__/makeFeatureEntry.test.ts
> +    expect(featureEntry).toEqual(entry);
toEqual нас страхует от мутаций, в то время как toBe - нет, поэтому мне кажется надежнее через toEqual проверять

2019-04-03 06:35 UTC, in19farkt commented on src/shared/helpers/__tests__/makeFeatureEntry.test.ts
> +    expect(featureEntry).toEqual(entry);
аа, теперь понял, про мутации не подумал чето)) да, тогда toEqual тут норм)

2019-04-03 06:38 UTC, in19farkt approved these changes

2019-04-03 06:39 UTC, merged