Lazy loading of features
fullstack-development/react-redux-starter-kit pull request #9
Opened 2017-11-02 09:25 UTC by Gulyaev52

2017-11-03 04:28 UTC, NikitaRzm requested changes

2017-11-03 04:28 UTC, NikitaRzm commented on src/features/dynamicFields/entry.ts
> +const actions = { ...act };
Запили хелпер типизированный )

2017-11-03 04:28 UTC, NikitaRzm commented on src/features/dynamicFields/redux/data/selectors.ts
> +function selectFields(state: any): IFields {
А в чем беда с типизацией?

2017-11-03 04:28 UTC, NikitaRzm commented on src/index.tsx
> +ReactDOM.render(<App {...appData} />, document.getElementById('root'));
А хот релоад то работает щас?

2017-11-03 04:28 UTC, NikitaRzm commented on src/shared/helpers/redux/makeCommunicationActionCreators.ts
> +example();
А это что? )

2017-11-03 04:28 UTC, NikitaRzm commented on src/shared/types/app.ts
> +import {} from 'shared/helpers/redux/multiConnect';
Empty?

2017-11-03 04:28 UTC, NikitaRzm commented on src/shared/types/app.ts
> +      throw new Error('Cannot find dependencies');
тут лучше null вернуть тогда, иначе тебе придется в коде-потребителе постоянно try-catch писать )

2017-11-03 04:28 UTC, NikitaRzm commented on webpack/dev.config.js
> -                    { loader: 'react-hot-loader/webpack' },
Почему хот-релоад удален?

2017-11-03 17:28 UTC, Znack approved these changes

2017-11-07 16:14 UTC, Znack approved these changes

2017-11-13 12:19 UTC, sk1e commented
А почему через bundle-loader? В новом вебпаке есть динамические импорты https://webpack.js.org/guides/code-splitting/#dynamic-imports. С ними проще всё это

2017-12-18 05:12 UTC, NikitaRzm approved these changes

2017-12-18 05:12 UTC, merged